import {expect,it} from 'vitest';
import {analyzeMaterials} from '../apps/api/src/material-analysis';
const component={component_id:'m',kind:'component',level:0,quantity:'0.420',snapshot:{name:'Material',unit_id:'kg',unit:'kg'}};
function review(good='1000',net='600'):any{return{company_id:'c',order_id:'o',status:'completed',good_quantity:good,order_snapshot:{bom:{id:'b',base_quantity:'1',snapshot:{},lines:[component]}},materials:[{issue_id:'i',item_id:'m',owner_id:'owner',unit_id:'kg',issued_quantity:'800',returned_quantity:'200',remaining_quantity:net,snapshot:{item:{name:'Material'},unit:{symbol:'kg'},owner:{name:'Owner'}}}]};}
it('800 issued minus 200 returned minus 500 theoretical is a 100 material difference, not automatic waste',()=>{const r=review();r.order_snapshot.bom.lines=[{...component,quantity:'0.5'}];const m=analyzeMaterials(r,[]).materials[0]!;expect(m.theoretical_quantity).toBe('500.00000000');expect(m.difference_quantity).toBe('100.00000000');expect(m.measured_waste_quantity).toBe('0.00000000');});
it('multiple materials, units and owners stay separate without duplicating theoretical consumption',()=>{const r=review();r.order_snapshot.bom.lines.push({...component,component_id:'label',quantity:'1',snapshot:{name:'Label',unit_id:'pcs',unit:'stk.'}});r.materials.push({...r.materials[0],issue_id:'i2',owner_id:'other',issued_quantity:'10',returned_quantity:'0',remaining_quantity:'10'});const a=analyzeMaterials(r,[]);expect(a.materials).toHaveLength(2);expect(a.materials[0]!.net_quantity).toBe('610.00000000');expect(a.materials[0]!.theoretical_quantity).toBe('420.00000000');expect(a.materials[0]!.owners).toHaveLength(2);expect(a.materials[1]!.unit).toBe('stk.');});
it('preserves rational precision, signed differences and undefined zero denominators',()=>{const r=review('1','0');r.order_snapshot.bom.base_quantity='3';r.order_snapshot.bom.lines=[{...component,quantity:'1'}];const m=analyzeMaterials(r,[]).materials[0]!;expect(m.theoretical_quantity).toBe('0.33333333');expect(m.difference_quantity).toBe('-0.33333333');expect(m.waste_percent).toBeNull();expect(m.difference_percent).toBeNull();expect(m.warnings).toContain('NEGATIVE_MATERIAL_DIFFERENCE');expect(BigInt(m.theoretical_exact!.numerator)*3n).toBe(BigInt(m.theoretical_exact!.denominator));});
it('zero good output and very large aggregates are valid and stay exact',()=>{const r=review('0','1000000000000000');const m=analyzeMaterials(r,[]).materials[0]!;expect(m.theoretical_quantity).toBe('0.00000000');expect(m.difference_quantity).toBe('1000000000000000.00000000');expect(m.difference_percent).toBe('100.00000000');});
it('flags mismatched or missing units and orphaned measured observations without treating missing theory as zero',()=>{const r=review();r.materials[0].unit_id='litre';const a=analyzeMaterials(r,[{item_id:'other',unit_id:'kg',owner_id:'owner',issue_id:'reversed',quantity:'1',snapshot:{stock:r.materials[0].snapshot}}]);expect(a.materials.find(m=>m.unit_id==='litre')!.warnings).toContain('UNIT_MISMATCH');const m=a.materials.find(m=>m.item_id==='other')!;expect(m.theoretical_quantity).toBeNull();expect(m.warnings).toContain('WASTE_ISSUE_REVERSED');expect(m.warnings).toContain('MEASURED_WASTE_EXCEEDS_NET');});
it('packing rounds partial containers once with accessories and handles zero output',()=>{const r=review('25','1');r.order_snapshot.packing={id:'p',base_quantity:'1',snapshot:{},lines:[{component_id:'box',kind:'container',level:0,quantity:'12',snapshot:{name:'Box',unit:'stk.',unit_id:'pcs'}},{component_id:'bag',kind:'accessory',level:0,quantity:'2',snapshot:{name:'Bag',unit:'stk.',unit_id:'pcs'}}]};const a=analyzeMaterials(r,[]);expect(a.materials.find(m=>m.item_id==='box')!.theoretical_quantity).toBe('3.00000000');expect(a.materials.find(m=>m.item_id==='bag')!.theoretical_quantity).toBe('6.00000000');r.good_quantity='0';expect(analyzeMaterials(r,[]).materials.every(m=>m.theoretical_quantity==='0.00000000')).toBe(true);});
