import {Surface,StatusBadge} from './VisualPrimitives';
import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {accessApi} from './auth-client';
export type DashboardTarget={page:'Produktion'|'Forsendelser'|'Modtagelse'|'Lager'|'Optælling';id?:string;q?:string};
type Alert={key:string;fingerprint:string;severity:'critical'|'attention';title:string;detail:string;state:'open'|'acknowledged'|'resolved';target:DashboardTarget};
type View={company_id:string;as_of:string;day:string;limited:string[];permissions:string[];alerts:Alert[];orders:{id:string;code:string;status:string;product?:string;quantity:string}[];shipments:{id:string;code:string;status:string}[];receipts:{id:string;reference:string;received_at:string;reversed:boolean}[]};
const msg=(e:unknown)=>e instanceof Error?e.message:'Dashboardet kunne ikke hentes.';
const status:Record<string,string>={draft:'Kladde',planned:'Planlagt',ready:'Klar',in_production:'I produktion',reconciliation:'Afstemning',reserved:'Reserveret',dispatched:'Afsendt',cancelled:'Annulleret'};
export function Dashboard({company,open}:{company:string;open:(target:DashboardTarget)=>void}){
 const base=`/companies/${company}/dashboard`,view=useQuery({queryKey:['dashboard',company],queryFn:async()=>{const v=await accessApi<View>(base);if(v.company_id!==company)throw new Error('Dashboardet har forkert virksomhed.');return v;},retry:false,refetchOnWindowFocus:false});
 const v=view.data;
 function group(title:string,alerts:Alert[]){if(!alerts.length)return null;return <Surface title={title+' · '+alerts.length} className="dashboard-alerts">{alerts.map(a=><article key={a.key+':'+a.fingerprint}><h3>{a.title}</h3><p>{a.detail}</p><button onClick={()=>open(a.target)}>Åbn {a.target.page.toLowerCase()}</button>{a.state==='open'&&v?.permissions.includes('dashboard.acknowledge')&&<Acknowledge base={base} alert={a} saved={async()=>{await view.refetch();}}/>}</article>)}</Surface>;}
 return <div className="dashboard"><div className="dashboard-toolbar"><span className="muted">Dagens overblik</span><button disabled={view.isFetching} onClick={()=>void view.refetch()}>Opdatér dashboard</button></div>{view.isPending&&<p>Henter dashboard…</p>}{view.error&&<p role="alert">{msg(view.error)} Genindlæs før du handler.</p>}{v&&!view.error&&<>
 {!!v.limited.length&&<p role="alert">Delvist overblik: {v.limited.join(', ')}. Åbn arbejdsområderne for alle poster. Fravær af advarsler er ikke en bekræftelse på, at alt er i orden.</p>}
<div className="dashboard-grid"><Surface title="Status" className="dashboard-status">{v.alerts.some(a=>a.state==='open')?<p>{v.alerts.filter(a=>a.state==='open').length} åbne advarsler</p>:<p>Ingen åbne advarsler i det viste udsnit.</p>}<small>Kun områder med læseadgang indgår.</small>{group('Kritiske advarsler',v.alerts.filter(a=>a.state==='open'&&a.severity==='critical'))}{group('Kræver opmærksomhed',v.alerts.filter(a=>a.state==='open'&&a.severity==='attention'))}</Surface><Surface title="Aktive produktioner">{!v.permissions.includes('production.read')?<p>Produktionsadgang mangler.</p>:v.orders.length?v.orders.map(o=><p key={o.id}><button onClick={()=>open({page:'Produktion',id:o.id})}>{o.code} · {o.product} · <StatusBadge tone={o.status==='in_production'?'success':'neutral'}>{status[o.status]??o.status}</StatusBadge> · {o.quantity}</button></p>):<p>Ingen aktive produktioner i udsnittet.</p>}</Surface>
 <Surface title="Dagens modtagelser og forsendelser"><h3>Dagens modtagelser</h3>{!v.permissions.includes('inventory.read')?<p>Lageradgang mangler.</p>:v.receipts.length?v.receipts.map(r=><p key={r.id}><button onClick={()=>open({page:'Modtagelse',id:r.id})}>{r.reference||'Modtagelse'} · {r.reversed?'Modposteret':'Bogført'}</button></p>):<p>Ingen modtagelser i dagens udsnit.</p>}<h3>Dagens forsendelser</h3>{!v.permissions.includes('shipments.read')?<p>Forsendelsesadgang mangler.</p>:v.shipments.length?v.shipments.map(s=><p key={s.id}><button onClick={()=>open({page:'Forsendelser',id:s.id})}>{s.code} · <StatusBadge>{status[s.status]??s.status}</StatusBadge></button></p>):<p>Ingen forsendelser i dagens udsnit.</p>}</Surface></div>
 <details className="dashboard-explanation"><summary>Om overblikket</summary><p>Opdateret {new Date(v.as_of).toLocaleString('da-DK')} · Dagens poster: {v.day} (dansk tid).</p><p>Kvitteret betyder set af dig; problemet er først løst, når grundlaget ikke længere udløser advarslen.</p></details>{v.alerts.some(a=>a.state==='acknowledged'||a.state==='resolved')&&<details className="dashboard-history" open={v.alerts.some(a=>a.state==='acknowledged'||a.state==='resolved') || undefined}><summary>Kvitterede og løste advarsler</summary>{group('Kvitteret af dig',v.alerts.filter(a=>a.state==='acknowledged'))}{group('Løste, tidligere kvitterede advarsler',v.alerts.filter(a=>a.state==='resolved'))}</details>}
 </>}</div>;
}
function Acknowledge({base,alert,saved}:{base:string;alert:Alert;saved:()=>Promise<void>}){
 const[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <><button disabled={busy} onClick={()=>{if(busy)return;setBusy(true);setError('');void accessApi(base+'/acknowledge','POST',{key:alert.key,fingerprint:alert.fingerprint}).then(saved).catch(e=>setError(msg(e)+' Ved ændret advarsel: opdatér dashboardet. Ved usikker forbindelse: prøv samme kvittering igen.')).finally(()=>setBusy(false));}}>Kvittér som set</button>{error&&<p role="alert">{error}</p>}</>;
}
