import {MoreInformation} from './MoreInformation';
import {QrLabel} from './Qr';
import {useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {accessApi} from './auth-client';
import {Picker} from './Inventory';
import {LocationPicker} from './Locations';
type Delivery={id:string;kind:string;quantity:string;reversed:boolean;pallet_code:string|null;handling_unit_id:string|null;created_at:string;comment:string;snapshot:{product:{name:string};owner:{name:string};unit:{symbol:string};location:{name:string}}};
export function FinishedGoods({company,orderId,status,canDeliver,canCorrect}:{company:string;orderId:string;status:string;canDeliver:boolean;canCorrect:boolean}){
 const base=`/companies/${company}/production-orders/${orderId}/deliveries`,cache=useQueryClient();
 const [quantity,setQuantity]=useState(''),[owner,setOwner]=useState(''),[location,setLocation]=useState<string|null>(null),[pallet,setPallet]=useState(''),[date,setDate]=useState(new Date().toLocaleDateString('en-CA')),[comment,setComment]=useState(''),[page,setPage]=useState(1),[pending,setPending]=useState<{path:string;body:object}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const sending=useRef(false);
 const summary=useQuery({queryKey:['deliveries',company,orderId,'summary',status],queryFn:()=>accessApi<{good_quantity:string;delivered_quantity:string;remaining_quantity:string;unit:{symbol:string};packing:{lines:{quantity:string;snapshot:{name:string}}[]}|null}>(base+'/summary'),retry:false});
 const history=useQuery({queryKey:['deliveries',company,orderId,page],queryFn:()=>accessApi<{items:Delivery[];total:number}>(base+`?page=${page}`),retry:false});
 async function refresh(){await cache.invalidateQueries({queryKey:['deliveries',company,orderId]});await cache.invalidateQueries({queryKey:['handling-units',company]});await cache.invalidateQueries({queryKey:['inventory',company]});}
 async function send(command:{path:string;body:object}){if(sending.current)return;sending.current=true;setBusy(true);setPending(command);setError('');try{await accessApi(command.path,'POST',command.body);setPending(null);setQuantity('');setComment('');await refresh();}catch(e){setError(e instanceof Error?e.message:'Afleveringen kunne ikke gemmes.');}finally{sending.current=false;setBusy(false);}}
 return <section className="access-card"><h3>Aflever færdigvarer til lager</h3><p>Aflever kun fysisk færdige varer. Produktionsregistrering og lageraflevering er separate handlinger. Én aflevering kan være én hel eller delvist fyldt palle eller en løs mængde.</p><button onClick={()=>void refresh()}>Opdatér afleveringer</button>
 {summary.error&&<p role="alert">Afleveringsgrundlaget kunne ikke hentes.</p>}{summary.data?.remaining_quantity!==undefined&&<p>Registreret godt: {summary.data.good_quantity} · Afleveret: {summary.data.delivered_quantity} · Kan afleveres: {summary.data.remaining_quantity} {summary.data.unit?.symbol}</p>}
 {Array.isArray(summary.data?.packing?.lines)&&<p>Ordren anvender den låste pakkeopbygning: {summary.data.packing.lines.map((l,i)=><span key={i}>{l.snapshot.name}: {l.quantity} · </span>)}</p>}
 {canDeliver&&['in_production','reconciliation','completed'].includes(status)&&<form onSubmit={e=>{e.preventDefault();if(pending||busy)return;if(window.confirm(`Aflever ${quantity} til lager? Den fysiske beholdning øges. Materiale og emballage forbruges ikke igen.`))void send({path:base,body:{idempotency_key:crypto.randomUUID(),quantity:quantity.replace(',','.'),owner_id:owner,location_id:location,pallet_type_id:pallet||null,production_date:date,comment}});}}><fieldset disabled={busy||!!pending}><label>Antal til lager<input required inputMode="decimal" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><Picker path={`/companies/${company}/inventory/owners`} label="Færdigvarernes ejer" value={owner} change={setOwner}/><LocationPicker company={company} label="Færdigvareplacering" value={location} change={setLocation} storageOnly/><MoreInformation enabled><Picker optional path={`/companies/${company}/masterdata/pallet_types`} label="Palletype (tom = løse varer)" value={pallet} change={setPallet}/><label>Produktionsdato<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>Afleveringskommentar<textarea maxLength={2000} value={comment} onChange={e=>setComment(e.target.value)}/></label></MoreInformation></fieldset><button className="primary" disabled={busy||!!pending||!location}>Bekræft lageraflevering</button></form>}
 {error&&<p role="alert">{error}</p>}{pending&&<button disabled={busy} onClick={()=>void send(pending)}>Prøv samme aflevering igen</button>}
 <h4>Afleveringshistorik</h4>{history.error&&<p role="alert">Historikken kunne ikke hentes.</p>}{Array.isArray(history.data?.items)&&history.data.items.map(d=><p key={d.id}>{new Date(d.created_at).toLocaleString('da-DK')} · {d.kind==='reversal'?'Modpostering':d.reversed?'Modposteret':'Afleveret'} · {d.quantity} {d.snapshot.unit.symbol} · {d.snapshot.owner.name} · {d.snapshot.location.name} · {d.pallet_code??'Løse varer'} · {d.comment}{canCorrect&&d.kind==='delivery'&&!d.reversed&&<button disabled={busy||!!pending} onClick={()=>{const reason=window.prompt('Begrund modposteringen. Lageret reduceres; en flyttet palle skal først tilbage til afleveringsplaceringen.');if(reason&&reason.trim().length>=3)void send({path:base+'/'+d.id+'/reverse',body:{idempotency_key:crypto.randomUUID(),comment:reason}});}}>Modpostér aflevering</button>}</p>)}<button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Forrige afleveringsside</button><button disabled={page*25>=(history.data?.total??0)} onClick={()=>setPage(p=>p+1)}>Næste afleveringsside</button></section>;
}
export function HandlingUnits({company,canMove,initialId=''}:{company:string;canMove:boolean;initialId?:string}){
 const[q,setQ]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState(initialId),[location,setLocation]=useState<string|null>(null),[comment,setComment]=useState(''),[pending,setPending]=useState<{path:string;body:object}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const sending=useRef(false),cache=useQueryClient(),base=`/companies/${company}/handling-units`;
 const list=useQuery({queryKey:['handling-units',company,q,page],queryFn:()=>accessApi<{items:{id:string;code:string;active:boolean;shipment_id?:string|null;location_id:string;current_location:{name:string};quantity:string;order_id:string;snapshot:{order_code:string;product:{name:string};owner:{name:string};unit:{symbol:string}}}[];total:number}>(base+'?'+new URLSearchParams({q,page:String(page)})),retry:false});
 const history=useQuery({queryKey:['handling-units',company,selected,'moves'],queryFn:()=>accessApi<{items:{id:string;created_at:string;comment:string;snapshot:{to_location:{name:string}}}[]}>(base+'/'+selected+'/moves'),enabled:!!selected,retry:false});
 async function send(command:{path:string;body:object}){if(sending.current)return;sending.current=true;setBusy(true);setPending(command);setError('');try{await accessApi(command.path,'POST',command.body);setPending(null);setComment('');await cache.invalidateQueries({queryKey:['handling-units',company]});await cache.invalidateQueries({queryKey:['inventory',company]});}catch(e){setError(e instanceof Error?e.message:'Pallen kunne ikke flyttes.');}finally{sending.current=false;setBusy(false);}}
 return <section className="access-card"><h2>Individuelle paller</h2><label>Søg palle, vare eller ordre<input value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/></label>{list.error&&<p role="alert">Paller kunne ikke hentes.</p>}{Array.isArray(list.data?.items)&&list.data.items.map(h=><article key={h.id}><QrLabel company={company} kind="pallet" id={h.id} label={h.code}/><p>{h.code} · {h.snapshot.product.name} · {h.quantity} {h.snapshot.unit.symbol} · {h.snapshot.owner.name} · Ordre {h.snapshot.order_code} · {h.active?'På lager':h.shipment_id?'Afsendt':'Modposteret'} · Seneste placering {h.current_location?.name??'Ukendt'}</p><button disabled={busy||!!pending} onClick={()=>setSelected(h.id)}>Vis pallehistorik / flyt</button></article>)}<button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Forrige palleside</button><button disabled={page*25>=(list.data?.total??0)} onClick={()=>setPage(p=>p+1)}>Næste palleside</button>
 {selected&&<><h3>Pallehistorik</h3>{history.error&&<p role="alert">Pallehistorik kunne ikke hentes.</p>}{history.data?.items?.map(m=><p key={m.id}>{new Date(m.created_at).toLocaleString('da-DK')} → {m.snapshot.to_location.name} · {m.comment}</p>)}{canMove&&<form onSubmit={e=>{e.preventDefault();if(busy||pending)return;if(window.confirm('Flyt hele pallens indhold til den valgte placering?'))void send({path:base+'/'+selected+'/moves',body:{idempotency_key:crypto.randomUUID(),to_location_id:location,comment}});}}><fieldset disabled={busy||!!pending}><LocationPicker company={company} label="Pallens nye placering" value={location} change={setLocation} storageOnly/><label>Flyttekommentar<textarea aria-label="Flyttekommentar" required minLength={3} maxLength={2000} value={comment} onChange={e=>setComment(e.target.value)}/></label></fieldset><button disabled={busy||!!pending||!location}>Flyt hele pallen</button></form>}</>}{error&&<p role="alert">{error}</p>}{pending&&<button disabled={busy} onClick={()=>void send(pending)}>Prøv samme palleflytning igen</button>}</section>;
}
