import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {accessApi} from './auth-client';
import {LocationPicker} from './Locations';
type Row={id:string;code:string;name:string;kind:string;active:boolean;notes:string;version:number;quantity:string;snapshot:{item:{code:string;name:string};owner:{name:string};location:{name:string};unit:{symbol:string}};posted_at:string;reason:string;reference:string;actor_id:string;lines:Row[]};
type List={items:Row[];total:number};
const msg=(e:unknown)=>e instanceof Error?e.message:'Handlingen kunne ikke gennemføres.';
function Picker({path,label,value,change}:{path:string;label:string;value:string;change:(s:string)=>void}){
 const[q,setQ]=useState('');const list=useQuery({queryKey:['inventory-picker',path,q],queryFn:()=>accessApi<List>(path+'?limit=100&q='+encodeURIComponent(q)),retry:false});
 return <label>{label}<input aria-label={'Søg '+label} type="search" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label={label} required value={value} onChange={e=>change(e.target.value)}><option value="">Vælg</option>{list.data?.items.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}{x.active?'':' (inaktiv)'}</option>)}</select>{list.error&&<span role="alert">{msg(list.error)}</span>}<small>Søg for at afgrænse de første 100 resultater.</small></label>;
}
export function Inventory({company,canAdjust,canMasterRead}:{company:string;canAdjust:boolean;canMasterRead:boolean}){
 const base=`/companies/${company}`,prefix=base+'/inventory',cache=useQueryClient();
 const[tab,setTab]=useState('balances'),[q,setQ]=useState(''),[page,setPage]=useState(1),[editing,setEditing]=useState<Row|null|undefined>(),[correction,setCorrection]=useState(false),[selected,setSelected]=useState(''),[status,setStatus]=useState('');
 const list=useQuery({queryKey:['inventory',company,tab,q,page],queryFn:()=>accessApi<List>(`${prefix}/${tab}?q=${encodeURIComponent(q)}&page=${page}`),retry:false});
 async function saved(){await cache.invalidateQueries({queryKey:['inventory']});await cache.invalidateQueries({queryKey:['inventory-picker']});setStatus('Registreringen er gemt.');}
 return <><p>Fysisk beholdning pr. vare, ejer og placering. Mængder ændres kun gennem begrundede lagerposteringer. Navne vises som ved seneste postering.</p><nav className="master-actions" aria-label="Lager"><button onClick={()=>{setTab('balances');setPage(1);setQ('');}}>Beholdning</button><button onClick={()=>{setTab('entries');setPage(1);setQ('');}}>Posteringer</button><button onClick={()=>{setTab('owners');setPage(1);setQ('');}}>Ejere</button></nav><div className="master-toolbar"><label>Søg<input type="search" maxLength={120} value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/></label>{canAdjust&&canMasterRead&&<button onClick={()=>setCorrection(true)}>Ny lagerkorrektion</button>}{canAdjust&&tab==='owners'&&<button onClick={()=>setEditing(null)}>Opret ejer</button>}</div>{canAdjust&&!canMasterRead&&<p>Stamdata-læseadgang kræves for at vælge varer og placeringer i korrektionsformularen.</p>}{status&&<p role="status">{status}</p>}{list.error&&<p role="alert">{msg(list.error)} <button onClick={()=>void list.refetch()}>Prøv igen</button></p>}{list.isPending&&<p>Henter lager…</p>}
 {correction&&<Correction company={company} close={()=>setCorrection(false)} saved={async()=>{setCorrection(false);await saved();}}/>}
 {editing!==undefined&&<OwnerForm key={editing?.id??'new'} canAdjust={canAdjust} company={company} row={editing} canMasterRead={canMasterRead} close={()=>setEditing(undefined)} saved={async()=>{setEditing(undefined);await saved();}}/>}
 {list.data&&<section className="access-card"><div className="table-scroll"><table><caption>{tab==='balances'?'Beholdning':tab==='entries'?'Posteringer':'Ejere'} · {list.data.total}</caption><thead><tr>{(tab==='balances'?['Vare','Ejer','Placering','Fysisk lager']:tab==='entries'?['Tid','Type','Begrundelse','Reference','Handling']:['Kode','Navn','Status','Handling']).map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{list.data.items.map((r,i)=><tr key={r.id??i}>{tab==='balances'?<><td>{r.snapshot.item.code} · {r.snapshot.item.name}</td><td>{r.snapshot.owner.name}</td><td>{r.snapshot.location.name}</td><td>{r.quantity} {r.snapshot.unit.symbol}</td></>:tab==='entries'?<><td>{new Date(r.posted_at).toLocaleString('da-DK')}</td><td>{r.kind==='correction'?'Korrektion':'Modpostering'}</td><td>{r.reason}</td><td>{r.reference}</td><td><button onClick={()=>setSelected(r.id)}>Vis postering</button></td></>:<><td>{r.code}</td><td>{r.name}</td><td>{r.active?'Aktiv':'Inaktiv'}</td><td><button onClick={()=>setEditing(r)}>{canAdjust?'Redigér og historik':'Vis historik'}</button></td></>}</tr>)}</tbody></table></div>{!list.data.items.length&&<p>Ingen registreringer fundet.</p>}<div className="master-actions"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Forrige</button><span>Side {page}</span><button disabled={page*25>=list.data.total} onClick={()=>setPage(p=>p+1)}>Næste</button></div></section>}
 {selected&&<Entry key={selected} prefix={prefix} id={selected} canAdjust={canAdjust} close={()=>setSelected('')} saved={saved}/>}
 </>;
}
function Correction({company,close,saved}:{company:string;close:()=>void;saved:()=>Promise<void>}){
 const base=`/companies/${company}`;const[kind,setKind]=useState('product'),[item,setItem]=useState(''),[owner,setOwner]=useState(''),[location,setLocation]=useState<string|null>(null),[quantity,setQuantity]=useState(''),[reason,setReason]=useState(''),[reference,setReference]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const[pending,setPending]=useState<object|null>(null);const[key]=useState(()=>crypto.randomUUID());
 async function submit(){if(busy)return;const decimal=quantity.trim().replace(',','.');if(!pending&&(!/^-?(0|[1-9][0-9]{0,11})(\.[0-9]{1,8})?$/.test(decimal)||/^-?0(\.0+)?$/.test(decimal))){setError('Angiv en mængde forskellig fra nul med højst 12 heltal og 8 decimaler.');return;}const body=pending??{idempotency_key:key,reason,reference,lines:[{item_id:item,owner_id:owner,location_id:location,quantity:decimal} ]};if(!pending&&!window.confirm(`Bogfør ændringen ${quantity} i varens lagerenhed? Fysisk lager ændres, og posteringen gemmes permanent med din begrundelse.`))return;setPending(body);setBusy(true);setError('');try{await accessApi(base+'/inventory/corrections','POST',body);await saved();}catch(e){setError(msg(e)+' Ved usikker forbindelse: prøv igen med samme registrering. Felterne er låst for at undgå dobbeltregistrering.');}finally{setBusy(false);}}
 return <section className="access-card"><h2>Begrundet lagerkorrektion</h2><p>Positiv mængde lægger til; negativ mængde trækker fra. Brug varens faste lagerenhed. Der foretages ingen enhedskonvertering.</p><form onSubmit={e=>{e.preventDefault();if(location)void submit();else setError('Vælg placering.');}}><fieldset disabled={!!pending||busy}><label>Varetype<select value={kind} onChange={e=>{setKind(e.target.value);setItem('');}}><option value="product">Færdigvare</option><option value="material">Materiale</option><option value="packaging">Emballage</option></select></label><Picker path={base+'/items/'+kind} label="Vare" value={item} change={setItem}/><Picker path={base+'/inventory/owners'} label="Ejer" value={owner} change={setOwner}/><LocationPicker company={company} label="Placering" value={location} change={setLocation} includeInactive/><label>Mængdeændring<input required inputMode="decimal" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Begrundelse<input required minLength={3} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><label>Reference<input maxLength={160} value={reference} onChange={e=>setReference(e.target.value)}/></label></fieldset>{error&&<p role="alert">{error}</p>}<button disabled={busy}>{pending?'Prøv samme registrering igen':'Bekræft lagerkorrektion'}</button><button type="button" disabled={busy} onClick={()=>{if(!pending||window.confirm('Kontrollér posteringerne før en ny registrering. Den tidligere kan allerede være gemt. Luk?'))close();}}>Luk</button></form></section>;
}
function OwnerForm({company,row,canMasterRead,canAdjust,close,saved}:{canAdjust:boolean;company:string;row:Row|null;canMasterRead:boolean;close:()=>void;saved:()=>Promise<void>}){
 const[code,setCode]=useState(row?.code??''),[name,setName]=useState(row?.name??''),[kind,setKind]=useState(row?.kind??'company'),[party,setParty]=useState(''),[active,setActive]=useState(row?.active??true),[notes,setNotes]=useState(row?.notes??''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const history=useQuery({queryKey:['inventory',company,'owner-history',row?.id],queryFn:()=>accessApi<{id:string;occurred_at:string;before_value:unknown;after_value:unknown}[]>(`/companies/${company}/inventory/owners/${row?.id}/history`),enabled:!!row,retry:false});
 return <section className="access-card"><h2>{row?'Ejer og historik':'Opret ejer'}</h2><form onSubmit={e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');const data=row?{version:row.version,data:{code,name,active,notes}}:{code,name,kind,notes,customer_id:kind==='customer'?party:null,supplier_id:kind==='supplier'?party:null};void accessApi(`/companies/${company}/inventory/owners`+(row?'/'+row.id:''),row?'PATCH':'POST',data).then(saved).catch(e=>setError(msg(e))).finally(()=>setBusy(false));}}><fieldset disabled={!canAdjust||busy}><label>Kode<input required maxLength={60} value={code} onChange={e=>setCode(e.target.value)}/></label><label>Navn<input required maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label>{!row&&<><label>Ejertype<select value={kind} onChange={e=>{setKind(e.target.value);setParty('');}}><option value="company">Egen virksomhed</option><option value="other">Anden ekstern ejer</option>{canMasterRead&&<><option value="customer">Kunde</option><option value="supplier">Leverandør</option></>}</select></label>{['customer','supplier'].includes(kind)&&<Picker path={`/companies/${company}/masterdata/${kind==='customer'?'customers':'suppliers'}`} label="Virksomhed" value={party} change={setParty}/>}</>}{row&&<label><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Aktiv</label>}<label>Noter<textarea maxLength={4000} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}</fieldset>{canAdjust&&<button disabled={busy}>Gem ejer</button>}<button type="button" onClick={close}>Luk</button></form>{history.error&&<p role="alert">{msg(history.error)}</p>}{history.data?.map(h=><details key={h.id}><summary>{new Date(h.occurred_at).toLocaleString('da-DK')}</summary><pre>{JSON.stringify({før:h.before_value,efter:h.after_value},null,2)}</pre></details>)}</section>;
}
function Entry({prefix,id,canAdjust,close,saved}:{prefix:string;id:string;canAdjust:boolean;close:()=>void;saved:()=>Promise<void>}){
 const detail=useQuery({queryKey:['inventory',prefix,id],queryFn:()=>accessApi<Row>(prefix+'/entries/'+id),retry:false});const[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState<object|null>(null);const[key]=useState(()=>crypto.randomUUID());
 return <section className="access-card"><button onClick={close}>Luk postering</button>{detail.error&&<p role="alert">{msg(detail.error)}</p>}{detail.data&&<><h2>{detail.data.reason}</h2><p>Bruger: {detail.data.actor_id} · {new Date(detail.data.posted_at).toLocaleString('da-DK')}</p>{detail.data.lines.map(l=><p key={l.id}>{l.snapshot.item.code} · {l.snapshot.item.name}: {l.quantity} {l.snapshot.unit.symbol} · {l.snapshot.owner.name} · {l.snapshot.location.name}</p>)}{canAdjust&&detail.data.kind==='correction'&&<form onSubmit={e=>{e.preventDefault();if(busy||!window.confirm('Modpostér hele posteringen? Alle oprindelige mængder bogføres med modsat fortegn. Negativt lager blokeres.'))return;const body=pending??{idempotency_key:key,reason};setPending(body);setBusy(true);void accessApi(prefix+'/entries/'+id+'/reverse','POST',body).then(async()=>{await saved();close();}).catch(e=>setError(msg(e))).finally(()=>setBusy(false));}}><label>Begrundelse for modpostering<input required minLength={3} maxLength={1000} disabled={!!pending} value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert">{error} Prøv samme modpostering igen ved usikker forbindelse.</p>}<button disabled={busy}>{pending?'Prøv samme modpostering igen':'Modpostér hele posteringen'}</button></form>}</>}</section>;
}
