import { FormEvent, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { accessApi } from './auth-client';
import { LocationPicker, LocationLabel } from './Locations';
import { MasterForm } from './Masterdata';

export const itemPages: Record<string,string> = { Varer:'product', Materialer:'material', Emballage:'packaging' };
type Item = { id:string; code:string; name:string; kind:string; active:boolean; version:number; [key:string]:unknown };
type List = { items:Item[]; total:number; page:number; limit:number };
const references: Record<string,[string,string]> = {
 unit_id:['units','Lagerenhed'], customer_id:['customers','Kunde'], supplier_id:['suppliers','Leverandør'],
 product_group_id:['product_groups','Produktgruppe'], material_type_id:['material_types','Materialetype'], standard_machine_id:['machines','Standardmaskine'],
};
const amounts: Record<string,string> = {minimum_stock:'Minimumslager',desired_stock:'Ønsket lagerbeholdning',maximum_stock:'Maksimumslager',reorder_level:'Genbestillingsniveau',standard_order_quantity:'Standardbestillingsmængde',quantity_per_pallet:'Standardmængde pr. palle'};
const labels: Record<string,string> = {code:'Nummer',name:'Navn',active:'Aktiv',description:'Beskrivelse',color:'Farve',supplier_code:'Leverandørens varenummer',lead_time_days:'Leveringstid (dage)',cavities:'Antal kaviteter',cycle_time_seconds:'Cyklustid (sekunder)',production_notes:'Produktionsnoter',notes:'Noter',standard_location_id:'Standardlagerplacering',...Object.fromEntries(Object.entries(references).map(([k,v])=>[k,v[1]])),...amounts};
const message = (e:unknown) => e instanceof Error?e.message:'Handlingen kunne ikke gennemføres.';
const fieldsFor = (kind:string) => ['code','name','description','color','unit_id','standard_location_id','product_group_id',...(kind==='product'?['customer_id','standard_machine_id','cavities','cycle_time_seconds','production_notes']:['supplier_id','supplier_code','material_type_id','lead_time_days']),...Object.keys(amounts),'notes','active'];
const numericFields = ['lead_time_days','cavities'];
function display(v:unknown) { return typeof v==='boolean'?(v?'Ja':'Nej'):v===null||v===undefined||v===''?'—':String(v); }
export function Items({company,kind,title,canManage}:{company:string;kind:string;title:string;canManage:boolean}) {
 const cache=useQueryClient(), prefix=`/companies/${company}/items/${kind}`;
 const [q,setQ]=useState(''),[active,setActive]=useState('all'),[sort,setSort]=useState('code'),[direction,setDirection]=useState('asc'),[page,setPage]=useState(1);
 const [filters,setFilters]=useState<Record<string,string>>({}),[edit,setEdit]=useState<Item|null|undefined>(),[detail,setDetail]=useState<string>(),[status,setStatus]=useState('');
 const query = new URLSearchParams({q,active,sort,direction,page:String(page),...Object.fromEntries(Object.entries(filters).filter(([,v])=>v))}).toString();
 const list=useQuery({queryKey:['items',company,kind,query],queryFn:()=>accessApi<List>(prefix+'?'+query),retry:false});
 return <>
 <p>Opret med nummer og navn. Udfyld resten, når oplysningerne er klar.</p>
 <div className="master-toolbar"><label>Søg efter nummer eller navn<input type="search" maxLength={120} value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/></label><label>Status<select value={active} onChange={e=>{setActive(e.target.value);setPage(1);}}><option value="all">Alle</option><option value="true">Aktive</option><option value="false">Inaktive</option></select></label><label>Sortér efter<select value={sort} onChange={e=>{setSort(e.target.value);setPage(1);}}><option value="code">Nummer</option><option value="name">Navn</option></select></label><label>Rækkefølge<select value={direction} onChange={e=>{setDirection(e.target.value);setPage(1);}}><option value="asc">Stigende</option><option value="desc">Faldende</option></select></label>{canManage&&<button className="primary" onClick={()=>{setEdit(null);setDetail(undefined);setStatus('');}}>Opret ny</button>}</div>
 <details className="access-card"><summary>Flere filtre</summary><div className="master-fields">{['product_group_id',...(kind==='product'?['customer_id']:['supplier_id','material_type_id'])].map(field=><Reference key={field} company={company} field={field} value={filters[field]??null} change={v=>{setFilters(f=>({...f,[field]:v??''}));setPage(1);}}/>)}</div></details>
 {status&&<p role="status">{status}</p>}{list.isPending&&<p role="status">Henter {title.toLowerCase()}…</p>}{list.error&&<div role="alert">{message(list.error)} <button onClick={()=>void list.refetch()}>Prøv igen</button></div>}
 {edit!==undefined&&canManage&&<ItemForm key={edit?.id??'new'} company={company} kind={kind} row={edit} close={()=>setEdit(undefined)} saved={async()=>{setEdit(undefined);setStatus('Ændringen er gemt.');await cache.invalidateQueries({queryKey:['items',company]});}}/>}
 {list.data&&<section className="access-card"><div className="table-scroll"><table><caption>{title} · {list.data.total} i alt</caption><thead><tr><th>Nummer</th><th>Navn</th><th>Status</th><th>Handlinger</th></tr></thead><tbody>{list.data.items.map(row=><tr key={row.id}><td>{row.code}</td><td>{row.name}</td><td><span className={row.active?'master-active':'master-inactive'}>{row.active?'Aktiv':'Inaktiv'}</span>{!row.unit_id&&<small className="item-warning">Lagerenhed mangler</small>}</td><td><div className="master-actions"><button onClick={()=>{setDetail(row.id);setEdit(undefined);}}>Detaljer og historik</button>{canManage&&<button onClick={()=>{setEdit(row);setDetail(undefined);}}>Redigér</button>}</div></td></tr>)}</tbody></table></div>{!list.data.items.length&&<p>Ingen resultater. {canManage?'Opret en registrering eller tilpas filtrene.':'Tilpas eventuelt filtrene.'}</p>}<div className="master-actions"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Forrige</button><span>Side {page}</span><button disabled={page*25>=list.data.total} onClick={()=>setPage(p=>p+1)}>Næste</button></div></section>}
 {detail&&<ItemDetails key={detail} company={company} prefix={prefix} id={detail} canManage={canManage} close={()=>setDetail(undefined)}/>}
 </>;
}
function Reference({company,field,value,change,disabled=false,create}:{company:string;field:string;value:unknown;change:(id:string|null)=>void;disabled?:boolean;create?:()=>void}) {
 const [q,setQ]=useState(''); const [catalog,label]=references[field]!;
 const result=useQuery({queryKey:['masterdata',company,catalog,'item-picker',q],queryFn:()=>accessApi<List>(`/companies/${company}/masterdata/${catalog}?${new URLSearchParams({q,active:'true',limit:'100'})}`),retry:false});
 return <div className="item-reference"><label>Søg {label.toLowerCase()}<input type="search" disabled={disabled} maxLength={120} value={q} onChange={e=>setQ(e.target.value)}/></label><label>{label}<select aria-label={label} disabled={disabled} value={String(value??'')} onChange={e=>change(e.target.value||null)}><option value="">Ikke angivet</option>{!!value&&!result.data?.items.some(r=>r.id===value)&&<option value={String(value)}>Nuværende valg</option>}{result.data?.items.map(r=><option key={r.id} value={r.id}>{r.code} · {r.name}</option>)}</select></label>{create&&!disabled&&<button type="button" onClick={create}>Opret {label.toLowerCase()}</button>}{result.error&&<p role="alert">Valgmuligheder kunne ikke hentes. <button type="button" onClick={()=>void result.refetch()}>Prøv igen</button></p>}{(result.data?.total??0)>100&&<small>Præcisér søgningen for at finde flere.</small>}</div>;
}
export function ItemForm({company,kind,row,close,saved}:{company:string;kind:string;row:Item|null;close:()=>void;saved:(item:Item)=>Promise<void>}) {
 const fields=fieldsFor(kind), cache=useQueryClient();
 const [draft,setDraft]=useState<Record<string,unknown>>(()=>Object.fromEntries(fields.map(field=>[field,row?.[field]??(field==='active'?true:field==='standard_location_id'||references[field]||amounts[field]||numericFields.includes(field)||field==='cycle_time_seconds'?null:'')])));
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[creating,setCreating]=useState<string>();
 const change=(field:string,value:unknown)=>setDraft(d=>({...d,[field]:value}));
 const decimalChange=(field:string,value:string)=>change(field,value===''?null:value.replace(',','.'));
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;if(row?.active&&!draft.active&&!window.confirm('Deaktivér registreringen? Historikken bevares.'))return;setBusy(true);setError('');try{const result=await accessApi<Item>(`/companies/${company}/items/${kind}${row?'/'+row.id:''}`,row?'PATCH':'POST',row?{version:row.version,data:draft}:draft);await saved(result);}catch(e){setError(message(e));}finally{setBusy(false);}}
 const reference=(field:string)=><Reference key={field} company={company} field={field} value={draft[field]} disabled={busy||(field==='unit_id'&&!!row?.unit_id)} change={v=>change(field,v)} create={()=>setCreating(field)}/>;
 return <section className="access-card"><h2>{row?'Redigér '+row.name:'Ny registrering'}</h2><form onSubmit={submit}><fieldset disabled={busy} className="item-section"><legend>Grunddata</legend><div className="master-fields">{['code','name','color'].map(field=><label key={field}>{labels[field]}<input maxLength={field==='code'?60:field==='color'?120:160} required={field!=='color'} value={String(draft[field])} onChange={e=>change(field,e.target.value)}/></label>)}<label className="master-wide">Beskrivelse<textarea maxLength={4000} value={String(draft.description)} onChange={e=>change('description',e.target.value)}/></label>{reference('product_group_id')}{reference(kind==='product'?'customer_id':'supplier_id')}{kind!=='product'&&<>{reference('material_type_id')}<label>Leverandørens varenummer<input maxLength={100} value={String(draft.supplier_code)} onChange={e=>change('supplier_code',e.target.value)}/></label><label>Leveringstid (dage)<input type="number" min={0} max={3650} step={1} value={String(draft.lead_time_days??'')} onChange={e=>change('lead_time_days',e.target.value===''?null:Number(e.target.value))}/></label></>}</div></fieldset>
 <fieldset disabled={busy} className="item-section"><legend>Lagerstandarder</legend><p>Mængderne er planlægningsværdier i lagerenheden, ikke aktuel beholdning.</p><div className="master-fields">{reference('unit_id')}<LocationPicker company={company} label="Standardlagerplacering" value={draft.standard_location_id as string|null} change={id=>change('standard_location_id',id)} storageOnly create/><p>Lagerenheden kan udfyldes senere. Efter valg er den låst, så mængder ikke får en anden betydning.</p>{Object.entries(amounts).map(([field,label])=><label key={field}>{label}<input inputMode="decimal" maxLength={21} disabled={!draft.unit_id} pattern="[0-9]+([.,][0-9]{1,8})?" value={String(draft[field]??'')} onChange={e=>decimalChange(field,e.target.value)}/></label>)}</div>{!draft.unit_id&&<p className="item-warning">Vælg en lagerenhed, før du angiver mængder.</p>}<small>Standardmængde pr. palle er vejledende. Behovsberegningen bruger kapaciteten fra den valgte pakkeopbygning.</small></fieldset>
 {kind==='product'&&<fieldset disabled={busy} className="item-section"><legend>Produktionsstandarder</legend><div className="master-fields">{reference('standard_machine_id')}<label>Antal kaviteter<input type="number" min={1} max={100000} step={1} value={String(draft.cavities??'')} onChange={e=>change('cavities',e.target.value===''?null:Number(e.target.value))}/></label><label>Cyklustid (sekunder)<input inputMode="decimal" maxLength={21} pattern="[0-9]+([.,][0-9]{1,8})?" value={String(draft.cycle_time_seconds??'')} onChange={e=>decimalChange('cycle_time_seconds',e.target.value)}/></label><label className="master-wide">Produktionsnoter<textarea maxLength={4000} value={String(draft.production_notes)} onChange={e=>change('production_notes',e.target.value)}/></label></div></fieldset>}
 <fieldset disabled={busy} className="master-fields"><label className="master-wide">Noter<textarea maxLength={4000} value={String(draft.notes)} onChange={e=>change('notes',e.target.value)}/></label><label className="check"><input type="checkbox" checked={!!draft.active} onChange={e=>change('active',e.target.checked)}/>Aktiv</label></fieldset>{error&&<p role="alert">{error}</p>}<div className="master-actions"><button disabled={busy||!!creating} className="primary">{busy?'Gemmer…':'Gem'}</button><button type="button" disabled={busy} onClick={close}>Annullér</button></div></form>
 {creating&&<MasterForm row={null} company={company} kind={references[creating]![0]} close={()=>setCreating(undefined)} saved={async result=>{await cache.invalidateQueries({queryKey:['masterdata',company]});change(creating,result.id);setCreating(undefined);}}/>}
 </section>;
}
function ItemDetails({company,prefix,id,canManage,close}:{company:string;prefix:string;id:string;canManage:boolean;close:()=>void}) {
 const detail=useQuery({queryKey:['items',company,id,'detail'],queryFn:()=>accessApi<Item>(prefix+'/'+id),retry:false});
 const history=useQuery({queryKey:['items',company,id,'history'],queryFn:()=>accessApi<{id:string;actor_id:string;occurred_at:string;before_value:Item|null;after_value:Item}[]>(prefix+'/'+id+'/history'),retry:false});
 return <section className="access-card"><button onClick={close}>Luk detaljer</button>{detail.isPending&&<p role="status">Henter detaljer…</p>}{detail.error&&<p role="alert">{message(detail.error)}</p>}{detail.data&&<><h2>{detail.data.name}</h2><ItemPhoto company={company} prefix={prefix} item={detail.data} canManage={canManage}/><dl className="master-details">{fieldsFor(detail.data.kind).map(field=><div key={field}><dt>{labels[field]}</dt><dd>{field==='standard_location_id'&&detail.data![field]?<LocationLabel company={company} id={String(detail.data![field])} storageOnly/>:references[field]&&detail.data![field]?<ReferenceName company={company} field={field} id={String(detail.data![field])}/>:display(detail.data![field])}</dd></div>)}</dl></>}<h3>Seneste 100 ændringer</h3>{history.error&&<p role="alert">{message(history.error)}</p>}{history.isPending&&<p role="status">Henter historik…</p>}{history.data?.map(h=><details key={h.id}><summary>{new Date(h.occurred_at).toLocaleString('da-DK')} · {h.before_value?'Ændret':'Oprettet'}</summary><p>Bruger-ID: {h.actor_id}</p><ul>{Object.keys(labels).filter(k=>k in h.after_value&&(!h.before_value||h.before_value[k]!==h.after_value[k])).map(k=><li key={k}>{labels[k]}: {h.before_value?display(h.before_value[k])+' → ':''}{display(h.after_value[k])}</li>)}</ul></details>)}</section>;
}

function ReferenceName({company,field,id}:{company:string;field:string;id:string}) {
 const value=useQuery({queryKey:['masterdata',company,references[field]![0],id],queryFn:()=>accessApi<Item>(`/companies/${company}/masterdata/${references[field]![0]}/${id}`),retry:false});
 return <>{value.data?`${value.data.code} · ${value.data.name}${value.data.active?'':' (inaktiv)'}`:value.isPending?'Henter…':'Referencen kunne ikke hentes'}</>;
}

function ItemPhoto({company,prefix,item,canManage}:{company:string;prefix:string;item:Item;canManage:boolean}) {
 const cache=useQueryClient();const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const photo=useQuery({queryKey:['items',company,item.id,'photo'],queryFn:()=>accessApi<{enabled:boolean;photo:{mime:string;base64:string}|null}>(`${prefix}/${item.id}/photo`),retry:false});
 async function upload(file:File) {
  if(busy)return;
  if(file.size>1024*1024 || !['image/png','image/jpeg'].includes(file.type)){setError('Vælg et PNG- eller JPEG-foto på højst 1 MB og 4096 × 4096 pixels.');return;}
  setBusy(true);setError('');
  try {
   const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]!);reader.onerror=()=>reject(new Error('Fotoet kunne ikke læses.'));reader.readAsDataURL(file);});
   await accessApi(`${prefix}/${item.id}/photo`,'POST',{version:item.version,mime:file.type,base64});
   await cache.invalidateQueries({queryKey:['items',company]});
  }catch(e){setError(message(e));}finally{setBusy(false);}
 }
 return <div className="item-photo">{photo.data?.photo&&<img alt={`Foto af ${item.name}`} src={`data:${photo.data.photo.mime};base64,${photo.data.photo.base64}`} loading="lazy"/>}{photo.data?.enabled&&canManage&&<label>Tilføj eller erstat foto<input type="file" accept="image/png,image/jpeg" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/><small>PNG eller JPEG, højst 1 MB og 4096 × 4096 pixels.</small></label>}{photo.data&&!photo.data.enabled&&<p>Foto-upload er endnu ikke aktiveret.</p>}{busy&&<p role="status">Gemmer foto…</p>}{(error||photo.error)&&<p role="alert">{error||message(photo.error)}</p>}</div>;
}
