import { FormEvent, ReactNode, useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { accessApi } from './auth-client';
type Crumb={id:string;code:string;name:string;active:boolean};
export type Location={id:string;code:string;name:string;parent_id:string|null;location_type:string;active:boolean;is_storage:boolean;notes:string;version:number;child_count?:number;path?:Crumb[]};
type List={items:Location[];total:number;page:number;limit:number};
const message=(e:unknown)=>e instanceof Error?e.message:'Handlingen kunne ikke gennemføres.';
export function Locations({company,canManage}:{company:string;canManage:boolean}){
 const cache=useQueryClient(),prefix=`/companies/${company}/locations`;
 const[parent,setParent]=useState('root'),[q,setQ]=useState(''),[active,setActive]=useState('all'),[storage,setStorage]=useState('all'),[sort,setSort]=useState('code'),[page,setPage]=useState(1),[editing,setEditing]=useState<Location|null|undefined>(),[detail,setDetail]=useState(''),[status,setStatus]=useState('');
 const current=useQuery({queryKey:['locations',company,'detail',parent],queryFn:()=>accessApi<Location>(prefix+'/'+parent),enabled:parent!=='root'&&parent!=='all',retry:false});
 const params=new URLSearchParams({parent_id:q?'all':parent,q,active,storage,sort,page:String(page)}).toString();
 const list=useQuery({queryKey:['locations',company,'list',params],queryFn:()=>accessApi<List>(prefix+'?'+params),retry:false});
 function navigate(id:string){setParent(id);setQ('');setPage(1);setEditing(undefined);setDetail('');setStatus('');}
 return <><p>Byg virksomhedens lagerstruktur med de niveauer og betegnelser, I bruger.</p><nav aria-label="Placeringssti" className="master-actions"><button onClick={()=>navigate('root')}>Øverste niveau</button>{current.data?.path?.map(c=><button key={c.id} aria-current={parent===c.id?'location':undefined} onClick={()=>navigate(c.id)}>{c.code} · {c.name}</button>)}<button onClick={()=>navigate('all')}>Vis alle placeringer</button></nav>{current.error&&<p role="alert">{message(current.error)}</p>}
 <div className="master-toolbar"><label>Søg alle placeringer<input type="search" maxLength={120} value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/></label><label>Status<select aria-label="Status" value={active} onChange={e=>{setActive(e.target.value);setPage(1);}}><option value="all">Alle</option><option value="true">Aktive</option><option value="false">Inaktive</option></select></label><label>Lagerføring<select aria-label="Lagerføring" value={storage} onChange={e=>{setStorage(e.target.value);setPage(1);}}><option value="all">Alle</option><option value="true">Tilladt</option><option value="false">Struktur alene</option></select></label><label>Sortér efter<select aria-label="Sortér efter" value={sort} onChange={e=>{setSort(e.target.value);setPage(1);}}><option value="code">Kode</option><option value="name">Navn</option></select></label>{canManage&&<button className="primary" onClick={()=>{setEditing(null);setDetail('');setStatus('');}}>Opret placering</button>}</div>
 {status&&<p role="status">{status}</p>}{list.isPending&&<p role="status">Henter placeringer…</p>}{list.error&&<div role="alert">{message(list.error)} <button onClick={()=>void list.refetch()}>Prøv igen</button></div>}
 {editing!==undefined&&canManage&&<LocationForm key={editing?.id??'new'} company={company} row={editing} parent={['root','all'].includes(parent)?null:parent} close={()=>setEditing(undefined)} saved={async()=>{setEditing(undefined);setStatus('Placeringen er gemt.');await cache.invalidateQueries({queryKey:['locations',company]});}}/>}
 {list.data&&<section className="access-card"><div className="table-scroll"><table><caption>Placeringer · {list.data.total} på denne liste</caption><thead><tr><th>Kode</th><th>Navn</th><th>Betegnelse</th><th>Status</th><th>Handlinger</th></tr></thead><tbody>{list.data.items.map(row=><tr key={row.id}><td>{row.code}</td><td>{row.name}</td><td>{row.location_type||'—'}</td><td><span className={row.active?'master-active':'master-inactive'}>{row.active?'Aktiv':'Inaktiv'}</span>{!row.is_storage&&<small>Struktur alene</small>}</td><td><div className="master-actions"><button onClick={()=>navigate(row.id)}>Underplaceringer ({row.child_count??0})</button><button onClick={()=>{setDetail(row.id);setEditing(undefined);}}>Detaljer og historik</button>{canManage&&<button onClick={()=>{setEditing(row);setDetail('');}}>Redigér</button>}</div></td></tr>)}</tbody></table></div>{!list.data.items.length&&<p>Ingen placeringer fundet på dette niveau eller med disse filtre.</p>}<div className="master-actions"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Forrige</button><span>Side {page}</span><button disabled={page*25>=list.data.total} onClick={()=>setPage(p=>p+1)}>Næste</button></div></section>}
 {detail&&<LocationDetails key={detail} company={company} id={detail} close={()=>setDetail('')}/>}</>;
}
export function LocationPicker({company,label,value,change,storageOnly=false,exclude,create=false,includeInactive=false}:{company:string;label:string;value:string|null;change:(v:string|null)=>void;storageOnly?:boolean;exclude?:string;create?:boolean;includeInactive?:boolean}){
 const[q,setQ]=useState(''),[creating,setCreating]=useState(false),cache=useQueryClient();
 const params=new URLSearchParams({q,active:includeInactive?'all':'true',storage:storageOnly?'true':'all',limit:'100',...(exclude?{exclude_subtree:exclude}:{})}).toString();
 const list=useQuery({queryKey:['locations',company,'picker',params],queryFn:()=>accessApi<List>(`/companies/${company}/locations?${params}`),retry:false});
 return <div className="item-reference"><label>Søg {label.toLowerCase()}<input type="search" maxLength={120} value={q} onChange={e=>setQ(e.target.value)}/></label><label>{label}<select aria-label={label} value={value??''} onChange={e=>change(e.target.value||null)}><option value="">Ikke angivet / øverste niveau</option>{value&&!list.data?.items.some(x=>x.id===value)&&<option value={value}>Nuværende placering</option>}{list.data?.items.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}{x.active?'':' (inaktiv)'}</option>)}</select></label>{value&&<LocationLabel company={company} id={value} storageOnly={storageOnly}/>} {(list.data?.total??0)>100&&<small>Præcisér søgningen for at finde flere placeringer.</small>}{list.error&&<p role="alert">Placeringer kunne ikke hentes. <button type="button" onClick={()=>void list.refetch()}>Prøv igen</button></p>}{create&&<button type="button" onClick={()=>setCreating(true)}>Opret {label.toLowerCase()}</button>}{creating&&<LocationDialog close={()=>setCreating(false)}><LocationForm company={company} row={null} parent={null} close={()=>setCreating(false)} saved={async row=>{change(row.id);setCreating(false);await cache.invalidateQueries({queryKey:['locations',company]});}}/></LocationDialog>}</div>;
}
export function LocationLabel({company,id,storageOnly=false}:{company:string;id:string;storageOnly?:boolean}){
 const detail=useQuery({queryKey:['locations',company,'detail',id],queryFn:()=>accessApi<Location>(`/companies/${company}/locations/${id}`),retry:false});
 return <span>{detail.isPending?'Henter sti…':detail.error?'Placeringen kunne ikke hentes':detail.data?.path?.map(x=>x.code+' · '+x.name).join(' / ')}{detail.data&&(!detail.data.active||storageOnly&&!detail.data.is_storage)&&<strong className="item-warning">Placeringen er inaktiv eller kan ikke bruges til lagerføring. Vælg en anden før anvendelse.</strong>}</span>;
}
export function LocationForm({company,row,parent,close,saved}:{company:string;row:Location|null;parent:string|null;close:()=>void;saved:(row:Location)=>Promise<void>}){
 const[draft,setDraft]=useState(()=>({code:row?.code??'',name:row?.name??'',parent_id:row?row.parent_id:parent,location_type:row?.location_type??'',active:row?.active??true,is_storage:row?.is_storage??true,notes:row?.notes??''})),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;if(row&&((row.active&&!draft.active)||row.parent_id!==draft.parent_id)&&!window.confirm('Gem ændringen? Deaktivering påvirker brugen af placeringen. En ny overordnet placering ændrer også stien for alle underplaceringer.'))return;setBusy(true);setError('');try{const value=await accessApi<Location>(`/companies/${company}/locations${row?'/'+row.id:''}`,row?'PATCH':'POST',row?{version:row.version,data:draft}:draft);await saved(value);}catch(e){setError(message(e)+' Kontrollér kode, overordnet placering og aktive underplaceringer. Ved samtidig redigering: luk formularen og hent listen igen.');}finally{setBusy(false);}}
 return <section className="access-card"><h2>{row?'Redigér placering':'Ny placering'}</h2><form onSubmit={submit}><fieldset className="master-fields" disabled={busy}><label>Placeringskode<input required maxLength={60} value={draft.code} onChange={e=>setDraft(d=>({...d,code:e.target.value}))}/></label><label>Placeringsnavn<input required maxLength={160} value={draft.name} onChange={e=>setDraft(d=>({...d,name:e.target.value}))}/></label><label>Betegnelse<input maxLength={80} value={draft.location_type} onChange={e=>setDraft(d=>({...d,location_type:e.target.value}))}/><small>Valgfri betegnelse for niveauet.</small></label><LocationPicker company={company} label="Overordnet placering" value={draft.parent_id} change={id=>setDraft(d=>({...d,parent_id:id}))} exclude={row?.id} includeInactive={!draft.active}/><label className="check"><input type="checkbox" checked={draft.active} onChange={e=>setDraft(d=>({...d,active:e.target.checked}))}/>Aktiv placering</label><label className="check"><input type="checkbox" checked={draft.is_storage} onChange={e=>setDraft(d=>({...d,is_storage:e.target.checked}))}/>Lagerføring tilladt</label><label className="master-wide">Noter<textarea maxLength={4000} value={draft.notes} onChange={e=>setDraft(d=>({...d,notes:e.target.value}))}/></label></fieldset><p>Aktive underplaceringer skal deaktiveres eller flyttes, før en overordnet placering kan deaktiveres.</p>{error&&<p role="alert">{error}</p>}<div className="master-actions"><button className="primary" disabled={busy}>Gem placering</button><button type="button" disabled={busy} onClick={close}>Annullér</button></div></form></section>;
}
function LocationDetails({company,id,close}:{company:string;id:string;close:()=>void}){
 const detail=useQuery({queryKey:['locations',company,'detail',id],queryFn:()=>accessApi<Location>(`/companies/${company}/locations/${id}`),retry:false});
 const audit=useQuery({queryKey:['locations',company,'history',id],queryFn:()=>accessApi<{id:string;actor_id:string;occurred_at:string;before_value:Location|null;after_value:Location}[]>(`/companies/${company}/locations/${id}/history`),retry:false});
 const labels:Record<string,string>={code:'Kode',name:'Navn',parent_id:'Overordnet ID',location_type:'Betegnelse',active:'Aktiv',is_storage:'Lagerføring tilladt',notes:'Noter'};
 const value=(v:unknown)=>v===null||v===''?'—':typeof v==='boolean'?(v?'Ja':'Nej'):String(v);
 return <section className="access-card"><button onClick={close}>Luk detaljer</button>{detail.error&&<p role="alert">{message(detail.error)}</p>}{detail.data&&<><h2>{detail.data.name}</h2><LocationLabel company={company} id={id}/><p>{detail.data.notes}</p></>}<h3>Seneste 100 ændringer</h3>{audit.error&&<p role="alert">{message(audit.error)}</p>}{audit.data?.map(a=><details key={a.id}><summary>{new Date(a.occurred_at).toLocaleString('da-DK')} · {a.before_value?'Ændret':'Oprettet'}</summary><p>Bruger-ID: {a.actor_id}</p><ul>{Object.entries(labels).filter(([k])=>!a.before_value||a.before_value[k as keyof Location]!==a.after_value[k as keyof Location]).map(([k,l])=><li key={k}>{l}: {a.before_value?value(a.before_value[k as keyof Location])+' → ':''}{value(a.after_value[k as keyof Location])}</li>)}</ul></details>)}</section>;
}
function LocationDialog({close,children}:{close:()=>void;children:ReactNode}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);
 return createPortal(<dialog ref={ref} className="recipe-create-dialog" aria-label="Opret placering" onCancel={close} onSubmit={e=>e.stopPropagation()}>{children}</dialog>,document.body);
}
