import { FormEvent, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { accessApi } from './auth-client';
export const masterdataPages:Record<string,string>={Kunder:'customers',Leverandører:'suppliers',Maskiner:'machines',Produktgrupper:'product_groups',Enheder:'units',Maskintyper:'machine_types',Materialetyper:'material_types',Palletyper:'pallet_types'};
type Row={id:string;code:string;name:string;active:boolean;notes:string;version:number;[key:string]:unknown};
type List={items:Row[];total:number;page:number;limit:number};
type Field={key:string;label:string;max:number;type?:string};
const contacts:Field[]=[{key:'address',label:'Adresse',max:1000},{key:'contact_name',label:'Kontaktperson',max:120},{key:'phone',label:'Telefon',max:60,type:'tel'},{key:'email',label:'E-mail',max:254,type:'email'}];
const dimensions:Record<string,string>={count:'Antal',mass:'Masse',length:'Længde',volume:'Volumen',package:'Pakkeenhed'};
const labels:Record<string,string>={code:'Nummer / kode',name:'Navn',active:'Aktiv',notes:'Noter',address:'Adresse',contact_name:'Kontaktperson',phone:'Telefon',email:'E-mail',lead_time_days:'Leveringstid (dage)',symbol:'Symbol',dimension:'Enhedstype',machine_type_id:'Maskintype'};
const errorText=(e:unknown)=>e instanceof Error?e.message:'Handlingen kunne ikke gennemføres.';
export function Masterdata({company,kind,title,canManage}:{company:string;kind:string;title:string;canManage:boolean}){
 const cache=useQueryClient();const prefix=`/companies/${company}/masterdata/${kind}`;
 const [q,setQ]=useState('');const [active,setActive]=useState('all');const [sort,setSort]=useState('code');const [page,setPage]=useState(1);
 const [editing,setEditing]=useState<Row|null|undefined>();const [history,setHistory]=useState<Row>();const [status,setStatus]=useState('');
 const list=useQuery({queryKey:['masterdata',company,kind,q,active,sort,page],queryFn:()=>accessApi<List>(`${prefix}?${new URLSearchParams({q,active,sort,page:String(page)})}`),retry:false});
 return <>
 <div className="master-toolbar"><label>Søg efter nummer eller navn<input type="search" maxLength={120} value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/></label><label>Status<select value={active} onChange={e=>{setActive(e.target.value);setPage(1);}}><option value="all">Alle</option><option value="true">Aktive</option><option value="false">Inaktive</option></select></label><label>Sortér efter<select value={sort} onChange={e=>{setSort(e.target.value);setPage(1);}}><option value="code">Nummer</option><option value="name">Navn</option></select></label>{canManage&&<button className="primary" onClick={()=>{setEditing(null);setHistory(undefined);setStatus('');}}>Opret ny</button>}</div>
 {status&&<p role="status">{status}</p>}{list.isPending&&<p role="status">Henter {title.toLowerCase()}…</p>}{list.error&&<div role="alert"><p>{errorText(list.error)}</p><button onClick={()=>void list.refetch()}>Prøv igen</button></div>}
 {editing!==undefined&&canManage&&<MasterForm key={editing?.id??'new'} row={editing} company={company} kind={kind} close={()=>setEditing(undefined)} saved={async()=>{setEditing(undefined);setStatus('Ændringen er gemt.');await cache.invalidateQueries({queryKey:['masterdata',company]});}}/>}
 {list.data&&<section className="access-card"><div className="table-scroll"><table><caption>{title} · {list.data.total} i alt</caption><thead><tr><th>Nummer</th><th>Navn</th><th>Status</th><th>Handlinger</th></tr></thead><tbody>{list.data.items.map(row=><tr key={row.id}><td>{row.code}</td><td>{row.name}</td><td><span className={row.active?'master-active':'master-inactive'}>{row.active?'Aktiv':'Inaktiv'}</span></td><td><div className="master-actions"><button onClick={()=>{setHistory(row);setEditing(undefined);}}>Detaljer og historik</button>{canManage&&<button onClick={()=>{setEditing(row);setHistory(undefined);setStatus('');}}>Redigér</button>}</div></td></tr>)}</tbody></table></div>{list.data.items.length===0&&<p>Ingen resultater. {q?'Prøv en anden søgning.':canManage?'Opret den første registrering.':''}</p>}<div className="master-actions"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Forrige</button><span>Side {page}</span><button disabled={page*25>=list.data.total} onClick={()=>setPage(p=>p+1)}>Næste</button></div></section>}
 {history&&<History key={history.id} row={history} prefix={prefix} company={company} kind={kind} close={()=>setHistory(undefined)}/>}
 </>;
}
export function MasterForm({row,company,kind,close,saved}:{row:Row|null;company:string;kind:string;close:()=>void;saved:(row:Row)=>Promise<void>}){
 const fields:Field[]=[{key:'code',label:'Nummer / kode',max:60},{key:'name',label:'Navn',max:160},...(['customers','suppliers'].includes(kind)?contacts:[]),...(kind==='units'?[{key:'symbol',label:'Symbol',max:20}]:[])];
 const [draft,setDraft]=useState<Record<string,unknown>>(()=>({code:'',name:'',active:true,notes:'',...Object.fromEntries(fields.map(f=>[f.key,row?.[f.key]??''])),...(kind==='suppliers'?{lead_time_days:row?.lead_time_days??null}:{}),...(kind==='units'?{dimension:row?.dimension??'count'}:{}),...(kind==='machines'?{machine_type_id:row?.machine_type_id??null}:{}),...(row?{active:row.active,notes:row.notes}:{})}));
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [typeSearch,setTypeSearch]=useState('');const [creatingType,setCreatingType]=useState(false);const cache=useQueryClient();
 const types=useQuery({queryKey:['masterdata',company,'machine_types','picker',typeSearch],queryFn:()=>accessApi<List>(`/companies/${company}/masterdata/machine_types?${new URLSearchParams({q:typeSearch,active:'true',limit:'100'})}`),enabled:kind==='machines',retry:false});
 function change(key:string,value:unknown){setDraft(d=>({...d,[key]:value}));}
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;if(row?.active&&!draft.active&&!window.confirm('Deaktivér registreringen? Historikken bevares.'))return;setBusy(true);setError('');try{const result=await accessApi<Row>(`/companies/${company}/masterdata/${kind}${row?'/'+row.id:''}`,row?'PATCH':'POST',row?{version:row.version,data:draft}:draft);await saved(result);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <section className="access-card"><h2>{row?'Redigér '+row.name:'Ny registrering'}</h2><form onSubmit={submit}><fieldset disabled={busy} className="master-fields">{fields.map(f=><label key={f.key}>{f.label}<input type={f.type??'text'} maxLength={f.max} required={['code','name','symbol'].includes(f.key)} value={String(draft[f.key]??'')} onChange={e=>change(f.key,e.target.value)}/></label>)}
 {kind==='suppliers'&&<label>Standardleveringstid (dage)<input type="number" min={0} max={3650} step={1} value={draft.lead_time_days===null?'':String(draft.lead_time_days)} onChange={e=>change('lead_time_days',e.target.value===''?null:Number(e.target.value))}/></label>}
 {kind==='units'&&<label>Enhedstype<select aria-label="Enhedstype" disabled={!!row} value={String(draft.dimension)} onChange={e=>change('dimension',e.target.value)}>{Object.entries(dimensions).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><small>Typen kan ikke ændres efter oprettelse.</small></label>}
 {kind==='machines'&&<><label>Søg maskintype<input type="search" maxLength={120} value={typeSearch} onChange={e=>setTypeSearch(e.target.value)}/></label><label>Maskintype<select aria-label="Maskintype" value={String(draft.machine_type_id??'')} onChange={e=>change('machine_type_id',e.target.value||null)}><option value="">Ikke angivet</option>{!!draft.machine_type_id&&!types.data?.items.some(t=>t.id===draft.machine_type_id)&&<option value={String(draft.machine_type_id)}>Nuværende maskintype</option>}{types.data?.items.map(t=><option value={t.id} key={t.id}>{t.code} · {t.name}</option>)}</select></label><button type="button" onClick={()=>setCreatingType(true)}>Opret maskintype</button>{types.error&&<p role="alert">Maskintyper kunne ikke hentes.</p>}{(types.data?.total??0)>100&&<p>Præcisér søgningen for at finde flere maskintyper.</p>}</>}
 <label className="master-wide">Noter<textarea maxLength={4000} rows={3} value={String(draft.notes)} onChange={e=>change('notes',e.target.value)}/></label><label className="check"><input type="checkbox" checked={!!draft.active} onChange={e=>change('active',e.target.checked)}/>Aktiv</label></fieldset>
 {error&&<p role="alert">{error}</p>}<div className="master-actions"><button className="primary" disabled={busy}>{busy?'Gemmer…':'Gem'}</button><button type="button" disabled={busy} onClick={close}>Annullér</button></div></form>{creatingType&&<MasterForm row={null} company={company} kind="machine_types" close={()=>setCreatingType(false)} saved={async type=>{await cache.invalidateQueries({queryKey:['masterdata',company,'machine_types']});change('machine_type_id',type.id);setCreatingType(false);}}/>}</section>;
}
function History({row,prefix,company,kind,close}:{row:Row;prefix:string;company:string;kind:string;close:()=>void}){
 const history=useQuery({queryKey:['masterdata',company,kind,row.id,'history'],queryFn:()=>accessApi<{id:string;action:string;actor_id:string;occurred_at:string;before_value:Row|null;after_value:Row}[]>(`${prefix}/${row.id}/history`),retry:false});
 const value=(v:unknown)=>typeof v==='boolean'?(v?'Ja':'Nej'):v===null||v===''?'—':String(v);
 return <section className="access-card"><div className="master-actions"><h2>{row.name}</h2><button onClick={close}>Luk detaljer</button></div><dl className="master-details">{Object.entries(labels).filter(([key])=>key in row).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{key==='dimension'?dimensions[String(row[key])]:value(row[key])}</dd></div>)}</dl><h3>Seneste 100 ændringer</h3>{history.isPending&&<p role="status">Henter historik…</p>}{history.error&&<p role="alert">{errorText(history.error)}</p>}{history.data?.map(h=><details key={h.id}><summary>{new Date(h.occurred_at).toLocaleString('da-DK')} · {h.action==='INSERT'?'Oprettet':'Ændret'}</summary><p>Bruger-ID: {h.actor_id}</p><ul>{Object.entries(labels).filter(([key])=>key in h.after_value&&(!h.before_value||h.before_value[key]!==h.after_value[key])).map(([key,label])=><li key={key}>{label}: {h.before_value?value(h.before_value[key])+' → ':''}{value(h.after_value[key])}</li>)}</ul></details>)}</section>;
}
