import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {accessApi} from './auth-client';
import {TransferForm} from './Transfers';
import {Entry} from './Inventory';
export function MaterialIssues({company,orderId,canIssue}:{company:string;orderId:string;canIssue:boolean}){
 const [open,setOpen]=useState(false),[page,setPage]=useState(1),[selected,setSelected]=useState('');const cache=useQueryClient(),base=`/companies/${company}/production-orders/${orderId}/material-issues`;
 const list=useQuery({queryKey:['material-issues',company,orderId,page],queryFn:()=>accessApi<{items:{id:string;kind:string;production_return_of?:string;reason:string;posted_at:string;production_snapshot:{machine?:{name:string}}}[];total:number}>(base+'?page='+page),retry:false});
 const options=useQuery({queryKey:['material-issue-options',company,orderId],queryFn:()=>accessApi<{components:{id:string}[];machine_location_id:string|null}>(base+'/options'),enabled:canIssue,retry:false});
 async function refresh(){await cache.invalidateQueries({queryKey:['production-waste',company,orderId]});await cache.invalidateQueries({queryKey:['material-issues',company,orderId]});await cache.invalidateQueries({queryKey:['inventory']});await cache.invalidateQueries({queryKey:['transfer-balances',company]});}
 return <section className="access-card"><h3>Materiale til produktion</h3><p>Materialet flyttes til produktionen med samme ejer. Det er ikke forbrug. Registreringen knyttes til denne ordre.</p>{canIssue&&<button disabled={!options.data} onClick={()=>setOpen(true)}>Send materiale til produktion</button>}{(list.error||options.error)&&<p role="alert">Materialeflytninger kunne ikke hentes. <button onClick={()=>{void list.refetch();if(canIssue)void options.refetch();}}>Prøv igen</button></p>}{open&&options.data&&<TransferForm key={orderId} company={company} orderId={orderId} components={options.data.components.map(c=>c.id)} machineLocation={options.data.machine_location_id} close={()=>setOpen(false)} saved={async()=>{setOpen(false);await refresh();}}/>}{list.data&&<><table><caption>Materialeflytninger · {list.data.total}</caption><thead><tr><th>Tid</th><th>Handling</th><th>Maskine</th><th>Kommentar</th><th>Detaljer</th></tr></thead><tbody>{list.data.items.map(e=><tr key={e.id}><td>{new Date(e.posted_at).toLocaleString('da-DK')}</td><td>{e.kind==='reversal'?'Modpostering':e.kind==='production_consumption'?'Nettoforbrug':e.production_return_of?'Retur':'Til produktion'}</td><td>{e.production_snapshot.machine?.name}</td><td>{e.reason}</td><td><button onClick={()=>setSelected(e.id)}>Vis materialeflytning</button></td></tr>)}</tbody></table>{!list.data.total&&<p>Ingen materialeflytninger registreret.</p>}<button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Forrige materialeflytninger</button><button disabled={page*25>=list.data.total} onClick={()=>setPage(p=>p+1)}>Næste materialeflytninger</button></>}{selected&&<Entry key={selected} prefix={`/companies/${company}/inventory`} id={selected} canAdjust={false} close={()=>setSelected('')} saved={refresh}/>}</section>;
}
