import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {accessApi} from './auth-client';
import {Picker} from './Inventory';
const message=(e:unknown)=>e instanceof Error?e.message:'Handlingen kunne ikke gennemføres.';
const direction=(n:string)=>BigInt(n)>0n?'Modpart skylder os':BigInt(n)<0n?'Vi skylder modpart':'Afregnet';
const kinds:Record<string,string>={outbound:'Sendt',inbound:'Modtaget / retur',correction:'Korrektion',reverse:'Modpostering',shipment:'Forsendelse'};
export function PalletAccounts({company,permissions}:{company:string;permissions:string[]}){
 const base=`/companies/${company}/pallet-accounts`,cache=useQueryClient(),can=(p:string)=>permissions.includes(p);
 const[tab,setTab]=useState('balances'),[page,setPage]=useState(1),[from,setFrom]=useState(''),[to,setTo]=useState(''),[partyKind,setPartyKind]=useState('customer'),[party,setParty]=useState(''),[type,setType]=useState(''),[creating,setCreating]=useState(false),[selected,setSelected]=useState<any>(null);
 const data=useQuery({queryKey:['pallet-accounts',company,tab,page,from,to,partyKind,party,type],queryFn:()=>accessApi<{items:any[];total:number}>(base+'/'+tab+'?page='+page+(party?'&'+partyKind+'_id='+party:'')+(type?'&pallet_type_id='+type:'')+(to?'&to='+to:'')+(tab==='entries'&&from?'&from='+from:'')),retry:false});
 async function saved(){await cache.invalidateQueries({queryKey:['pallet-accounts']});setCreating(false);setSelected(null);}
 return <><p>Positiv saldo: modparten skylder os. Negativ saldo: vi skylder modparten. Alle antal er stk. Mellemværender ændrer ikke fysisk lager.</p><button onClick={()=>{setTab('balances');setPage(1);}}>Saldi</button><button onClick={()=>{setTab('entries');setPage(1);}}>Pallehistorik</button>
 {can('masterdata.read')&&<><label>Modpartstype<select value={partyKind} onChange={e=>{setPartyKind(e.target.value);setParty('');setPage(1);}}><option value="customer">Kunde</option><option value="supplier">Leverandør</option></select></label><Picker path={`/companies/${company}/masterdata/${partyKind==='customer'?'customers':'suppliers'}`} label="Modpartsfilter" value={party} change={v=>{setParty(v);setPage(1);}}/><Picker path={`/companies/${company}/masterdata/pallet_types`} label="Emballagetypefilter" value={type} change={v=>{setType(v);setPage(1);}}/></>}
 {tab==='entries'&&<label>Fra dato<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1);}}/></label>}<label>{tab==='balances'?'Saldo til og med dato':'Til dato'}<input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1);}}/></label>
 {can('masterdata.read')&&(can('pallets.manage')||can('pallets.adjust'))&&<button onClick={()=>setCreating(true)}>Ny pallebevægelse</button>}
 {data.error&&<p role="alert">{message(data.error)}</p>}{data.data&&<section className="access-card"><div className="table-scroll"><table><caption>{tab==='balances'?'Pallesaldi':'Pallebevægelser'} · {data.data.total}</caption><thead><tr><th>Modpart</th><th>Type</th><th>Antal</th><th>{tab==='balances'?'Mellemværende':'Hændelse'}</th><th>Reference</th></tr></thead><tbody>{data.data.items.map((x,i)=><tr key={x.id??i}><td>{x.snapshot.party.name} ({x.snapshot.party.kind==='customer'?'Kunde':'Leverandør'})</td><td>{x.snapshot.type.name}</td><td>{x.quantity}</td><td>{tab==='balances'?direction(x.quantity):kinds[x.kind]}</td><td>{tab==='entries'&&<button onClick={()=>setSelected(x)}>{x.reference||'Vis postering'}</button>}</td></tr>)}</tbody></table></div>{!data.data.items.length&&<p>Ingen pallebevægelser fundet.</p>}<button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Forrige</button><span>Side {page}</span><button disabled={page*25>=data.data.total} onClick={()=>setPage(p=>p+1)}>Næste</button></section>}
 {creating&&<Movement company={company} can={can} saved={saved} close={()=>setCreating(false)}/>}
 {selected&&<section className="access-card"><h2>{kinds[selected.kind]} · {selected.quantity} stk.</h2><p>{selected.occurred_on.slice(0,10)} · {selected.reference} · {selected.reason}</p><p>Registreret {new Date(selected.created_at).toLocaleString('da-DK')} · {selected.actor_id}</p>{selected.shipment_id&&<p>Forsendelse: {selected.shipment_id}</p>}{selected.reverses_id&&<p>Modposterer: {selected.reverses_id}</p>}{can('pallets.adjust')&&selected.kind!=='reverse'&&<Reverse key={selected.id} base={base} row={selected} saved={saved}/>}<button onClick={()=>setSelected(null)}>Luk postering</button></section>}
 </>;
}
function Reverse({base,row,saved}:{base:string;row:any;saved:()=>Promise<void>}){
 const[reason,setReason]=useState(''),[pending,setPending]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function send(){if(busy)return;if(!pending&&!window.confirm('Modpostér '+row.quantity+' stk.? Mellemværendet ændres modsat. Fysisk lager og forsendelsesstatus ændres ikke.'))return;const body=pending??{idempotency_key:crypto.randomUUID(),reason};setPending(body);setBusy(true);try{await accessApi(base+'/entries/'+row.id+'/reverse','POST',body);await saved();}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <><label>Begrundelse for modpostering<input minLength={3} maxLength={1000} value={reason} disabled={busy||!!pending} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button disabled={busy||reason.trim().length<3} onClick={()=>void send()}>{pending?'Prøv samme modpostering igen':'Modpostér'}</button></>;
}
function Movement({company,can,saved,close}:{company:string;can:(p:string)=>boolean;saved:()=>Promise<void>;close:()=>void}){
 const[action,setAction]=useState(can('pallets.manage')?'outbound':'correction'),[partyKind,setPartyKind]=useState('customer'),[party,setParty]=useState(''),[type,setType]=useState(''),[quantity,setQuantity]=useState(''),[date,setDate]=useState(''),[reference,setReference]=useState(''),[reason,setReason]=useState(''),[pending,setPending]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function send(){if(busy)return;if(!pending&&!window.confirm('Bogfør pallemellemværendet? Sendt øger saldoen, modtaget mindsker den. Korrektion bruger det angivne fortegn. Fysisk lager ændres ikke.'))return;const body=pending??{idempotency_key:crypto.randomUUID(),action,reason,data:{customer_id:partyKind==='customer'?party:null,supplier_id:partyKind==='supplier'?party:null,pallet_type_id:type,quantity,occurred_on:date,reference}};setPending(body);setBusy(true);try{await accessApi(`/companies/${company}/pallet-accounts/movements`,'POST',body);await saved();}catch(e){setError(message(e)+' Samme input genbruges ved gentagelse.');}finally{setBusy(false);}}
 return <form className="access-card" onSubmit={e=>{e.preventDefault();void send();}}><h2>Ny pallebevægelse</h2><p>For en forsendelse skal emballagen angives på forsendelsens kladde. Registrér ikke samme afsendelse igen her.</p><fieldset disabled={busy||!!pending}><label>Bevægelse<select value={action} onChange={e=>setAction(e.target.value)}>{can('pallets.manage')&&<><option value="outbound">Sendt</option><option value="inbound">Modtaget / retur</option></>}{can('pallets.adjust')&&<option value="correction">Korrektion / startsaldo</option>}</select></label><label>Modpartstype<select value={partyKind} onChange={e=>{setPartyKind(e.target.value);setParty('');}}><option value="customer">Kunde</option><option value="supplier">Leverandør</option></select></label><Picker path={`/companies/${company}/masterdata/${partyKind==='customer'?'customers':'suppliers'}`} label="Modpart" value={party} change={setParty}/><Picker path={`/companies/${company}/masterdata/pallet_types`} label="Emballagetype" value={type} change={setType}/><label>Antal stk.<input required inputMode="numeric" pattern={action==='correction'?'-?[1-9][0-9]{0,8}':'[1-9][0-9]{0,8}'} value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Dato<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Reference<input maxLength={160} value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Begrundelse / kommentar<input required minLength={3} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label></fieldset>{error&&<p role="alert">{error}</p>}<button disabled={busy||!party||!type}>{pending?'Prøv samme bevægelse igen':'Bogfør pallebevægelse'}</button><button type="button" disabled={busy} onClick={()=>{if(!pending||window.confirm('Bevægelsen kan være gemt. Kontrollér historikken før ny registrering. Luk?'))close();}}>Luk</button></form>;
}
export function ShipmentPalletExchange({company,row,permissions,saved}:{company:string;row:{id:string;version:number;status:string;pallet_exchange?:any[]};permissions:string[];saved:(id?:string)=>Promise<void>}){
 const[lines,setLines]=useState<{pallet_type_id:string;quantity:string}[]>((row.pallet_exchange??[]).map(x=>({pallet_type_id:x.pallet_type_id,quantity:x.quantity}))),[reason,setReason]=useState(''),[pending,setPending]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const can=permissions.includes('pallets.read')&&permissions.includes('pallets.manage')&&permissions.includes('shipments.manage')&&permissions.includes('masterdata.read');
 return <section><h3>Genbrugsemballage / pallemellemværende</h3><p>{row.pallet_exchange?.length?row.pallet_exchange.map(x=>x.quantity+' × '+x.snapshot.name).join(', '):'Ingen genbrugsemballage angivet.'} Bogføres automatisk ved afsendelse. Angiv de faktiske paller, rammer eller andre genbrugstyper; pakkeoversigten kan bruges som støtte.</p>{row.status==='draft'&&can&&<form onSubmit={e=>{e.preventDefault();if(busy)return;if(!pending&&!window.confirm('Gem genbrugsemballage? Pallesaldo ændres først ved afsendelse.'))return;const body=pending??{idempotency_key:crypto.randomUUID(),version:row.version,reason,lines};setPending(body);setBusy(true);void accessApi(`/companies/${company}/pallet-accounts/shipments/${row.id}`,'POST',body).then(()=>saved(row.id)).catch(e=>setError(message(e)+' Ved konflikt: genindlæs forsendelsen.')).finally(()=>setBusy(false));}}><fieldset disabled={busy||!!pending}>{lines.map((l,i)=><div key={i}><Picker path={`/companies/${company}/masterdata/pallet_types`} label={'Genbrugstype '+(i+1)} value={l.pallet_type_id} change={v=>setLines(old=>old.map((x,n)=>n===i?{...x,pallet_type_id:v}:x))}/><label>Antal genbrugsemballage<input required pattern="[1-9][0-9]{0,8}" inputMode="numeric" value={l.quantity} onChange={e=>setLines(old=>old.map((x,n)=>n===i?{...x,quantity:e.target.value}:x))}/></label><button type="button" onClick={()=>setLines(old=>old.filter((_,n)=>n!==i))}>Fjern genbrugstype {i+1}</button></div>)}<button type="button" disabled={lines.length>=100} onClick={()=>setLines(old=>[...old,{pallet_type_id:'',quantity:''}])}>Tilføj genbrugstype</button><label>Begrundelse for genbrugsemballage<input required minLength={3} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label></fieldset>{error&&<p role="alert">{error}</p>}<button disabled={busy||lines.some(x=>!x.pallet_type_id)}>{pending?'Prøv samme emballage igen':'Gem genbrugsemballage'}</button></form>}</section>;
}
