import {useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {accessApi} from './auth-client';
import {LocationPicker} from './Locations';
type Material={issue_id:string;item_id:string;owner_id:string;location_id:string;issued_quantity:string;returned_quantity:string;remaining_quantity:string;snapshot:{item:{name:string};owner:{name:string};location:{name:string};unit:{symbol:string}}};
type Review={review_token:string;good_quantity:string;planned_quantity:string;materials:Material[]};
export function ProductionClose({company,orderId,status,version,problem,canReturn,canClose,refresh}:{company:string;orderId:string;status:string;version:number;problem:boolean;canReturn:boolean;canClose:boolean;refresh:()=>Promise<void>}){
 const base=`/companies/${company}/production-orders/${orderId}/close`,cache=useQueryClient();
 const [issue,setIssue]=useState(''),[destination,setDestination]=useState<string|null>(null),[quantity,setQuantity]=useState(''),[comment,setComment]=useState(''),[rejected,setRejected]=useState('0'),[confirmed,setConfirmed]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState<{path:string;body:object}|null>(null);const sending=useRef(false);
 const review=useQuery({queryKey:['production-close',company,orderId,version],queryFn:()=>accessApi<Review>(base+'/review'),retry:false});
 const result=useQuery({queryKey:['production-close-result',company,orderId],queryFn:()=>accessApi<{comment:string;snapshot:Review&{rejected_quantity:string}}>(base+'/result'),enabled:status==='completed',retry:false});
 async function send(command:{path:string;body:object}){if(sending.current)return;sending.current=true;setBusy(true);setPending(command);setError('');try{await accessApi(command.path,'POST',command.body);setPending(null);setQuantity('');setConfirmed(false);await cache.invalidateQueries({queryKey:['deliveries',company,orderId]});await cache.invalidateQueries({queryKey:['production-waste',company,orderId]});await cache.invalidateQueries({queryKey:['production-close',company,orderId]});await cache.invalidateQueries({queryKey:['material-issues',company,orderId]});await cache.invalidateQueries({queryKey:['inventory']});await cache.invalidateQueries({queryKey:['transfer-balances',company]});await refresh();}catch(e){setError(e instanceof Error?e.message:'Handlingen kunne ikke gennemføres.');}finally{sending.current=false;setBusy(false);}}
 const materials=review.data?.materials??[],closed=status==='completed';
 return <section className="access-card"><h3>Materialeretur og afslutning</h3>{review.error&&<p role="alert">Afstemningen kunne ikke hentes. <button onClick={()=>void review.refetch()}>Hent afstemning igen</button></p>}
 {review.data&&<><p>Registrerede gode emner: {review.data.good_quantity} · Planlagt: {review.data.planned_quantity}</p><div className="table-scroll"><table><caption>Udleveret materiale pr. ejer og produktionsplacering</caption><thead><tr><th>Materiale / ejer</th><th>Placering</th><th>Udleveret</th><th>Retur</th><th>{closed?'Afstemt nettoforbrug':'Til afstemning'}</th></tr></thead><tbody>{materials.map(m=><tr key={m.issue_id}><td>{m.snapshot.item.name} · {m.snapshot.owner.name}</td><td>{m.snapshot.location.name}</td><td>{m.issued_quantity}</td><td>{m.returned_quantity}</td><td>{m.remaining_quantity} {m.snapshot.unit.symbol}</td></tr>)}</tbody></table></div>{!materials.length&&<p>Ingen udestående materialeudleveringer.</p>}</>}
 {!closed&&canReturn&&['planned','ready','in_production','reconciliation'].includes(status)&&<details><summary>Returnér ubrugt materiale</summary><form onSubmit={e=>{e.preventDefault();if(pending||busy)return;if(!issue||!destination){setError('Vælg udlevering og tilplacering.');return;}if(window.confirm('Returnér den angivne mængde? Materialet flyttes tilbage med samme ejer.'))void send({path:base+'/returns',body:{idempotency_key:crypto.randomUUID(),issue_id:issue,to_location_id:destination,quantity:quantity.replace(',','.'),comment}});}}><fieldset disabled={busy||!!pending}><label>Udlevering til retur<select aria-label="Udlevering til retur" required value={issue} onChange={e=>setIssue(e.target.value)}><option value="">Vælg materialeudlevering</option>{materials.filter(m=>!/^0(\.0+)?$/.test(m.remaining_quantity)).map(m=><option key={m.issue_id} value={m.issue_id}>{m.snapshot.item.name} · {m.snapshot.owner.name} · {m.snapshot.location.name} · {m.remaining_quantity}</option>)}</select></label><LocationPicker company={company} label="Returplacering" value={destination} change={setDestination} storageOnly/><label>Returmængde<input required inputMode="decimal" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Returkommentar<textarea required minLength={3} maxLength={1000} value={comment} onChange={e=>setComment(e.target.value)}/></label></fieldset><button disabled={busy||!!pending}>Returnér materiale</button></form></details>}
 {canClose&&status==='in_production'&&<button disabled={busy||!!pending} onClick={()=>{if(window.confirm('Gå til afstemning? Nye produktionstal og udleveringer stoppes, mens materialer stadig kan returneres.'))void send({path:`/companies/${company}/production-orders/${orderId}/status`,body:{version,status:'reconciliation'}});}}>Begynd afstemning</button>}
 {canClose&&status==='reconciliation'&&<><p>1. Kontrollér de gode emner ovenfor. Genåbn produktionen, hvis registreringer skal rettes.</p><button disabled={busy||!!pending} onClick={()=>void send({path:`/companies/${company}/production-orders/${orderId}/status`,body:{version,status:'in_production'}})}>Tilbage til produktion</button><p>2. Returnér alt ubrugt materiale, også ubrugt emballage. De resterende mængder i tabellen bogføres som faktisk nettoforbrug, ikke automatisk som fysisk spild.</p><p>3. Kontrollér pakkeopbygningen på ordren. Lageraflevering af færdigvarer og paller sker separat under opgaven “Aflever til lager”.</p><form onSubmit={e=>{e.preventDefault();if(!review.data||pending||busy||!confirmed)return;if(window.confirm('Afslut produktionen permanent? De viste nettomængder trækkes fra produktionslageret én gang. Ordren og registreringerne låses. Der oprettes ikke færdigvarelager.'))void send({path:base,body:{idempotency_key:crypto.randomUUID(),review_token:review.data.review_token,rejected_quantity:rejected.replace(',','.'),comment,confirm_materials:true}});}}><fieldset disabled={busy||!!pending}><label>Kasserede emner<input required inputMode="decimal" value={rejected} onChange={e=>setRejected(e.target.value)}/></label><label>Afslutningskommentar og afvigelser<textarea required minLength={3} maxLength={2000} value={comment} onChange={e=>setComment(e.target.value)}/></label><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Jeg har kontrolleret gode emner og returneret alt ubrugt materiale. De viste nettomængder er brugt.</label></fieldset><button className="primary" disabled={busy||!!pending||!confirmed||!review.data||problem}>Afslut produktion</button></form></>}
 {closed&&result.data&&<><p>Produktionen er afsluttet og låst. Gode emner: {result.data.snapshot.good_quantity}. Kasserede emner: {result.data.snapshot.rejected_quantity}.</p><p>{result.data.comment}</p></>}{result.error&&<p role="alert">Afslutningsdokumentet kunne ikke hentes.</p>}
 {error&&<p role="alert">{error}</p>}{pending&&<p>Kontrollér resultatet før en ny handling. <button disabled={busy} onClick={()=>void send(pending)}>Prøv samme handling igen</button><button disabled={busy} onClick={()=>{if(window.confirm('Kontrollér først historik og ordrestatus. Handlingen kan allerede være gemt. Hent ny afstemning?')){setPending(null);setConfirmed(false);void review.refetch();void refresh();}}}>Hent ny afstemning</button></p>}
 </section>;
}
