import {useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {accessApi} from './auth-client';
type Material={item_id:string;unit_id:string;name:string;unit:string;consumption_owner:string|null;issued_quantity:string;returned_quantity:string;net_quantity:string;theoretical_quantity:string|null;difference_quantity:string|null;measured_waste_quantity:string;unexplained_quantity:string|null;difference_percent:string|null;waste_percent:string|null;warnings:string[]};
type Waste={id:string;kind:string;reversed:boolean;quantity:string;comment:string;created_at:string;created_by:string;snapshot:{stock:{item:{name:string};unit:{symbol:string};owner:{name:string}}}};
const warnings:Record<string,string>={PROVISIONAL_UNRETURNED_STOCK:'Foreløbig: ubrugt materiale kan stadig stå i produktion.',MEASURED_WASTE_EXCEEDS_NET:'Målt spild overstiger nettoforbruget. Kontrollér registreringerne.',NEGATIVE_MATERIAL_DIFFERENCE:'Negativ materialedifference. Kontrollér forbrug, retur og stykliste.',THEORETICAL_BASIS_MISSING:'Teoretisk grundlag mangler.',UNIT_MISMATCH:'Enhederne matcher ikke det historiske beregningsgrundlag.',WASTE_ISSUE_REVERSED:'Spild er knyttet til en modposteret udlevering.'};
export function ProductionWaste({company,orderId,status,canRecord,canCorrect}:{company:string;orderId:string;status:string;canRecord:boolean;canCorrect:boolean}){
 const base=`/companies/${company}/production-orders/${orderId}/waste`,cache=useQueryClient();
 const [page,setPage]=useState(1),[issue,setIssue]=useState(''),[quantity,setQuantity]=useState(''),[comment,setComment]=useState(''),[pending,setPending]=useState<{path:string;body:object}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const sending=useRef(false);
 const analysis=useQuery({queryKey:['production-waste',company,orderId,'analysis',status],queryFn:()=>accessApi<{final:boolean;materials:Material[]}>(base+'/analysis'),retry:false});
 const history=useQuery({queryKey:['production-waste',company,orderId,page],queryFn:()=>accessApi<{items:Waste[];total:number}>(base+`?page=${page}`),retry:false});
 const choices=useQuery({queryKey:['production-close',company,orderId,'waste-options'],queryFn:()=>accessApi<{materials:{issue_id:string;snapshot:{item:{name:string};owner:{name:string};unit:{symbol:string}}}[]}>(`/companies/${company}/production-orders/${orderId}/close/review`),enabled:canRecord,retry:false});
 async function refresh(){await cache.invalidateQueries({queryKey:['production-waste',company,orderId]});await cache.invalidateQueries({queryKey:['production-analysis',company]});}
 async function send(command:{path:string;body:object}){if(sending.current)return;sending.current=true;setBusy(true);setPending(command);setError('');try{await accessApi(command.path,'POST',command.body);setPending(null);setQuantity('');setComment('');await refresh();}catch(e){setError(e instanceof Error?e.message:'Registreringen kunne ikke gemmes.');}finally{sending.current=false;setBusy(false);}}
 return <section className="access-card"><h3>Materialedifference og fysisk spild</h3><p>Difference = udleveret − retur − teoretisk forbrug til gode emner. Målt fysisk spild registreres separat. Lageret ændres ikke her.</p><button onClick={()=>void refresh()}>Opdatér materialeanalysen</button>
 {analysis.error&&<p role="alert">Materialeanalysen kunne ikke hentes.</p>}{Array.isArray(analysis.data?.materials)&&<><p>{analysis.data.final?'Afsluttet ordre: forbrugsgrundlaget er låst.':'Foreløbig analyse: netto er endnu ikke endeligt forbrug.'} Procenter beregnes af udleveret minus retur; uden positivt netto vises ingen procent. Ingen mængder lægges sammen på tværs af enheder.</p><div className="table-scroll"><table><caption>Materialeanalyse pr. komponent og enhed</caption><thead><tr><th>Komponent</th><th>Udleveret / retur</th><th>Netto</th><th>Teoretisk</th><th>Difference / %</th><th>Målt spild / %</th><th>Uforklaret difference</th></tr></thead><tbody>{analysis.data.materials.map(m=><tr key={m.item_id+':'+m.unit_id}><td>{m.name} ({m.unit}) · {m.consumption_owner==='packing'?'Pakning':'BOM'}{m.warnings.map(w=><p key={w}>{warnings[w]??'Kontrollér grundlaget.'}</p>)}</td><td>{m.issued_quantity} / {m.returned_quantity}</td><td>{m.net_quantity}</td><td>{m.theoretical_quantity??'Mangler'}</td><td>{m.difference_quantity??'Mangler'} / {m.difference_percent??'—'} %</td><td>{m.measured_waste_quantity} / {m.waste_percent??'—'} %</td><td>{m.unexplained_quantity??'Mangler'}</td></tr>)}</tbody></table></div></>}
 {canRecord&&['in_production','reconciliation','completed'].includes(status)&&<form onSubmit={e=>{e.preventDefault();if(busy||pending)return;if(window.confirm('Registrér målt fysisk spild? Observationen gemmes i historikken. Den ændrer ikke lageret eller det afsluttede forbrug.'))void send({path:base,body:{idempotency_key:crypto.randomUUID(),issue_id:issue,quantity:quantity.replace(',','.'),comment}});}}><fieldset disabled={busy||!!pending}><label>Spildets materialeudlevering<select aria-label="Spildets materialeudlevering" required value={issue} onChange={e=>setIssue(e.target.value)}><option value="">Vælg udlevering</option>{choices.data?.materials?.map(m=><option key={m.issue_id} value={m.issue_id}>{m.snapshot.item.name} · {m.snapshot.owner.name} · {m.snapshot.unit.symbol} · {m.issue_id.slice(0,8)}</option>)}</select></label><label>Målt spildmængde<input required inputMode="decimal" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Spildkommentar<textarea required minLength={3} maxLength={2000} value={comment} onChange={e=>setComment(e.target.value)}/></label></fieldset><button className="primary" disabled={busy||!!pending}>Registrér fysisk spild</button>{choices.error&&<p role="alert">Materialeudleveringer kunne ikke hentes.</p>}</form>}
 {error&&<p role="alert">{error}</p>}{pending&&<p>Kontrollér historikken ved usikker forbindelse. <button disabled={busy} onClick={()=>void send(pending)}>Prøv samme spildhandling igen</button><button disabled={busy} onClick={()=>{if(window.confirm('Handlingen kan allerede være gemt. Kontrollér historikken før en ny registrering.')){setPending(null);void refresh();}}}>Kontrollér spildhistorik</button></p>}
 <h4>Spildhistorik</h4>{history.error&&<p role="alert">Spildhistorikken kunne ikke hentes.</p>}{history.data?.items?.map(w=><p key={w.id}>{new Date(w.created_at).toLocaleString('da-DK')} · {w.snapshot.stock.item.name} · {w.snapshot.stock.owner.name} · {w.kind==='reversal'?'Modregistrering':w.reversed?'Modregistreret':'Målt spild'}: {w.quantity} {w.snapshot.stock.unit.symbol} · {w.comment} · Bruger {w.created_by}{canCorrect&&w.kind==='record'&&!w.reversed&&<button disabled={busy||!!pending} onClick={()=>{const reason=window.prompt('Begrund modregistreringen af fysisk spild. Lageret ændres ikke.');if(reason&&reason.trim().length>=3)void send({path:base+'/'+w.id+'/reverse',body:{idempotency_key:crypto.randomUUID(),comment:reason}});}}>Modregistrér spild</button>}</p>)}<button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Forrige spildside</button><button disabled={page*25>=(history.data?.total??0)} onClick={()=>setPage(p=>p+1)}>Næste spildside</button>
 </section>;
}
