import {MoreInformation} from './MoreInformation';
import {useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {accessApi} from './auth-client';
type Entry={id:string;kind:string;quantity:string;boxes:number|null;comment:string;created_at:string;created_by:string;reversed:boolean};
export function ProductionRegistrations({company,orderId,running,problem,canRecord,canCorrect}:{company:string;orderId:string;running:boolean;problem:boolean;canRecord:boolean;canCorrect:boolean}){
 const base=`/companies/${company}/production-orders/${orderId}/registrations`,cache=useQueryClient();
 const [page,setPage]=useState(1),[quantity,setQuantity]=useState(''),[boxes,setBoxes]=useState(''),[comment,setComment]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState<{path:string;body:object}|null>(null);const sending=useRef(false);
 const list=useQuery({queryKey:['production-registrations',company,orderId,page],queryFn:()=>accessApi<{items:Entry[];total:number}>(base+'?page='+page),retry:false});
 const summary=useQuery({queryKey:['production-summary',company,orderId],queryFn:()=>accessApi<{good_quantity:string;planned_quantity:string;progress_percent:string;overproduced:boolean;unit:{symbol:string}}>(base+'/summary'),retry:false});
 async function send(command:{path:string;body:object}){if(sending.current)return;sending.current=true;setBusy(true);setError('');setPending(command);try{await accessApi(command.path,'POST',command.body);setPending(null);setQuantity('');setBoxes('');setComment('');await cache.invalidateQueries({queryKey:['deliveries',company,orderId]});await cache.invalidateQueries({queryKey:['production-waste',company,orderId]});await cache.invalidateQueries({queryKey:['production-registrations',company,orderId]});await cache.invalidateQueries({queryKey:['production-summary',company,orderId]});}catch(e){setError(e instanceof Error?e.message:'Registreringen kunne ikke gemmes.');}finally{setBusy(false);sending.current=false;}}
 return <section className="access-card"><h3>Produktionsregistrering</h3><p>Registrér kun nye gode emner siden sidste registrering. Lageraflevering sker separat.</p>{summary.data&&<p>Gode emner: {summary.data.good_quantity} / {summary.data.planned_quantity} {summary.data.unit?.symbol} · {summary.data.progress_percent} %{summary.data.overproduced&&' · Overproduktion'}</p>}{(list.error||summary.error)&&<p role="alert">Produktionsregistreringer kunne ikke hentes. <button onClick={()=>{void list.refetch();void summary.refetch();}}>Prøv igen</button></p>}
 {running&&canRecord&&!problem&&<form onSubmit={e=>{e.preventDefault();if(pending||busy)return;const q=quantity.replace(',','.');if(!/^(?:0|[1-9]\d{0,11})(?:\.\d{1,8})?$/.test(q)||!/[1-9]/.test(q)||boxes!==''&&!/^\d{1,10}$/.test(boxes)){setError('Angiv en positiv mængde og eventuelt et helt antal kasser.');return;}if(window.confirm(`Registrér ${q} gode emner? Lageret ændres ikke.`))void send({path:base,body:{idempotency_key:crypto.randomUUID(),quantity:q,boxes:boxes===''?null:Number(boxes),comment}});}}><fieldset disabled={busy||!!pending}><label>Nye gode emner<input required inputMode="decimal" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><MoreInformation enabled><label>Antal kasser (valgfrit)<input inputMode="numeric" value={boxes} onChange={e=>setBoxes(e.target.value)}/></label><p>Kasser er en oplysning om registreringen og medfører ikke emballageforbrug.</p><label>Produktionskommentar<textarea maxLength={2000} value={comment} onChange={e=>setComment(e.target.value)}/></label></MoreInformation></fieldset><button className="primary" disabled={busy||!!pending}>Registrér gode emner</button></form>}
 {error&&<p role="alert">{error}</p>}{pending&&<p>Svaret er usikkert eller afvist. Kontrollér historikken før en ny registrering. <button disabled={busy} onClick={()=>void send(pending)}>Prøv samme registrering igen</button><button disabled={busy} onClick={()=>{if(window.confirm('Kontrollér først historikken, da registreringen kan være gemt. Frigiv formularen?'))setPending(null);}}>Frigiv formular</button></p>}
 {list.data&&<><div className="table-scroll"><table><caption>Registreringer · {list.data.total}</caption><thead><tr><th>Tid</th><th>Gode emner</th><th>Kasser</th><th>Kommentar</th><th>Handling</th></tr></thead><tbody>{list.data.items.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString('da-DK')}</td><td>{r.kind==='reversal'?'-':''}{r.quantity}{r.reversed&&' · Modregistreret'}</td><td>{r.boxes??'Ikke angivet'}</td><td>{r.comment}</td><td>{running&&canCorrect&&r.kind==='record'&&!r.reversed&&<button disabled={busy||!!pending} onClick={()=>{const reason=window.prompt('Begrund modregistreringen. Hele registreringen trækkes fra gode emner; historik og lager bevares.');if(reason?.trim())void send({path:base+'/'+r.id+'/reverse',body:{idempotency_key:crypto.randomUUID(),comment:reason.trim()}});}}>Modregistrér</button>}</td></tr>)}</tbody></table></div>{!list.data.total&&<p>Ingen produktion registreret.</p>}<button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Forrige registreringer</button><button disabled={page*25>=list.data.total} onClick={()=>setPage(p=>p+1)}>Næste registreringer</button></>}
 </section>;
}
