import {useEffect,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {accessApi} from './auth-client';
import {Picker,Entry} from './Inventory';
import {LocationPicker} from './Locations';
const msg=(e:unknown)=>e instanceof Error?e.message:'Modtagelsen kunne ikke gemmes.';
const decimal=/^(0|[1-9][0-9]{0,11})(\.[0-9]{1,8})?$/;
const clean=(v:string)=>v.trim().replace(',','.');
// Exact eight-place arithmetic for the preview, matching database precision.
export function receiptDifference(actual:string,expected:string):string|null{
 const a=clean(actual),e=clean(expected);if(!decimal.test(a)||!decimal.test(e))return null;
 const units=(v:string)=>{const [whole='0',fraction='']=v.split('.');return BigInt(whole)*100000000n+BigInt(fraction.padEnd(8,'0'));};
 const difference=units(a)-units(e),abs=difference<0n?-difference:difference;return (difference<0n?'-':'')+(abs/100000000n).toString()+'.'+(abs%100000000n).toString().padStart(8,'0');
}
type Receipt={id:string;reference:string;received_at:string;quantity:string;expected_quantity:string|null;difference:string|null;pallet_count:number|null;comment:string;reversal_id:string|null;supplier_snapshot:{name:string}|null;snapshot:{item:{code:string;name:string};owner:{name:string};location:{name:string};unit:{symbol:string}}};
export function Receiving({company,canReceive,canAdjust,canMasterRead}:{company:string;canReceive:boolean;canAdjust:boolean;canMasterRead:boolean}){
 const cache=useQueryClient(),prefix=`/companies/${company}/receipts`;const[q,setQ]=useState(''),[page,setPage]=useState(1),[creating,setCreating]=useState(false),[selected,setSelected]=useState(''),[status,setStatus]=useState('');
 const list=useQuery({queryKey:['receipts',company,q,page],queryFn:()=>accessApi<{items:Receipt[];total:number}>(prefix+'?'+new URLSearchParams({q,page:String(page)})),retry:false});
 async function refresh(){await cache.invalidateQueries({queryKey:['receipts',company]});await cache.invalidateQueries({queryKey:['inventory']});}
 return <><p>Registrér den faktisk modtagne mængde i varens lagerenhed. En ukendt forventet mængde kan stå tom.</p><div className="master-toolbar"><label>Søg modtagelser<input type="search" maxLength={120} value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/></label>{canReceive&&canMasterRead&&<button onClick={()=>setCreating(true)}>Ny modtagelse</button>}</div>{canReceive&&!canMasterRead&&<p>Du skal have stamdata-læseadgang for at vælge vare og placering.</p>}{status&&<p role="status">{status}</p>}{creating&&<ReceiptForm company={company} close={()=>setCreating(false)} saved={async()=>{setCreating(false);await refresh();setStatus('Modtagelsen er bogført på lageret.');}}/>}{list.isPending&&<p>Henter modtagelser…</p>}{list.error&&<p role="alert">{msg(list.error)} <button onClick={()=>void list.refetch()}>Prøv igen</button></p>}{list.data&&<section className="access-card"><div className="table-scroll"><table><caption>Modtagelser · {list.data.total}</caption><thead><tr>{['Tid','Vare','Leverandør','Ejer / placering','Forventet','Modtaget','Difference','Paller','Reference','Status','Handling'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{list.data.items.map(r=><tr key={r.id}><td>{new Date(r.received_at).toLocaleString('da-DK')}</td><td>{r.snapshot.item.code} · {r.snapshot.item.name}</td><td>{r.supplier_snapshot?.name??'—'}</td><td>{r.snapshot.owner.name} / {r.snapshot.location.name}</td><td>{r.expected_quantity??'—'}</td><td>{r.quantity} {r.snapshot.unit.symbol}</td><td>{r.difference===null?'Ikke beregnet':<strong>{r.difference} {r.snapshot.unit.symbol}{!/^0(\.0+)?$/.test(r.difference)&&' · Afvigelse'}</strong>}</td><td>{r.pallet_count??'—'}</td><td>{r.reference}</td><td>{r.reversal_id?'Modposteret':'Bogført'}</td><td><button onClick={()=>setSelected(r.id)}>Vis modtagelse</button></td></tr>)}</tbody></table></div>{!list.data.items.length&&<p>Ingen modtagelser fundet.</p>}<div className="master-actions"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Forrige</button><span>Side {page}</span><button disabled={page*25>=list.data.total} onClick={()=>setPage(p=>p+1)}>Næste</button></div></section>}{selected&&<Entry key={selected} prefix={`/companies/${company}/inventory`} id={selected} canAdjust={canAdjust} close={()=>setSelected('')} saved={refresh}/>}</>;
}
function ReceiptForm({company,close,saved}:{company:string;close:()=>void;saved:()=>Promise<void>}){
 const base=`/companies/${company}`;const[kind,setKind]=useState('material'),[item,setItem]=useState(''),[owner,setOwner]=useState(''),[supplier,setSupplier]=useState(''),[location,setLocation]=useState<string|null>(null),[quantity,setQuantity]=useState(''),[expected,setExpected]=useState(''),[pallets,setPallets]=useState(''),[reference,setReference]=useState(''),[comment,setComment]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState<object|null>(null);const[key]=useState(()=>crypto.randomUUID());
 const itemInfo=useQuery({queryKey:['receipt-item',company,kind,item],queryFn:()=>accessApi<{id:string;unit_id:string|null;supplier_id:string|null;standard_location_id:string|null}>(base+'/items/'+kind+'/'+item),enabled:!!item,retry:false});
 const unit=useQuery({queryKey:['receipt-unit',company,itemInfo.data?.unit_id],queryFn:()=>accessApi<{symbol:string;dimension:string}>(base+'/masterdata/units/'+itemInfo.data?.unit_id),enabled:!!itemInfo.data?.unit_id,retry:false});
 useEffect(()=>{if(itemInfo.data){setSupplier(itemInfo.data.supplier_id??'');setLocation(itemInfo.data.standard_location_id??null);}},[itemInfo.data]);
 const difference=receiptDifference(quantity,expected);
 async function submit(){if(busy)return;const a=clean(quantity),e=clean(expected);if(!pending){if(!itemInfo.data?.unit_id||!unit.data){setError('Vælg en vare med en lagerenhed.');return;}if(!decimal.test(a)||/^0(\.0+)?$/.test(a)||e!==''&&!decimal.test(e)){setError('Modtaget mængde skal være positiv. Brug højst 12 heltal og 8 decimaler.');return;}if(['count','package'].includes(unit.data.dimension)&&[a,e].some(x=>x.includes('.')&&!/^\d+\.0+$/.test(x))){setError('Denne lagerenhed kræver hele antal.');return;}if(!location){setError('Vælg lagerplacering.');return;}if(!window.confirm(`Modtag ${a} ${unit.data.symbol}? Fysisk lager øges med denne mængde.${difference!==null&&!/^0\.0+$/.test(difference)?' Afvigelse fra forventet: '+difference+' '+unit.data.symbol+'.':''}`))return;}
 const body=pending??{idempotency_key:key,item_id:item,owner_id:owner,location_id:location,quantity:a,expected_quantity:e||null,supplier_id:supplier||null,pallet_count:pallets===''?null:Number(pallets),reference,comment};setPending(body);setBusy(true);setError('');try{await accessApi(base+'/receipts','POST',body);await saved();}catch(err){setError(msg(err)+' Ved usikker forbindelse: prøv samme registrering igen. Felterne er låst for at undgå dobbeltregistrering.');}finally{setBusy(false);}}
 return <section className="access-card"><h2>Ny modtagelse</h2><form onSubmit={e=>{e.preventDefault();void submit();}}><fieldset disabled={busy||!!pending}><label>Varetype<select value={kind} onChange={e=>{setKind(e.target.value);setItem('');setSupplier('');setLocation(null);}}><option value="material">Materiale</option><option value="packaging">Emballage</option><option value="product">Færdigvare</option></select></label><Picker path={base+'/items/'+kind} label="Vare" value={item} change={setItem}/>{itemInfo.error&&<p role="alert">{msg(itemInfo.error)}</p>}{unit.error&&<p role="alert">{msg(unit.error)}</p>}<p>Lagerenhed: {unit.data?.symbol??(itemInfo.data&&!itemInfo.data.unit_id?'Mangler på varen':'Vælg vare')}</p><Picker path={base+'/inventory/owners'} label="Ejer" value={owner} change={setOwner}/><Picker optional path={base+'/masterdata/suppliers'} label="Leverandør" value={supplier} change={setSupplier}/><LocationPicker company={company} label="Placering" value={location} change={setLocation} storageOnly/><label>Forventet mængde<input inputMode="decimal" value={expected} onChange={e=>setExpected(e.target.value)}/></label><label>Modtaget mængde<input required inputMode="decimal" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><p role="status">{difference===null?'Difference beregnes, når begge mængder er angivet.':`Difference: ${difference} ${unit.data?.symbol??''}${!/^0\.0+$/.test(difference)?' · Afvigelse':''}`}</p><label>Antal paller<input type="number" min={0} max={1000000} step={1} value={pallets} onChange={e=>setPallets(e.target.value)}/></label><small>Palleantal registreres som en oplysning om denne modtagelse.</small><label>Reference<input maxLength={160} value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Kommentar<textarea maxLength={4000} value={comment} onChange={e=>setComment(e.target.value)}/></label></fieldset>{error&&<p role="alert">{error}</p>}<button disabled={busy}>{pending?'Prøv samme modtagelse igen':'Bekræft modtagelse'}</button><button type="button" disabled={busy} onClick={()=>{if(!pending||window.confirm('Kontrollér modtagelserne før en ny registrering. Den tidligere kan allerede være gemt. Luk?'))close();}}>Luk</button></form></section>;
}
