import { FormEvent, useState, useEffect, useRef } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { createPortal } from 'react-dom';
import { ItemForm } from './Items';
import { MasterForm } from './Masterdata';
import { accessApi } from './auth-client';
type Pick={id:string;code:string;name:string};
type Line={component_id:string;kind:string;level:number;quantity:string;snapshot?:{name:string;unit:string}};
type Revision={id:string;revision:number;base_quantity:string;pallet_type_id:string|null;notes:string;lines:Line[];snapshot:{name:string;unit:string}};
type Recipe={id:string;name:string;kind:string;version:number;active:boolean;is_default:boolean;notes:string;current_revision_id:string|null;current?:Revision;revisions?:Revision[]};
const errorText=(e:unknown)=>e instanceof Error?e.message:'Handlingen kunne ikke gennemføres.';
const normal=(s:string)=>s.replace(',','.');
export function Recipes({company,canManage}:{company:string;canManage:boolean}){
 const [product,setProduct]=useState('');
 return <><p>Versionér materialeforbrug og pakning. Beregninger ændrer ikke lageret.</p><CatalogPicker company={company} kind="product" create={canManage} label="Vare" value={product} change={setProduct}/>{product&&<ProductRecipes key={company+product} company={company} product={product} canManage={canManage}/>}</>;
}
function CatalogPicker({company,kind,label,value,change,create=false}:{company:string;kind:string;label:string;value:string;change:(v:string)=>void;create?:boolean}){
 const [creating,setCreating]=useState(false),cache=useQueryClient();
 const[q,setQ]=useState('');const [category,setCategory]=useState(kind==='component'?'material':kind);
 const path=category==='pallet_types'?'masterdata':'items';
 const list=useQuery({queryKey:['recipe-picker',company,category,q],queryFn:()=>accessApi<{items:Pick[];total:number}>(`/companies/${company}/${path}/${category}?${new URLSearchParams({q,active:'true',limit:'100'})}`),retry:false});
 return <div className="item-reference">{creating&&<CreateDialog close={()=>setCreating(false)}>{category==='pallet_types'?<MasterForm row={null} company={company} kind={category} close={()=>setCreating(false)} saved={async row=>{change(row.id);setCreating(false);await cache.invalidateQueries({queryKey:['recipe-picker',company]});}}/>:<ItemForm row={null} company={company} kind={category} close={()=>setCreating(false)} saved={async row=>{change(row.id);setCreating(false);await cache.invalidateQueries({queryKey:['recipe-picker',company]});}}/>}</CreateDialog>}{kind==='component'&&<label>Komponenttype<select aria-label="Komponenttype" value={category} onChange={e=>{setCategory(e.target.value);setQ('');change('');}}><option value="material">Materiale</option><option value="packaging">Produktionsemballage</option><option value="product">Lagerført komponent</option></select></label>}<label>Søg {label.toLowerCase()}<input type="search" maxLength={120} value={q} onChange={e=>setQ(e.target.value)}/></label><label>{label}<select aria-label={label} required={kind!=='pallet_types'} value={value} onChange={e=>change(e.target.value)}><option value="">Vælg</option>{value&&!list.data?.items.some(x=>x.id===value)&&<option value={value}>Nuværende valg</option>}{list.data?.items.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label>{create&&<button type="button" onClick={()=>setCreating(true)}>Opret {label.toLowerCase()}</button>}{list.error&&<p role="alert">Valg kunne ikke hentes. <button type="button" onClick={()=>void list.refetch()}>Prøv igen</button></p>}{(list.data?.total??0)>100&&<small>Præcisér søgningen for at finde flere.</small>}</div>;
}
function ProductRecipes({company,product,canManage}:{company:string;product:string;canManage:boolean}){
 const prefix=`/companies/${company}/recipes`,cache=useQueryClient();const[name,setName]=useState(''),[kind,setKind]=useState('bom'),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const list=useQuery({queryKey:['recipes',company,product],queryFn:()=>accessApi<Recipe[]>(prefix+'?product_id='+product),retry:false});
 async function create(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await accessApi<Recipe>(prefix,'POST',{product_id:product,kind,name});setName('');setSelected(r.id);await cache.invalidateQueries({queryKey:['recipes',company]});}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <><section className="access-card"><h2>Styklister og pakkeopbygninger</h2>{list.error&&<p role="alert">{errorText(list.error)}</p>}{list.isPending&&<p role="status">Henter opsætninger…</p>}<div className="table-scroll"><table><thead><tr><th>Navn</th><th>Type</th><th>Status</th><th>Handling</th></tr></thead><tbody>{list.data?.map(r=><tr key={r.id}><td>{r.name}{r.is_default?' · Standard':''}</td><td>{r.kind==='bom'?'Stykliste':'Pakning'}</td><td>{!r.active?'Inaktiv':r.current_revision_id?'Klar':'Version mangler'}</td><td><button onClick={()=>setSelected(r.id)}>Åbn</button></td></tr>)}</tbody></table></div>{list.data?.length===0&&<p>Ingen opsætninger endnu.</p>}{canManage&&<form className="inline-form" onSubmit={create}><label>Type<select aria-label="Type" value={kind} onChange={e=>setKind(e.target.value)}><option value="bom">Stykliste</option><option value="packing">Pakkeopbygning</option></select></label><label>Navn<input required maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><button disabled={busy}>Opret opsætning</button></form>}{error&&<p role="alert">{error}</p>}</section>
 {selected&&<RecipeDetail key={selected} company={company} id={selected} canManage={canManage}/>}<Calculator key={(list.data??[]).map(r=>r.version).join(',')} company={company} recipes={list.data??[]}/></>;
}
function RecipeDetail({company,id,canManage}:{company:string;id:string;canManage:boolean}){
 const prefix=`/companies/${company}/recipes/${id}`,cache=useQueryClient(),[edit,setEdit]=useState(false),[history,setHistory]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const detail=useQuery({queryKey:['recipe',company,id],queryFn:()=>accessApi<Recipe>(prefix),retry:false});
 const historical=useQuery({queryKey:['recipe-revision',company,id,history],queryFn:()=>accessApi<Revision>(prefix+'/revisions/'+history),enabled:!!history,retry:false});
 const audit=useQuery({queryKey:['recipe-history',company,id],queryFn:()=>accessApi<{id:string;action:string;occurred_at:string}[]>(prefix+'/history'),retry:false});
 async function refresh(){await Promise.all([cache.invalidateQueries({queryKey:['recipe',company,id]}),cache.invalidateQueries({queryKey:['recipes',company]}),cache.invalidateQueries({queryKey:['recipe-history',company,id]})]);}
 async function metadata(action:'default'|'active'|'rename'){if(!detail.data)return;const r=detail.data;const name=action==='rename'?window.prompt('Navn',r.name):r.name;if(name===null)return;setBusy(true);setError('');try{await accessApi(prefix,'PATCH',{version:r.version,data:{name,notes:r.notes,active:action==='active'?!r.active:r.active,is_default:action==='default'?true:action==='active'?false:r.is_default}});await refresh();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 const r=detail.data,shown=history?historical.data:r?.current;
 return <section className="access-card">{detail.error&&<p role="alert">{errorText(detail.error)}</p>}{r&&<><h2>{r.name}</h2>{canManage&&<div className="master-actions"><button disabled={busy} onClick={()=>setEdit(!edit)}>{edit?'Luk formular':'Ny version'}</button><button disabled={busy} onClick={()=>void metadata('rename')}>Omdøb</button><button disabled={busy} onClick={()=>void metadata('active')}>{r.active?'Deaktivér':'Aktivér'}</button><button disabled={busy||!r.active||!r.current_revision_id||r.is_default} onClick={()=>void metadata('default')}>Gør til standard</button></div>}{error&&<p role="alert">{error}</p>}{edit&&canManage&&<RevisionForm key={r.version} company={company} recipe={r} saved={async()=>{setEdit(false);setHistory('');await refresh();}}/>}
 <label>Vis version<select aria-label="Vis version" value={history} onChange={e=>setHistory(e.target.value)}><option value="">Aktuel version</option>{r.revisions?.map(v=><option key={v.id} value={v.id}>Version {v.revision}</option>)}</select></label>{historical.error&&<p role="alert">{errorText(historical.error)}</p>}{shown&&<><p>Version {shown.revision} · {shown.snapshot.name} · Basis {shown.base_quantity} {shown.snapshot.unit}</p><div className="table-scroll"><table><thead><tr><th>Komponent</th><th>Mængde / kapacitet</th><th>Enhed</th><th>Anvendelse</th><th>Niveau</th></tr></thead><tbody>{shown.lines.map(l=><tr key={l.component_id}><td>{l.snapshot?.name}</td><td>{l.quantity}</td><td>{l.kind==='container'?(l.level===0?shown.snapshot.unit:`beholdere fra niveau ${l.level-1}`):l.snapshot?.unit}</td><td>{l.kind==='component'?'BOM':l.kind==='container'?'Beholder':'Tilbehør'}</td><td>{l.level}</td></tr>)}</tbody></table></div><p>{shown.notes}</p></>}
 <details><summary>Ændringshistorik</summary>{audit.error&&<p role="alert">{errorText(audit.error)}</p>}{audit.data?.map(a=><p key={a.id}>{new Date(a.occurred_at).toLocaleString('da-DK')} · {a.action==='INSERT'?'Oprettet':'Ændret'}</p>)}</details></>}</section>;
}
function RevisionForm({company,recipe,saved}:{company:string;recipe:Recipe;saved:()=>Promise<void>}){
 const [base,setBase]=useState(recipe.current?.base_quantity??'1'),[pallet,setPallet]=useState(recipe.current?.pallet_type_id??''),[notes,setNotes]=useState(''),[lines,setLines]=useState<Line[]>(recipe.current?.lines.map(({component_id,kind,level,quantity})=>({component_id,kind,level,quantity}))??[]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const bom=recipe.kind==='bom';function change(i:number,patch:Partial<Line>){setLines(ls=>ls.map((l,n)=>n===i?{...l,...patch}:l));}
 async function save(e:FormEvent){e.preventDefault();if(!window.confirm('Gem ny version? Tidligere versioner bevares uændret.'))return;setBusy(true);setError('');try{await accessApi(`/companies/${company}/recipes/${recipe.id}/revisions`,'POST',{version:recipe.version,data:{base_quantity:bom?normal(base):'1',pallet_type_id:pallet||null,notes,lines:lines.map(l=>({...l,quantity:normal(l.quantity)}))}});await saved();}catch(e){setError(errorText(e)+' Kontrollér enheder, aktive komponenter, niveauer og emballagens forbrugsansvar.');}finally{setBusy(false);}}
 return <form className="item-section" onSubmit={save}><h3>Ny version</h3><p>{bom?'Angiv forbrug i hver komponents lagerenhed. Brug fx en basis på 12 for præcist at angive 1 kasse pr. 12 varer.':'Niveau 0 er den inderste beholder. Kapaciteten er antal varenheder på niveau 0 og antal beholdere fra forrige niveau på de næste niveauer. Tilbehør angives pr. beholder på det valgte niveau.'}</p><p>Produktionsemballage tilhører BOM. Pakke- og transportemballage tilhører pakningen. Samme komponent må ikke bruges begge steder.</p>{bom?<label>Basis i varens lagerenhed<input required inputMode="decimal" value={base} onChange={e=>setBase(e.target.value)}/></label>:<CatalogPicker company={company} create kind="pallet_types" label="Palletype for yderste niveau" value={pallet} change={setPallet}/>}
 {lines.map((l,i)=><fieldset className="item-section" key={i}><legend>Linje {i+1}</legend><CatalogPicker company={company} create kind={bom?'component':'packaging'} label={`Komponent ${i+1}`} value={l.component_id} change={v=>change(i,{component_id:v})}/>{!bom&&<div className="master-fields"><label>Anvendelse<select aria-label="Anvendelse" value={l.kind} onChange={e=>change(i,{kind:e.target.value})}><option value="container">Beholder</option><option value="accessory">Tilbehør</option></select></label><label>Niveau<input type="number" min={0} max={15} required value={l.level} onChange={e=>change(i,{level:Number(e.target.value)})}/></label></div>}<label>{bom?'Forbrug pr. basis':l.kind==='container'?'Kapacitet':'Antal pr. beholder'}<input required inputMode="decimal" value={l.quantity} onChange={e=>change(i,{quantity:e.target.value})}/></label><button type="button" onClick={()=>setLines(ls=>ls.filter((_,n)=>n!==i))}>Fjern linje {i+1}</button></fieldset>)}
 <button type="button" disabled={lines.length>=100} onClick={()=>setLines(ls=>[...ls,{component_id:'',kind:bom?'component':'container',level:bom?0:ls.filter(l=>l.kind==='container').length,quantity:'1'}])}>Tilføj linje</button><label>Versionsnoter<textarea maxLength={4000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="primary" disabled={busy||lines.length===0}>Gem ny version</button>{error&&<p role="alert">{error}</p>}</form>;
}
function Calculator({company,recipes}:{company:string;recipes:Recipe[]}){
 const[bom,setBom]=useState(recipes.find(r=>r.kind==='bom'&&r.is_default)?.current_revision_id??''),[pack,setPack]=useState(recipes.find(r=>r.kind==='packing'&&r.is_default)?.current_revision_id??''),[qty,setQty]=useState('1'),[result,setResult]=useState<any>(),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function run(e:FormEvent){e.preventDefault();setBusy(true);setError('');setResult(undefined);try{setResult(await accessApi(`/companies/${company}/recipes/calculate`,'POST',{quantity:normal(qty),...(bom?{bom_revision_id:bom}:{}),...(pack?{packing_revision_id:pack}:{})}));}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <section className="access-card"><h2>Beregn behov</h2><p>Teoretisk forbrug afrundes op til 8 decimaler. Pakning afrundes til hele beholdere. Der bogføres intet forbrug.</p><form onSubmit={run}><div className="master-fields">{[['bom','Stykliste',bom,setBom],['packing','Pakning',pack,setPack]].map(([kind,label,value,setter])=><label key={String(kind)}>{String(label)}<select aria-label={String(label)} value={String(value)} onChange={e=>{(setter as (v:string)=>void)(e.target.value);setResult(undefined);}}><option value="">Ingen</option>{recipes.filter(r=>r.kind===kind&&r.active&&r.current_revision_id).map(r=><option key={r.id} value={r.current_revision_id!}>{r.name}</option>)}</select></label>)}<label>Produktionsmængde<input required inputMode="decimal" value={qty} onChange={e=>{setQty(e.target.value);setResult(undefined);}}/></label></div><button disabled={busy||(!bom&&!pack)}>Beregn</button></form>{error&&<p role="alert">{error}</p>}{result&&<div role="status"><h3>Behov for {result.quantity} varenheder</h3>{result.materials.map((l:any)=><p key={l.component_id}>{l.name}: {l.quantity} {l.unit} · BOM</p>)}{result.packaging.map((l:any)=><p key={l.component_id}>{l.snapshot.name}: {l.quantity} {l.snapshot.unit} · Pakning</p>)}{result.containers.map((c:any)=><p key={c.level}>Niveau {c.level}: {c.full} fulde + {c.partial} delbeholdere · kapacitet {c.capacity} · rest {c.remainder} varenheder</p>)}</div>}</section>;
}

function CreateDialog({close,children}:{close:()=>void;children:React.ReactNode}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);
 return createPortal(<dialog ref={ref} className="recipe-create-dialog" aria-label="Opret stamdata" onCancel={close} onSubmit={e=>e.stopPropagation()}>{children}</dialog>,document.body);
}
