import {useEffect,useRef,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {accessApi} from './auth-client';
import type {DashboardTarget} from './Dashboard';
const kinds={stock:{name:'Aktuel lagerbeholdning',rights:['inventory.read'],help:'Fysisk, reserveret og disponibel beholdning nu. Se lagerjournalen for de bevægelser, som danner beholdningen.'},inventory:{name:'Lagerjournal',rights:['inventory.read'],help:'Signerede lagerbevægelser i perioden. Flytninger har både en udgående og en indgående linje. Modposteringer hører til deres egen bogføringsdato.'},production:{name:'Produktion',rights:['production.read'],help:'Registrerede gode emner minus modregistreringer i perioden. Det er ikke planlagt antal eller færdigvareafleveringer.'},consumption:{name:'Bogført forbrug',rights:['inventory.read','production.read'],help:'Afsluttede ordrers bogførte nettomaterialeforbrug. Materiale flyttet til en maskine er ikke i sig selv forbrug.'},waste:{name:'Målt fysisk spild',rights:['inventory.read','production.read'],help:'Målt spild minus modregistreringer i perioden. Tallene er observationer, ikke ekstra lagerforbrug eller beregnet uforklaret afvigelse.'},shipments:{name:'Afsendte forsendelser',rights:['inventory.read','shipments.read'],help:'Faktisk afsendte mængder fra lagerjournalen på afsendelsesdatoen. Kladder, reservationer og annullerede forsendelser er ikke med.'}};
type Kind=keyof typeof kinds;
type Filters={q?:string;from?:string;to?:string;item_id?:string;owner_id?:string;location_id?:string;order_id?:string};
type Row={row_id:string;occurred_at:string;source_id:string|null;entry_id:string|null;order_id:string|null;item_id:string;owner_id:string|null;location_id:string|null;unit_id:string;code:string;name:string;owner:string;location:string;unit:string;reference:string;kind:string;quantity:string;reserved_quantity:string;available_quantity:string;reverses_id:string|null};
type View={company_id:string;report:Kind;as_of:string;total:number;items:Row[];totals:{unit_id:string;unit:string;quantity:string;reserved_quantity:string;available_quantity:string}[]};
type Export={company_id:string;filename:string;csv:string;sha256:string;row_count:number;as_of:string;receipt:{id:string}};
const clean=(q:Filters)=>Object.fromEntries(Object.entries(q).filter(([,v])=>v!==''&&v!==undefined)) as Filters;
const error=(e:unknown)=>e instanceof Error?e.message:'Rapporten kunne ikke hentes.';
const stamp=(s:string)=>new Date(s).toLocaleString('da-DK',{timeZone:'Europe/Copenhagen'});
export function Reports({company,permissions,open}:{company:string;permissions:string[];open:(t:DashboardTarget)=>void}){
 const available=(Object.keys(kinds) as Kind[]).filter(k=>kinds[k].rights.every(p=>permissions.includes(p)));
 if(!available.length)return <p>Du har rapportadgang, men mangler læseadgang til rapporternes kilder.</p>;
 return <ReportWorkspace key={company+':'+available.join(',')} company={company} available={available} canExport={permissions.includes('reports.export')} open={open}/>;
}
function ReportWorkspace({company,available,canExport,open}:{company:string;available:Kind[];canExport:boolean;open:(t:DashboardTarget)=>void}){
 const[kind,setKind]=useState<Kind>(available[0]!),[draft,setDraft]=useState<Filters>({}),[applied,setApplied]=useState<Filters>({}),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[failure,setFailure]=useState(''),[generated,setGenerated]=useState('');
 const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const cache=useQueryClient(),base=`/companies/${company}/reports`;
 const report=useQuery({queryKey:['reports',company,kind,applied,page],queryFn:async()=>{const v=await accessApi<View>(`${base}/${kind}?`+new URLSearchParams({...applied,page:String(page)}));if(v.company_id!==company||v.report!==kind)throw new Error('Rapporten har forkert virksomhed eller type.');return v;},retry:false,refetchOnWindowFocus:false});
 const history=useQuery({queryKey:['report-exports',company],queryFn:()=>accessApi<{company_id:string;items:{id:string;report:Kind;row_count:number;sha256:string;created_at:string;filters:Filters}[]}>(base+'/exports?limit=10'),enabled:canExport,retry:false});
 const v=report.data;
 async function download(){if(busy)return;setBusy(true);setFailure('');setGenerated('');try{
  const x=await accessApi<Export>(`${base}/${kind}/export`,'POST',applied);if(!alive.current)return;if(x.company_id!==company)throw new Error('Eksporten har forkert virksomhed.');
  const url=URL.createObjectURL(new Blob([x.csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=x.filename;document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);
  setGenerated(`${x.row_count} rækker genereret ${stamp(x.as_of)}. Kvittering ${x.receipt.id}. SHA-256: ${x.sha256}`);await cache.invalidateQueries({queryKey:['report-exports',company]});
 }catch(e){if(alive.current)setFailure(error(e)+' Ved usikker forbindelse: en ny eksport læser data igen og får en ny kvittering.');}finally{if(alive.current)setBusy(false);}}
 return <><p>Rapporter ændrer ikke lager eller produktion. Totaler gælder alle filtrerede rækker og holdes adskilt efter enhed. Datoer er hele dage i dansk tid.</p>
 <label>Rapporttype<select disabled={busy} value={kind} onChange={e=>{setKind(e.target.value as Kind);setDraft({});setApplied({});setPage(1);setFailure('');setGenerated('');}}>{available.map(k=><option key={k} value={k}>{kinds[k].name}</option>)}</select></label><p>{kinds[kind].help}</p>
 <form onSubmit={e=>{e.preventDefault();setApplied(clean(draft));setPage(1);setFailure('');setGenerated('');}}><fieldset disabled={busy}><label>Søg varenummer, navn eller reference<input maxLength={120} value={draft.q??''} onChange={e=>setDraft({...draft,q:e.target.value})}/></label>
 {kind!=='stock'&&<><label>Fra dato<input type="date" value={draft.from??''} max={draft.to||undefined} onChange={e=>setDraft({...draft,from:e.target.value})}/></label><label>Til dato<input type="date" value={draft.to??''} min={draft.from||undefined} onChange={e=>setDraft({...draft,to:e.target.value})}/></label></>}
 <details><summary>Præcise ID-filtre</summary>{(['item_id',...(kind==='production'?[]:['owner_id','location_id']),...(kind==='stock'?[]:['order_id'])] as (keyof Filters)[]).map(f=><label key={f}>{{item_id:'Vare-ID',owner_id:'Ejer-ID',location_id:'Placerings-ID',order_id:'Ordre-ID'}[f as 'item_id']}<input value={draft[f]??''} pattern="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}" onChange={e=>setDraft({...draft,[f]:e.target.value})}/></label>)}</details>
 <button>Anvend rapportfiltre</button></fieldset></form><p>Viste data og eksport bruger de senest anvendte filtre.</p><button disabled={report.isFetching||busy} onClick={()=>void report.refetch()}>Opdatér rapport</button>
 {report.isPending&&<p>Henter rapport…</p>}{report.error&&<p role="alert">{error(report.error)} Kontrollér filtrene og prøv igen.</p>}
 {v&&!report.error&&<><p>{v.total} rækker · Øjebliksbillede {stamp(v.as_of)}</p><section className="access-card"><h2>Totaler for alle filtrerede rækker</h2>{v.totals.map(t=><p key={t.unit_id}>{t.quantity} {t.unit}{kind==='stock'&&` · Reserveret ${t.reserved_quantity} · Disponibelt ${t.available_quantity}`} · Enhed {t.unit_id}</p>)}{!v.total&&<p>Ingen rækker matcher filtrene.</p>}</section>
 <div className="table-scroll"><table><caption>{kinds[kind].name}</caption><thead><tr>{['Tid','Vare','Ejer / placering','Reference / type','Mængde','Kilde og handling'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{v.items.map(r=><tr key={r.row_id}><td>{stamp(r.occurred_at)}</td><td>{r.code} · {r.name}</td><td>{r.owner} / {r.location}</td><td>{r.reference} · {r.kind}</td><td>{r.quantity} {r.unit}{kind==='stock'&&<><br/>Reserveret {r.reserved_quantity}<br/>Disponibelt {r.available_quantity}</>}</td><td>{kind==='stock'?<button onClick={()=>{const f={item_id:r.item_id,...(r.owner_id?{owner_id:r.owner_id}:{}),...(r.location_id?{location_id:r.location_id}:{})};setKind('inventory');setApplied(f);setDraft(f);setPage(1);}}>Se lagerjournal</button>:<><small>Kilde {r.source_id} · Linje {r.row_id}{r.reverses_id&&` · Modposterer ${r.reverses_id}`}</small><br/>{(kind==='production'||kind==='waste'||kind==='consumption')&&r.order_id&&<button onClick={()=>open({page:'Produktion',id:r.order_id!})}>Åbn produktionsordre</button>}{kind==='shipments'&&r.source_id&&<button onClick={()=>open({page:'Forsendelser',id:r.source_id!})}>Åbn forsendelse</button>}{r.entry_id&&<button onClick={()=>open({page:'Lager',id:r.entry_id!})}>Åbn journalpost</button>}</>}</td></tr>)}</tbody></table></div>
 <button disabled={page===1||busy} onClick={()=>setPage(p=>p-1)}>Forrige rapportside</button><span>Side {page}</span><button disabled={page*25>=v.total||busy} onClick={()=>setPage(p=>p+1)}>Næste rapportside</button>
 {canExport&&<><p>CSV-eksport læser de anvendte filtre på ny: højst 2.000 rækker og 4 MB. Afgræns større rapporter. Historikken beviser generering, ikke modtagelse. Importér ID'er og præcise decimaler som tekst i regneark.</p><button disabled={busy||report.isFetching||v.total>2000} onClick={()=>void download()}>Eksportér filtreret CSV</button>{v.total>2000&&<p>Afgræns til højst 2.000 rækker før eksport.</p>}</>}
 </>}{failure&&<p role="alert">{failure}</p>}{generated&&<p role="status">{generated}</p>}
 {canExport&&<section className="access-card"><h2>Dine seneste genererede eksporter</h2>{history.error&&<p role="alert">Eksporthistorikken kunne ikke hentes.</p>}{history.data?.items.map(h=><details key={h.id}><summary>{stamp(h.created_at)} · {kinds[h.report]?.name??h.report} · {h.row_count} rækker</summary><p>Kvittering {h.id} · SHA-256 {h.sha256}</p><pre>{JSON.stringify(h.filters,null,2)}</pre></details>)}</section>}
 </>;
}
