import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {accessApi} from './auth-client';
import {Picker} from './Inventory';
import {LocationPicker} from './Locations';
type Reservation={id:string;company_id:string;quantity:string;reference:string;reason:string;active:boolean;created_at:string;snapshot:{item:{code:string;name:string};owner:{name:string};location:{name:string};unit:{symbol:string};handling_unit_code:string|null};events:{id:string;kind:string;reason:string;actor_id:string;created_at:string}[]};
const message=(e:unknown)=>e instanceof Error?e.message:'Handlingen kunne ikke gennemføres.';
export function Reservations({company,canReserve,canMasterRead,canProductionRead}:{company:string;canReserve:boolean;canMasterRead:boolean;canProductionRead:boolean}){
 const base=`/companies/${company}/reservations`,cache=useQueryClient();
 const[q,setQ]=useState(''),[active,setActive]=useState('true'),[page,setPage]=useState(1),[create,setCreate]=useState(false),[selected,setSelected]=useState('');
 const list=useQuery({queryKey:['reservations',company,q,active,page],queryFn:()=>accessApi<{items:Reservation[];total:number}>(`${base}?q=${encodeURIComponent(q)}&page=${page}${active?'&active='+active:''}`),retry:false});
 async function saved(){await cache.invalidateQueries({queryKey:['reservations']});await cache.invalidateQueries({queryKey:['inventory']});setCreate(false);setSelected('');}
 return <><p>Reservationer reducerer tilgængeligt lager, men ændrer ikke fysisk lager. Frigiv en reservation, før den reserverede mængde bruges eller flyttes. Forsendelser kommer i næste fase.</p><label>Søg reference eller vare<input value={q} onChange={e=>{setQ(e.target.value);setPage(1);}} maxLength={120}/></label><label>Status<select value={active} onChange={e=>{setActive(e.target.value);setPage(1);}}><option value="true">Aktiv</option><option value="false">Frigivet</option><option value="">Alle</option></select></label>{canReserve&&canMasterRead&&<button onClick={()=>setCreate(true)}>Ny reservation</button>}{list.error&&<p role="alert">{message(list.error)}</p>}{list.isPending&&<p>Henter reservationer…</p>}{create&&<ReservationForm company={company} canProductionRead={canProductionRead} close={()=>setCreate(false)} saved={saved}/>}
 {list.data&&<section className="access-card"><div className="table-scroll"><table><caption>Reservationer · {list.data.total}</caption><thead><tr>{['Reference','Vare','Ejer','Placering / palle','Mængde','Status','Handling'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{list.data.items.map(r=><tr key={r.id}><td>{r.reference}</td><td>{r.snapshot.item.code} · {r.snapshot.item.name}</td><td>{r.snapshot.owner.name}</td><td>{r.snapshot.location.name} {r.snapshot.handling_unit_code}</td><td>{r.quantity} {r.snapshot.unit.symbol}</td><td>{r.active?'Aktiv':'Frigivet'}</td><td><button onClick={()=>setSelected(r.id)}>Vis reservation</button></td></tr>)}</tbody></table></div>{!list.data.items.length&&<p>Ingen reservationer fundet.</p>}<button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Forrige</button><span>Side {page}</span><button disabled={page*25>=list.data.total} onClick={()=>setPage(p=>p+1)}>Næste</button></section>}
 {selected&&<ReservationDetail key={selected} base={base} id={selected} canReserve={canReserve} saved={saved} close={()=>setSelected('')}/>}
 </>;
}
function ReservationForm({company,canProductionRead,close,saved}:{company:string;canProductionRead:boolean;close:()=>void;saved:()=>Promise<void>}){
 const base=`/companies/${company}`;
 const[kind,setKind]=useState('product'),[item,setItem]=useState(''),[owner,setOwner]=useState(''),[location,setLocation]=useState<string|null>(null),[hu,setHu]=useState(''),[quantity,setQuantity]=useState(''),[reference,setReference]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<object|null>(null),[key]=useState(()=>crypto.randomUUID());
 return <section className="access-card"><h2>Ny reservation</h2><p>Vælg løst lager eller en konkret palle. Ved valg af palle hentes vare, ejer og placering automatisk. Brug varens lagerenhed.</p><form onSubmit={e=>{e.preventDefault();if(busy)return;const value=quantity.trim().replace(',','.');if(!pending&&(!location||!/^(0|[1-9][0-9]{0,11})(\.[0-9]{1,8})?$/.test(value)||/^0(\.0+)?$/.test(value))){setError('Vælg placering og en positiv mængde med højst 8 decimaler.');return;}if(!pending&&!window.confirm('Reserver mængden? Tilgængeligt lager reduceres. Fysisk lager ændres ikke.'))return;const body=pending??{idempotency_key:key,item_id:item,owner_id:owner,location_id:location,handling_unit_id:hu.trim()||null,quantity:value,reference,reason};setPending(body);setBusy(true);setError('');void accessApi(base+'/reservations','POST',body).then(saved).catch(e=>setError(message(e)+' Prøv samme reservation igen ved usikker forbindelse.')).finally(()=>setBusy(false));}}><fieldset disabled={busy||!!pending}>{canProductionRead&&<PalletSelect company={company} value={hu} choose={p=>{setHu(p?.id??'');setItem(p?.snapshot.product.id??'');setOwner(p?.snapshot.owner.id??'');setLocation(p?.location_id??null);}}/>}{!hu&&<><label>Varetype<select value={kind} onChange={e=>{setKind(e.target.value);setItem('');}}><option value="product">Færdigvare</option><option value="material">Materiale</option><option value="packaging">Emballage</option></select></label><Picker path={base+'/items/'+kind} label="Vare" value={item} change={setItem}/><Picker path={base+'/inventory/owners'} label="Ejer" value={owner} change={setOwner}/><LocationPicker company={company} label="Placering" value={location} change={setLocation}/></>}<label>Mængde<input required inputMode="decimal" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Reference<input required maxLength={160} value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Begrundelse<input required minLength={3} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label></fieldset>{error&&<p role="alert">{error}</p>}<button disabled={busy}>{pending?'Prøv samme reservation igen':'Bekræft reservation'}</button><button type="button" disabled={busy} onClick={()=>{if(!pending||window.confirm('Reservationen kan allerede være gemt. Kontrollér listen før en ny registrering. Luk?'))close();}}>Luk</button></form></section>;
}
function ReservationDetail({base,id,canReserve,close,saved}:{base:string;id:string;canReserve:boolean;close:()=>void;saved:()=>Promise<void>}){
 const detail=useQuery({queryKey:['reservations',base,id],queryFn:()=>accessApi<Reservation>(base+'/'+id),retry:false});const[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<object|null>(null),[key]=useState(()=>crypto.randomUUID());
 return <section className="access-card"><button onClick={close}>Luk reservation</button>{detail.error&&<p role="alert">{message(detail.error)}</p>}{detail.data&&<><h2>{detail.data.reference}</h2><p>{detail.data.quantity} {detail.data.snapshot.unit.symbol} · {detail.data.reason}</p>{detail.data.events.map(x=><p key={x.id}>{x.kind==='reserve'?'Reserveret':'Frigivet'} · {new Date(x.created_at).toLocaleString('da-DK')} · {x.reason} · Bruger {x.actor_id}</p>)}{canReserve&&detail.data.active&&<form onSubmit={e=>{e.preventDefault();if(busy||!pending&&!window.confirm('Frigiv hele reservationen? Mængden bliver tilgængelig igen. Fysisk lager ændres ikke.'))return;const body=pending??{idempotency_key:key,reason};setPending(body);setBusy(true);void accessApi(base+'/'+id+'/release','POST',body).then(saved).catch(e=>setError(message(e)+' Prøv samme frigivelse igen ved usikker forbindelse.')).finally(()=>setBusy(false));}}><label>Begrundelse for frigivelse<input required minLength={3} maxLength={1000} disabled={busy||!!pending} value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button disabled={busy}>{pending?'Prøv samme frigivelse igen':'Frigiv reservation'}</button></form>}</>}</section>;
}

type Pallet={id:string;code:string;active:boolean;quantity:string;reserved_quantity:string;location_id:string;snapshot:{product:{id:string;name:string};owner:{id:string;name:string}}};
function PalletSelect({company,value,choose}:{company:string;value:string;choose:(p:Pallet|null)=>void}){
 const[q,setQ]=useState('');const list=useQuery({queryKey:['reservation-pallets',company,q],queryFn:()=>accessApi<{items:Pallet[]}>(`/companies/${company}/handling-units?q=${encodeURIComponent(q)}`),retry:false});
 return <><label>Søg palle<input maxLength={120} value={q} onChange={e=>setQ(e.target.value)}/></label><label>Palle eller løst lager<select value={value} onChange={e=>choose(list.data?.items.find(x=>x.id===e.target.value)??null)}><option value="">Løst lager</option>{list.data?.items.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.code} · {p.snapshot.product.name} · {p.snapshot.owner.name} · fysisk {p.quantity}, reserveret {p.reserved_quantity}</option>)}</select></label>{list.error&&<p role="alert">{message(list.error)}</p>}<small>Søg for at afgrænse de første 25 paller.</small></>;
}
