import {ShipmentPalletExchange} from './PalletAccounts';
import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {accessApi} from './auth-client';
import {Picker} from './Inventory';
import {LocationPicker} from './Locations';
import {PalletSelect} from './Reservations';
const labels:Record<string,string>={draft:'Kladde',planned:'Planlagt',reserved:'Reserveret',ready:'Klar',dispatched:'Afsendt',cancelled:'Annulleret'};
const actions:Record<string,string>={plan:'Planlæg',reserve:'Reservér varer',ready:'Markér klar',dispatch:'Afsend forsendelse',cancel:'Annullér forsendelse'};
type Line={item_id:string;owner_id:string;location_id:string;quantity:string;handling_unit_id:string|null;packing_revision_id:string|null;pallet_spaces:string|null;snapshot?:any};
type Shipment={id:string;code:string;status:string;version:number;customer_id:string;ship_date:string;reference:string;carrier:string;notes:string;lines:Line[];snapshot:{customer:{name:string;address:string}};entry_id:string|null;pallet_exchange?:any[];events:{id:string;action:string;reason:string;actor_id:string;created_at:string}[];packing:any};
const empty=():Line=>({item_id:'',owner_id:'',location_id:'',quantity:'',handling_unit_id:null,packing_revision_id:null,pallet_spaces:null});
const errorText=(e:unknown)=>e instanceof Error?e.message:'Handlingen kunne ikke gennemføres.';
export function Shipments({initialId='',company,permissions}: {initialId?:string;company:string;permissions:string[]}){
 const base=`/companies/${company}/shipments`,cache=useQueryClient(),can=(p:string)=>permissions.includes(p);
 const[q,setQ]=useState(''),[status,setStatus]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[customer,setCustomer]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState(initialId),[creating,setCreating]=useState(false),[editing,setEditing]=useState(false);
 const list=useQuery({queryKey:['shipments',company,q,status,from,to,customer,page],queryFn:()=>accessApi<{items:Shipment[];total:number}>(`${base}?q=${encodeURIComponent(q)}&page=${page}${status?'&status='+status:''}${from?'&from='+from:''}${to?'&to='+to:''}${customer?'&customer_id='+customer:''}`),retry:false});
 const detail=useQuery({queryKey:['shipments',company,selected],queryFn:()=>accessApi<Shipment>(base+'/'+selected),enabled:!!selected,retry:false});
 async function saved(id?:string){await cache.invalidateQueries({queryKey:['shipments']});await cache.invalidateQueries({queryKey:['pallet-accounts']});await cache.invalidateQueries({queryKey:['inventory']});await cache.invalidateQueries({queryKey:['reservations']});await cache.invalidateQueries({queryKey:['handling-units']});setCreating(false);setEditing(false);if(id)setSelected(id);}
 return <><p>Planlæg, reservér og afsend. Først ved bekræftet afsendelse reduceres fysisk lager. Pakkeoversigten forbruger ikke emballage igen.</p><label>Søg forsendelse<input value={q} maxLength={120} onChange={e=>{setQ(e.target.value);setPage(1);}}/></label><label>Forsendelsesstatus<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Alle</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Fra dato<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1);}}/></label><label>Til dato<input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1);}}/></label>{can('masterdata.read')&&<Picker path={`/companies/${company}/masterdata/customers`} label="Kundefilter" value={customer} change={v=>{setCustomer(v);setPage(1);}}/>}
 {can('shipments.manage')&&can('inventory.read')&&can('masterdata.read')&&<button onClick={()=>{setCreating(true);setSelected('');}}>Ny forsendelse</button>}
 {list.error&&<p role="alert">{errorText(list.error)}</p>}{list.data&&<section className="access-card"><div className="table-scroll"><table><caption>Forsendelser · {list.data.total}</caption><thead><tr><th>Nummer</th><th>Kunde</th><th>Dato</th><th>Status</th><th>Handling</th></tr></thead><tbody>{list.data.items.map(s=><tr key={s.id}><td>{s.code}</td><td>{s.snapshot.customer.name}</td><td>{s.ship_date.slice(0,10)}</td><td>{labels[s.status]}</td><td><button onClick={()=>{setSelected(s.id);setCreating(false);setEditing(false);}}>Vis forsendelse</button></td></tr>)}</tbody></table></div>{!list.data.items.length&&<p>Ingen forsendelser fundet.</p>}<button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Forrige</button><span>Side {page}</span><button disabled={page*25>=list.data.total} onClick={()=>setPage(p=>p+1)}>Næste</button></section>}
 {creating&&<ShipmentForm key="new" company={company} canProductionRead={can('production.read')} saved={saved} close={()=>setCreating(false)}/>}
 {selected&&detail.error&&<p role="alert">{errorText(detail.error)}</p>}
 {selected&&detail.data&&<section className="access-card"><button onClick={()=>setSelected('')}>Luk forsendelse</button><h2>{detail.data.code} · {labels[detail.data.status]}</h2><p>{detail.data.snapshot.customer.name} · {detail.data.snapshot.customer.address}</p><p>{detail.data.reference} · {detail.data.carrier} · {detail.data.notes}</p>{detail.data.lines.map((l,i)=><p key={i}>{l.snapshot.item.code} · {l.snapshot.item.name}: {l.quantity} {l.snapshot.unit.symbol} · {l.snapshot.owner.name} · {l.snapshot.location.name} · {l.snapshot.handling_unit_code??'Løst lager'}</p>)}<h3>Pakkeoversigt</h3><p>Paller: {detail.data.packing.pallets??'Ukendt — pakkeopbygning mangler'} · Pallepladser: {detail.data.packing.pallet_spaces??'Ikke angivet'}</p>{detail.data.packing.lines.map((l:any,i:number)=><div key={i}>{l.packing?.containers.map((c:any)=><p key={c.component_id}>{c.snapshot.name??c.snapshot.code}: {c.count} · fulde {c.full}, del {c.partial}, rest {c.remainder}</p>)}{l.packing?.packaging.map((c:any)=><p key={c.component_id}>{c.snapshot.name??c.snapshot.code}: {c.quantity}</p>)}</div>)}
 <ShipmentPalletExchange key={detail.data.id+':'+detail.data.version} company={company} row={detail.data} permissions={permissions} saved={saved}/>{detail.data.entry_id&&<p>Lagerpostering: {detail.data.entry_id}</p>}
 {can('shipments.manage')&&can('masterdata.read')&&can('inventory.read')&&detail.data.status==='draft'&&<button onClick={()=>setEditing(true)}>Redigér kladde</button>}
 {editing&&<ShipmentForm key={detail.data.id+detail.data.version} company={company} initial={detail.data} canProductionRead={can('production.read')} saved={saved} close={()=>setEditing(false)}/>}
 {!editing&&<ShipmentActions key={detail.data.id+detail.data.version} base={base} row={detail.data} can={can} saved={saved}/>}
 <h3>Historik</h3>{detail.data.events.map(e=><p key={e.id}>{e.action} · {e.reason} · {new Date(e.created_at).toLocaleString('da-DK')} · {e.actor_id}</p>)}</section>}
 </>;
}
function ShipmentActions({base,row,can,saved}:{base:string;row:Shipment;can:(s:string)=>boolean;saved:(id?:string)=>Promise<void>}){
 const[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<{action:string;body:object}|null>(null);
 let next=({draft:'plan',planned:'reserve',reserved:'ready',ready:'dispatch'} as Record<string,string>)[row.status];
 const allowed=(action:string)=>(action!=='dispatch'||!row.pallet_exchange?.length||can('pallets.read')&&can('pallets.manage'))&&can(action==='dispatch'?'shipments.dispatch':'shipments.manage')&&(!(['reserve','dispatch'].includes(action)||action==='cancel'&&['reserved','ready'].includes(row.status))||can('inventory.read')&&can('inventory.reserve'));
 async function send(action:string){if(busy||reason.trim().length<3)return;if(!pending&&!window.confirm(action==='dispatch'?'Afsend forsendelsen? Fysisk lager reduceres med de viste varemængder, reservationerne afsluttes, og paller markeres afsendt.':action==='cancel'?'Annullér forsendelsen og frigiv dens reservationer? Fysisk lager ændres ikke.':'Bekræft '+actions[action]+'? Fysisk lager ændres ikke.'))return;const p=pending??{action,body:{idempotency_key:crypto.randomUUID(),version:row.version,reason}};setPending(p);setBusy(true);try{await accessApi(base+'/'+row.id+'/'+p.action,'POST',p.body);await saved(row.id);}catch(e){setError(errorText(e)+' Kontrollér status ved konflikt. Ved usikker forbindelse kan samme kommando prøves igen.');}finally{setBusy(false);}}
 if(['dispatched','cancelled'].includes(row.status))return null;
 return <div><label>Begrundelse for statusændring<input minLength={3} maxLength={1000} disabled={busy||!!pending} value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}{pending?<><button disabled={busy} onClick={()=>void send(pending.action)}>Prøv samme kommando igen</button><button disabled={busy} onClick={()=>void saved(row.id)}>Genindlæs status</button></>:<>{next&&allowed(next)&&<button disabled={busy||reason.trim().length<3} onClick={()=>void send(next)}>{actions[next]}</button>}{allowed('cancel')&&<button disabled={busy||reason.trim().length<3} onClick={()=>void send('cancel')}>{actions.cancel}</button>}</>}</div>;
}
function ShipmentForm({company,initial,canProductionRead,saved,close}:{company:string;initial?:Shipment;canProductionRead:boolean;saved:(id?:string)=>Promise<void>;close:()=>void}){
 const[code,setCode]=useState(initial?.code??''),[customer,setCustomer]=useState(initial?.customer_id??''),[date,setDate]=useState(initial?.ship_date.slice(0,10)??''),[reference,setReference]=useState(initial?.reference??''),[carrier,setCarrier]=useState(initial?.carrier??''),[notes,setNotes]=useState(initial?.notes??''),[reason,setReason]=useState(''),[lines,setLines]=useState<Line[]>(initial?.lines.map(({snapshot,...line})=>line)??[empty()]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<any>(null);
 return <form className="access-card" onSubmit={e=>{e.preventDefault();if(busy)return;const body=pending??{idempotency_key:crypto.randomUUID(),version:initial?.version??0,reason,data:{code,customer_id:customer,ship_date:date,reference,carrier,notes,lines:lines.map(l=>({...l,quantity:l.quantity.replace(',','.'),pallet_spaces:l.pallet_spaces?.replace(',','.')??null}))}};setPending(body);setBusy(true);void accessApi<{id:string}>(`/companies/${company}/shipments${initial?'/'+initial.id+'/edit':''}`,'POST',body).then(r=>saved(r.id)).catch(e=>setError(errorText(e)+' Kontrollér felter/status; samme input genbruges ved gentagelse.')).finally(()=>setBusy(false));}}><h2>{initial?'Redigér kladde':'Ny forsendelse'}</h2><fieldset disabled={busy||!!pending}><label>Forsendelsesnummer<input required maxLength={60} value={code} onChange={e=>setCode(e.target.value)}/></label><Picker path={`/companies/${company}/masterdata/customers`} label="Kunde" value={customer} change={setCustomer}/><label>Forsendelsesdato<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Ordreference<input maxLength={160} value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Transportør<input maxLength={160} value={carrier} onChange={e=>setCarrier(e.target.value)}/></label><label>Forsendelsesnoter<textarea maxLength={4000} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{lines.map((l,i)=><section key={i}><h3>Linje {i+1}</h3><ShipmentLine company={company} line={l} canProductionRead={canProductionRead} change={v=>setLines(old=>old.map((x,n)=>n===i?v:x))}/>{lines.length>1&&<button type="button" onClick={()=>setLines(old=>old.filter((_,n)=>n!==i))}>Fjern linje {i+1}</button>}</section>)}<button type="button" disabled={lines.length>=100} onClick={()=>setLines(old=>[...old,empty()])}>Tilføj varelinje</button><label>Begrundelse<input required minLength={3} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label></fieldset>{error&&<p role="alert">{error}</p>}<button disabled={busy}>{pending?'Prøv samme kladde igen':'Gem kladde'}</button><button type="button" disabled={busy} onClick={()=>{if(!pending||window.confirm('Kladde kan allerede være gemt. Kontrollér listen før ny oprettelse. Luk?'))close();}}>Luk</button></form>;
}
function ShipmentLine({company,line,canProductionRead,change}:{company:string;line:Line;canProductionRead:boolean;change:(l:Line)=>void}){
 const[kind,setKind]=useState('product');const base=`/companies/${company}`;
 const recipes=useQuery({queryKey:['shipment-packing',company,line.item_id],queryFn:()=>accessApi<{id:string;name:string;current_revision_id:string|null}[]>(base+'/recipes?kind=packing&product_id='+line.item_id),enabled:!!line.item_id&&!line.handling_unit_id&&kind==='product',retry:false});
 return <>{canProductionRead&&<PalletSelect company={company} value={line.handling_unit_id??''} choose={p=>change({...empty(),handling_unit_id:p?.id??null,item_id:p?.snapshot.product.id??'',owner_id:p?.snapshot.owner.id??'',location_id:p?.location_id??'',quantity:p?.quantity??''})}/>}{line.handling_unit_id?<p>Hele pallens registrerede indhold: {line.quantity}. Historisk pakning anvendes.</p>:<><label>Varetype<select value={kind} onChange={e=>{setKind(e.target.value);change({...line,item_id:'',packing_revision_id:null});}}><option value="product">Færdigvare</option><option value="material">Materiale</option><option value="packaging">Emballage</option></select></label><Picker path={base+'/items/'+kind} label="Vare" value={line.item_id} change={v=>change({...line,item_id:v,packing_revision_id:null})}/><Picker path={base+'/inventory/owners'} label="Ejer" value={line.owner_id} change={v=>change({...line,owner_id:v})}/><LocationPicker company={company} label="Placering" value={line.location_id||null} change={v=>change({...line,location_id:v??''})}/><label>Mængde<input required inputMode="decimal" value={line.quantity} onChange={e=>change({...line,quantity:e.target.value})}/></label><label>Pakkeopbygning<select value={line.packing_revision_id??''} onChange={e=>change({...line,packing_revision_id:e.target.value||null})}><option value="">Ikke angivet — antal kolli ukendt</option>{recipes.data?.filter(x=>x.current_revision_id).map(x=><option key={x.id} value={x.current_revision_id!}>{x.name}</option>)}</select></label>{recipes.error&&<p role="alert">{errorText(recipes.error)}</p>}</>}<label>Pallepladser for linjen (valgfrit)<input inputMode="decimal" value={line.pallet_spaces??''} onChange={e=>change({...line,pallet_spaces:e.target.value||null})}/></label></>;
}
