import {MoreInformation} from './MoreInformation';
import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {accessApi} from './auth-client';
type Balance={item_id:string;owner_id:string;location_id:string;quantity:string;snapshot:{item:{code:string;name:string};owner:{name:string};location:{name:string};unit:{symbol:string}}};
type Count=Balance&{id:string;status:string;version:number;baseline_quantity:string;counted_quantity:string|null;current_quantity:string;reserved_quantity:string;difference:string|null;stale:boolean;entry_id:string|null;events:{id:string;action:string;reason:string;actor_id:string;created_at:string}[];reservations:{id:string;reference:string;quantity:string}[]};
const labels:Record<string,string>={open:'Åben',counted:'Optalt',approved:'Godkendt',cancelled:'Annulleret',start:'Startet',record:'Optalt',approve:'Godkendt',cancel:'Annulleret'};
const msg=(e:unknown)=>e instanceof Error?e.message:'Handlingen kunne ikke gennemføres.';
export function StockCounts({initialId='',company,permissions}: {initialId?:string;company:string;permissions:string[]}){
 const base=`/companies/${company}/stock-counts`,cache=useQueryClient();
 const[status,setStatus]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState(initialId),[create,setCreate]=useState(false);
 const manage=permissions.includes('counts.manage'),approve=permissions.includes('counts.approve')&&permissions.includes('inventory.adjust');
 const list=useQuery({queryKey:['counts',company,status,page],queryFn:()=>accessApi<{items:Count[];total:number}>(`${base}?page=${page}${status?'&status='+status:''}`),retry:false});
 async function saved(id?:string){await cache.invalidateQueries({queryKey:['counts']});await cache.invalidateQueries({queryKey:['inventory']});setCreate(false);if(id)setSelected(id);}
 return <><p>Optæl hele den fysiske beholdning for én vare, ejer og placering ad gangen, inklusive identificerede paller. Start optællingen før du tæller. Lagerbevægelser undervejs kræver annullering og en ny optælling. Godkendelse bogfører kun forskellen.</p>
 <label>Optællingsstatus<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Alle</option>{['open','counted','approved','cancelled'].map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label>
 {manage&&<button onClick={()=>{setCreate(true);setSelected('');}}>Ny optælling</button>}
 {list.error&&<p role="alert">{msg(list.error)}</p>}{list.isPending&&<p>Henter optællinger…</p>}
 {create&&<StartCount company={company} close={()=>setCreate(false)} saved={saved}/>}
 {list.data&&<section className="access-card"><div className="table-scroll"><table><caption>Optællinger · {list.data.total}</caption><thead><tr>{['Vare','Ejer','Placering','Udgangspunkt','Optalt','Status','Handling'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{list.data.items.map(c=><tr key={c.id}><td>{c.snapshot.item.code} · {c.snapshot.item.name}</td><td>{c.snapshot.owner.name}</td><td>{c.snapshot.location.name}</td><td>{c.baseline_quantity} {c.snapshot.unit.symbol}</td><td>{c.counted_quantity??'Ikke optalt'}</td><td>{labels[c.status]}</td><td><button onClick={()=>{setSelected(c.id);setCreate(false);}}>Vis optælling</button></td></tr>)}</tbody></table></div>{!list.data.items.length&&<p>Ingen optællinger fundet.</p>}<button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Forrige</button><span>Side {page}</span><button disabled={page*25>=list.data.total} onClick={()=>setPage(p=>p+1)}>Næste</button></section>}
 {selected&&<CountDetail key={selected} base={base} id={selected} manage={manage} approve={approve} saved={saved} close={()=>setSelected('')}/>}
 </>;
}
function StartCount({company,close,saved}:{company:string;close:()=>void;saved:(id?:string)=>Promise<void>}){
 const[q,setQ]=useState(''),[page,setPage]=useState(1),[balance,setBalance]=useState<Balance|null>(null);
 const list=useQuery({queryKey:['counts','balances',company,q,page],queryFn:()=>accessApi<{items:Balance[];total:number}>(`/companies/${company}/inventory/balances?q=${encodeURIComponent(q)}&page=${page}`),retry:false});
 return <section className="access-card"><h2>Start optælling</h2><p>Vælg en registreret lagerkombination. Kombinationer med nulbeholdning kan også tælles. Start er uden lagerændring.</p><label>Søg vare til optælling<input maxLength={120} value={q} onChange={e=>{setQ(e.target.value);setPage(1);setBalance(null);}}/></label>
 {list.error&&<p role="alert">{msg(list.error)}</p>}{list.data?.items.map(b=><p key={[b.item_id,b.owner_id,b.location_id].join('/')}><button onClick={()=>setBalance(b)}>{b.snapshot.item.code} · {b.snapshot.owner.name} · {b.snapshot.location.name} · {b.quantity} {b.snapshot.unit.symbol}</button></p>)}
 {list.data&&!list.data.items.length&&<p>Ingen lagerkombinationer fundet.</p>}<button disabled={page===1} onClick={()=>{setPage(p=>p-1);setBalance(null);}}>Forrige lagerkombinationer</button><button disabled={!list.data||page*25>=list.data.total} onClick={()=>{setPage(p=>p+1);setBalance(null);}}>Næste lagerkombinationer</button>
 {balance&&<p role="status">Valgt: {balance.snapshot.item.code} · {balance.snapshot.owner.name} · {balance.snapshot.location.name} · {balance.quantity} {balance.snapshot.unit.symbol}</p>}{balance&&<CountCommand key={[balance.item_id,balance.owner_id,balance.location_id].join('/')} path={`/companies/${company}/stock-counts`} data={{item_id:balance.item_id,owner_id:balance.owner_id,location_id:balance.location_id}} label="Start optælling" confirmation="Start optælling for den valgte vare, ejer og placering? Tæl først efter starten." saved={saved}/>}
 <button onClick={close}>Luk ny optælling</button></section>;
}
function CountDetail({base,id,manage,approve,close,saved}:{base:string;id:string;manage:boolean;approve:boolean;close:()=>void;saved:(id?:string)=>Promise<void>}){
 const detail=useQuery({queryKey:['counts',base,id],queryFn:()=>accessApi<Count>(base+'/'+id),retry:false});const c=detail.data;
 return <section className="access-card"><button onClick={close}>Luk optælling</button><button onClick={()=>void detail.refetch()}>Opdatér optælling</button>{detail.error&&<p role="alert">{msg(detail.error)}</p>}{c&&<><h2>Optælling · {labels[c.status]}</h2><p>{c.snapshot.item.code} · {c.snapshot.item.name} · {c.snapshot.owner.name} · {c.snapshot.location.name}</p><p>Udgangspunkt: {c.baseline_quantity} · Optalt: {c.counted_quantity??'Ikke optalt'} · Difference: {c.difference??'—'} {c.snapshot.unit.symbol}</p><p>Aktuelt fysisk lager: {c.current_quantity} · Reserveret: {c.reserved_quantity}</p>
 {c.stale&&['open','counted'].includes(c.status)&&<p role="alert">Lageret er flyttet siden starten. Annullér denne optælling, start en ny og tæl igen.</p>}
 {!!c.reservations.length&&<><h3>Aktive reservationer (højst 100)</h3><p>En korrektion må ikke bruge reserverede mængder. Frigiv berørte reservationer i Reservationer, eller håndtér dem via Forsendelser, før godkendelsen prøves igen. Identificerede paller er også beskyttede.</p>{c.reservations.map(r=><p key={r.id}>{r.reference} · {r.quantity}</p>)}</>}
 {['open','counted'].includes(c.status)&&<>{manage&&!c.stale&&<MoreInformation enabled={c.status==='counted'}><CountCommand key={'record'+c.version} path={`${base}/${id}/record`} data={{version:c.version}} quantity label="Gem optalt antal" confirmation="Gem det optalte antal? Lageret ændres først ved godkendelse." saved={saved}/></MoreInformation>}{approve&&c.status==='counted'&&!c.stale&&<CountCommand key={'approve'+c.version} path={`${base}/${id}/approve`} data={{version:c.version}} label="Godkend optælling" confirmation={`Godkend difference ${c.difference} ${c.snapshot.unit.symbol}? Fysisk lager korrigeres. Reservationer frigives ikke automatisk.`} saved={saved}/>}{manage&&<CountCommand key={'cancel'+c.version} path={`${base}/${id}/cancel`} data={{version:c.version}} label="Annullér optælling" confirmation="Annullér optællingen uden lagerændring?" saved={saved}/>}</>}
 {c.entry_id&&<p>Korrektionens posterings-ID: {c.entry_id} (findes under Lager → Posteringer).</p>}<h3>Historik</h3>{c.events.map(e=><p key={e.id}>{labels[e.action]} · {new Date(e.created_at).toLocaleString('da-DK')} · {e.reason} · Bruger {e.actor_id}</p>)}</>}</section>;
}
function CountCommand({path,data,label,confirmation,quantity=false,saved}:{path:string;data:object;label:string;confirmation:string;quantity?:boolean;saved:(id?:string)=>Promise<void>}){
 const[reason,setReason]=useState(''),[value,setValue]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState<object|null>(null),[error,setError]=useState('');
 return <form onSubmit={e=>{e.preventDefault();if(busy)return;const q=value.trim().replace(',','.');if(!pending&&quantity&&!/^(0|[1-9][0-9]{0,11})(\.[0-9]{1,8})?$/.test(q)){setError('Indtast nul eller et positivt antal med højst 8 decimaler.');return;}if(!pending&&!window.confirm(confirmation))return;const body=pending??{...data,idempotency_key:crypto.randomUUID(),reason,...(quantity?{quantity:q}:{})};setPending(body);setBusy(true);setError('');void accessApi<Count>(path,'POST',body).then(c=>saved(c.id)).catch(e=>setError(msg(e)+' Ved ændret lager eller beskyttede reservationer: opdatér optællingen og håndtér årsagen. Ved usikker forbindelse: prøv samme handling igen.')).finally(()=>setBusy(false));}}>
 <fieldset disabled={busy||!!pending}>{quantity&&<label>Optalt antal<input required inputMode="decimal" value={value} onChange={e=>setValue(e.target.value)}/></label>}<label>Begrundelse · {label}<input required minLength={3} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label></fieldset>{error&&<p role="alert">{error}</p>}<button className={label==='Annullér optælling'?undefined:'primary'} disabled={busy}>{pending?'Prøv samme handling igen · '+label:label}</button></form>;
}
