import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {accessApi} from './auth-client';
import {Entry} from './Inventory';
import {LocationPicker} from './Locations';
const message=(e:unknown)=>e instanceof Error?e.message:'Flytningen kunne ikke gemmes.';
type Balance={item_id:string;owner_id:string;location_id:string;quantity:string;snapshot:{item:{code:string;name:string};owner:{name:string};location:{name:string};unit:{symbol:string}}};
const balanceKey=(b:Balance)=>[b.item_id,b.owner_id,b.location_id].join(':');
export function Transfers({company,canTransfer,canAdjust,canMasterRead}:{company:string;canTransfer:boolean;canAdjust:boolean;canMasterRead:boolean}){
 const base=`/companies/${company}`,cache=useQueryClient();const[creating,setCreating]=useState(false),[selected,setSelected]=useState(''),[page,setPage]=useState(1),[q,setQ]=useState(''),[status,setStatus]=useState('');
 const list=useQuery({queryKey:['transfers',company,q,page],queryFn:()=>accessApi<{items:{id:string;reference:string;reason:string;posted_at:string}[];total:number}>(base+'/transfers?'+new URLSearchParams({q,page:String(page)})),retry:false});
 async function refresh(){await cache.invalidateQueries({queryKey:['transfers',company]});await cache.invalidateQueries({queryKey:['inventory']});await cache.invalidateQueries({queryKey:['transfer-balances',company]});}
 return <><p>Flyt en vare mellem lagerplaceringer. Ejer og samlet fysisk beholdning bevares.</p><div className="master-toolbar"><label>Søg flytninger<input type="search" value={q} maxLength={120} onChange={e=>{setQ(e.target.value);setPage(1);}}/></label>{canTransfer&&canMasterRead&&<button onClick={()=>setCreating(true)}>Ny lagerflytning</button>}</div>{canTransfer&&!canMasterRead&&<p>Stamdata-læseadgang kræves for at vælge tilplacering.</p>}{status&&<p role="status">{status}</p>}{creating&&<TransferForm company={company} close={()=>setCreating(false)} saved={async()=>{setCreating(false);await refresh();setStatus('Lagerflytningen er bogført.');}}/>}{list.isPending&&<p>Henter flytninger…</p>}{list.error&&<p role="alert">{message(list.error)} <button onClick={()=>void list.refetch()}>Prøv igen</button></p>}{list.data&&<section className="access-card"><table><caption>Lagerflytninger · {list.data.total}</caption><thead><tr><th>Tid</th><th>Reference</th><th>Kommentar</th><th>Handling</th></tr></thead><tbody>{list.data.items.map(r=><tr key={r.id}><td>{new Date(r.posted_at).toLocaleString('da-DK')}</td><td>{r.reference}</td><td>{r.reason}</td><td><button onClick={()=>setSelected(r.id)}>Vis flytning</button></td></tr>)}</tbody></table>{!list.data.items.length&&<p>Ingen lagerflytninger fundet.</p>}<button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Forrige</button><span>Side {page}</span><button disabled={page*25>=list.data.total} onClick={()=>setPage(p=>p+1)}>Næste</button></section>}{selected&&<Entry key={selected} prefix={base+'/inventory'} id={selected} canAdjust={canAdjust} close={()=>setSelected('')} saved={refresh}/>}</>;
}
function TransferForm({company,close,saved}:{company:string;close:()=>void;saved:()=>Promise<void>}){
 const[q,setQ]=useState(''),[page,setPage]=useState(1),[source,setSource]=useState<Balance|null>(null),[destination,setDestination]=useState<string|null>(null),[quantity,setQuantity]=useState(''),[reference,setReference]=useState(''),[comment,setComment]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState<object|null>(null);const[key]=useState(()=>crypto.randomUUID());
 const balances=useQuery({queryKey:['transfer-balances',company,q,page],queryFn:()=>accessApi<{items:Balance[];total:number}>(`/companies/${company}/inventory/balances?`+new URLSearchParams({q,page:String(page)})),retry:false});
 async function submit(){if(busy)return;const amount=quantity.trim().replace(',','.');if(!pending){if(!source||!destination||source.location_id===destination){setError('Vælg beholdning og en anden tilplacering.');return;}if(!/^(0|[1-9][0-9]{0,11})(\.[0-9]{1,8})?$/.test(amount)||/^0(\.0+)?$/.test(amount)){setError('Mængden skal være positiv med højst 8 decimaler.');return;}if(comment.trim().length>0&&comment.trim().length<3){setError('Kommentaren skal have mindst 3 tegn eller være tom.');return;}if(!window.confirm(`Flyt ${amount} ${source.snapshot.unit.symbol} fra ${source.snapshot.location.name} til den valgte placering? Ejer og samlet lager ændres ikke.`))return;}
 const body=pending??{idempotency_key:key,item_id:source!.item_id,owner_id:source!.owner_id,from_location_id:source!.location_id,to_location_id:destination,quantity:amount,reference,comment};setPending(body);setBusy(true);setError('');try{await accessApi(`/companies/${company}/transfers`,'POST',body);await saved();}catch(e){setError(message(e)+' Ved usikker forbindelse: prøv samme flytning igen. Felterne er låst for at undgå dobbeltregistrering.');}finally{setBusy(false);}}
 return <section className="access-card"><h2>Ny lagerflytning</h2><form onSubmit={e=>{e.preventDefault();void submit();}}><fieldset disabled={busy||!!pending}><label>Søg beholdning<input type="search" value={q} maxLength={120} onChange={e=>{setQ(e.target.value);setPage(1);}}/></label>{balances.error&&<p role="alert">{message(balances.error)}</p>}<label>Fra beholdning<select aria-label="Fra beholdning" required value={source?balanceKey(source):''} onChange={e=>setSource(balances.data?.items.find(b=>balanceKey(b)===e.target.value)??null)}><option value="">Vælg vare, ejer og fra-placering</option>{source&&!balances.data?.items.some(b=>balanceKey(b)===balanceKey(source))&&<option value={balanceKey(source)}>{source.snapshot.item.code} · {source.snapshot.location.name}</option>}{balances.data?.items.filter(b=>!/^0(\.0+)?$/.test(b.quantity)).map(b=><option key={balanceKey(b)} value={balanceKey(b)}>{b.snapshot.item.code} · {b.snapshot.owner.name} · {b.snapshot.location.name} · {b.quantity} {b.snapshot.unit.symbol}</option>)}</select></label><button type="button" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Forrige beholdninger</button><button type="button" disabled={!balances.data||page*25>=balances.data.total} onClick={()=>setPage(p=>p+1)}>Flere beholdninger</button>{source&&<p>Fysisk lager ved opslag: {source.quantity} {source.snapshot.unit.symbol}. Den aktuelle mængde kontrolleres igen ved bogføring.</p>}<LocationPicker company={company} label="Tilplacering" value={destination} change={setDestination} storageOnly/><label>Mængde<input required inputMode="decimal" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Reference<input maxLength={160} value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Kommentar<textarea maxLength={1000} value={comment} onChange={e=>setComment(e.target.value)}/></label></fieldset>{error&&<p role="alert">{error}</p>}<button disabled={busy}>{pending?'Prøv samme flytning igen':'Bekræft lagerflytning'}</button><button type="button" disabled={busy} onClick={()=>{if(!pending||window.confirm('Kontrollér flytningerne før en ny registrering; denne kan allerede være gemt. Luk?'))close();}}>Luk</button></form></section>;
}
