import {BadRequestException,Body,ConflictException,Controller,ForbiddenException,Get,Inject,NotFoundException,Param,Post,Query,Req} from '@nestjs/common';
import {PoolClient} from 'pg';
import {z} from 'zod';
import {Actor,AuthRequired} from './auth';
import {DatabaseService} from './database';
const uuid=z.string().uuid(),page=z.object({page:z.coerce.number().int().min(1).max(100000).default(1)}).strict();
function parse<T>(schema:z.ZodType<T>,v:unknown):T{const x=schema.safeParse(v);if(!x.success)throw new BadRequestException();return x.data;}
const delivery=z.object({idempotency_key:uuid,quantity:z.string().regex(/^(0|[1-9]\d{0,11})(\.\d{1,8})?$/).refine(v=>!/^0(\.0+)?$/.test(v)),owner_id:uuid,location_id:uuid,pallet_type_id:uuid.nullable().default(null),production_date:z.string().date(),comment:z.string().trim().max(2000).default('')}).strict();
const reversal=z.object({idempotency_key:uuid,comment:z.string().trim().min(3).max(2000)}).strict();
class OutputAccess{
 constructor(protected readonly database:DatabaseService){}
 protected async run<T>(actor:Actor,c:string,permission:string|null,work:(db:PoolClient)=>Promise<T>):Promise<T>{parse(uuid,c);for(let attempt=0;;attempt++)try{return await this.database.asActor(actor,c,async db=>{const p=(await db.query("select app.allowed('production.read') and app.allowed('inventory.read') as read,app.allowed($1) as write",[permission??'production.read'])).rows[0];if(!p?.read||!p.write)throw new ForbiddenException();return work(db);});}catch(e){const x=e as {code:string;constraint?:string};if(attempt<2&&(['40001','40P01'].includes(x.code)||x.code==='23505'&&['production_deliveries_company_id_idempotency_key_key','handling_unit_moves_company_id_idempotency_key_key'].includes(x.constraint??'')))continue;throw e;}}
 protected async order(db:PoolClient,c:string,o:string){parse(uuid,o);const r=(await db.query('select * from app.production_orders where company_id=$1 and id=$2',[c,o])).rows[0];if(!r)throw new NotFoundException();return r;}
}
@AuthRequired()
@Controller('companies/:companyId/production-orders/:orderId/deliveries')
export class FinishedGoodsController extends OutputAccess{
 constructor(@Inject(DatabaseService)database:DatabaseService){super(database);}
 @Get('summary')
 summary(@Req()r:{actor:Actor},@Param('companyId')c:string,@Param('orderId')o:string){return this.run(r.actor,c,null,async db=>{const ord=await this.order(db,c,o);const totals=(await db.query("select g.q::text good_quantity,d.q::text delivered_quantity,(g.q-d.q)::text remaining_quantity from (select coalesce(sum(case when kind='record' then quantity else -quantity end),0) q from app.production_registrations where company_id=$1 and order_id=$2) g cross join (select coalesce(sum(case when kind='delivery' then quantity else -quantity end),0) q from app.production_deliveries where company_id=$1 and order_id=$2) d",[c,o])).rows[0];return {company_id:c,order_id:o,...totals,unit:ord.snapshot.unit,packing:ord.snapshot.packing};});}
 @Get()
 list(@Req()r:{actor:Actor},@Param('companyId')c:string,@Param('orderId')o:string,@Query()raw:unknown){const q=parse(page,raw);return this.run(r.actor,c,null,async db=>{await this.order(db,c,o);const total=(await db.query('select count(*)::int total from app.production_deliveries where company_id=$1 and order_id=$2',[c,o])).rows[0].total;const items=(await db.query('select d.*,h.id handling_unit_id,h.code pallet_code,exists(select 1 from app.production_deliveries v where v.company_id=d.company_id and v.reverses_id=d.id) reversed from app.production_deliveries d left join app.handling_units h on h.company_id=d.company_id and h.delivery_id=d.id where d.company_id=$1 and d.order_id=$2 order by d.created_at desc,d.id desc limit 25 offset $3',[c,o,(q.page-1)*25])).rows;return {items,total};});}
 @Get(':id')
 get(@Req()r:{actor:Actor},@Param('companyId')c:string,@Param('orderId')o:string,@Param('id')id:string){parse(uuid,id);return this.run(r.actor,c,null,async db=>{await this.order(db,c,o);const row=(await db.query('select * from app.production_deliveries where company_id=$1 and order_id=$2 and id=$3',[c,o,id])).rows[0];if(!row)throw new NotFoundException();return row;});}
 @Post()
 create(@Req()r:{actor:Actor},@Param('companyId')c:string,@Param('orderId')o:string,@Body()body:unknown){const x=parse(delivery,body);return this.run(r.actor,c,'production.deliver',async db=>{await this.order(db,c,o);const params=[c,x.idempotency_key,o,x.quantity,x.owner_id,x.location_id,x.pallet_type_id,x.production_date,x.comment];const old=(await db.query("select *,kind='delivery' and order_id=$3 and quantity=$4::numeric and owner_id=$5 and location_id=$6 and pallet_type_id is not distinct from $7::uuid and production_date=$8::date and comment=$9 as same from app.production_deliveries where company_id=$1 and idempotency_key=$2",params)).rows[0];if(old){if(!old.same)throw new ConflictException();return old;}return (await db.query("insert into app.production_deliveries(company_id,idempotency_key,order_id,kind,quantity,owner_id,location_id,pallet_type_id,production_date,comment) values($1,$2,$3,'delivery',$4,$5,$6,$7,$8,$9) returning *",params)).rows[0];});}
 @Post(':id/reverse')
 reverse(@Req()r:{actor:Actor},@Param('companyId')c:string,@Param('orderId')o:string,@Param('id')id:string,@Body()body:unknown){parse(uuid,id);const x=parse(reversal,body);return this.run(r.actor,c,'production.delivery.correct',async db=>{await this.order(db,c,o);const old=(await db.query('select * from app.production_deliveries where company_id=$1 and idempotency_key=$2',[c,x.idempotency_key])).rows[0];if(old){if(old.order_id!==o||old.kind!=='reversal'||old.reverses_id!==id||old.comment!==x.comment)throw new ConflictException();return old;}const original=(await db.query("select * from app.production_deliveries where company_id=$1 and order_id=$2 and id=$3 and kind='delivery'",[c,o,id])).rows[0];if(!original)throw new NotFoundException();return(await db.query("insert into app.production_deliveries(company_id,order_id,idempotency_key,kind,quantity,owner_id,location_id,production_date,comment,reverses_id) values($1,$2,$3,'reversal',1,$4,$5,$6,$7,$8) returning *",[c,o,x.idempotency_key,original.owner_id,original.location_id,original.production_date,x.comment,id])).rows[0];});}
}
@AuthRequired()
@Controller('companies/:companyId/handling-units')
export class HandlingUnitsController extends OutputAccess{
 constructor(@Inject(DatabaseService)database:DatabaseService){super(database);}
 @Get()
 list(@Req()r:{actor:Actor},@Param('companyId')c:string,@Query()raw:unknown){const q=parse(z.object({page:z.coerce.number().int().min(1).max(100000).default(1),q:z.string().trim().max(120).default('')}).strict(),raw);return this.run(r.actor,c,null,async db=>{const params=[c,'%'+q.q.replace(/[\\%_]/g,'\\$&')+'%'];const where='h.company_id=$1 and (h.code ilike $2 or d.snapshot->\'product\'->>\'name\' ilike $2 or d.snapshot->>\'order_code\' ilike $2)';const source='app.handling_units h join app.production_deliveries d on d.company_id=h.company_id and d.id=h.delivery_id';const total=(await db.query('select count(*)::int total from '+source+' where '+where,params)).rows[0].total;return {items:(await db.query('select h.*,d.order_id,d.quantity,d.production_date,d.snapshot,coalesce((select m.snapshot->\'to_location\' from app.handling_unit_moves m where m.company_id=h.company_id and m.handling_unit_id=h.id order by m.created_at desc,m.id desc limit 1),d.snapshot->\'location\') current_location from '+source+' where '+where+' order by h.code limit 25 offset $3',[...params,(q.page-1)*25])).rows,total};});}
 @Get(':id')
 get(@Req()r:{actor:Actor},@Param('companyId')c:string,@Param('id')id:string){parse(uuid,id);return this.run(r.actor,c,null,async db=>{const row=(await db.query('select h.*,d.order_id,d.quantity,d.production_date,d.snapshot,coalesce((select m.snapshot->\'to_location\' from app.handling_unit_moves m where m.company_id=h.company_id and m.handling_unit_id=h.id order by m.created_at desc,m.id desc limit 1),d.snapshot->\'location\') current_location from app.handling_units h join app.production_deliveries d on d.company_id=h.company_id and d.id=h.delivery_id where h.company_id=$1 and h.id=$2',[c,id])).rows[0];if(!row)throw new NotFoundException();return row;});}
 @Get(':id/moves')
 history(@Req()r:{actor:Actor},@Param('companyId')c:string,@Param('id')id:string,@Query()raw:unknown){parse(uuid,id);const q=parse(page,raw);return this.run(r.actor,c,null,async db=>{if(!(await db.query('select id from app.handling_units where company_id=$1 and id=$2',[c,id])).rows[0])throw new NotFoundException();return {items:(await db.query('select * from app.handling_unit_moves where company_id=$1 and handling_unit_id=$2 order by created_at desc,id desc limit 25 offset $3',[c,id,(q.page-1)*25])).rows};});}
 @Post(':id/moves')
 move(@Req()r:{actor:Actor},@Param('companyId')c:string,@Param('id')id:string,@Body()raw:unknown){parse(uuid,id);const x=parse(reversal.extend({to_location_id:uuid}),raw);return this.run(r.actor,c,'inventory.transfer',async db=>{const old=(await db.query('select * from app.handling_unit_moves where company_id=$1 and idempotency_key=$2',[c,x.idempotency_key])).rows[0];if(old){if(old.handling_unit_id!==id||old.to_location_id!==x.to_location_id||old.comment!==x.comment)throw new ConflictException();return old;}if(!(await db.query('select id from app.handling_units where company_id=$1 and id=$2',[c,id])).rows[0])throw new NotFoundException();return(await db.query('insert into app.handling_unit_moves(company_id,handling_unit_id,idempotency_key,to_location_id,comment) values($1,$2,$3,$4,$5) returning *',[c,id,x.idempotency_key,x.to_location_id,x.comment])).rows[0];});}
}
