import {BadRequestException,Body,ConflictException,Controller,ForbiddenException,Get,Inject,NotFoundException,Param,Post,Query,Req} from '@nestjs/common';
import {PoolClient} from 'pg';
import {z} from 'zod';
import {Actor,AuthRequired} from './auth';
import {DatabaseService} from './database';
import {scaled} from './recipe-calculation';
const uuid=z.string().uuid();
function parse<T>(schema:z.ZodType<T>,v:unknown):T{const r=schema.safeParse(v);if(!r.success)throw new BadRequestException();return r.data;}
const record=z.object({idempotency_key:uuid,quantity:z.string().regex(/^(?:0|[1-9]\d{0,11})(?:\.\d{1,8})?$/).refine(v=>{try{return scaled(v)>0n;}catch{return false;}}),boxes:z.number().int().min(0).max(2147483647).nullable().default(null),comment:z.string().trim().max(2000).default('')}).strict();
@AuthRequired()
@Controller('companies/:companyId/production-orders/:orderId/registrations')
export class ProductionRegistrationsController {
 constructor(@Inject(DatabaseService)private readonly database:DatabaseService){}
 private async run<T>(actor:Actor,c:string,permission:string|null,work:(db:PoolClient)=>Promise<T>):Promise<T>{parse(uuid,c);for(let attempt=0;;attempt++){try{return await this.database.asActor(actor,c,async db=>{const r=await db.query("select app.allowed('production.read') as read,app.allowed($1) as write",[permission??'production.read']);if(!r.rows[0]?.read||!r.rows[0]?.write)throw new ForbiddenException();return work(db);});}catch(e){const x=e as {code:string;constraint?:string};if(attempt<2&&(['40001','40P01'].includes(x.code)||(x.code==='23505'&&x.constraint==='production_registrations_company_id_idempotency_key_key')))continue;throw e;}}}
 private async order(db:PoolClient,c:string,o:string,lock=false){parse(uuid,o);const r=await db.query(`select * from app.production_orders where company_id=$1 and id=$2${lock?' for update':''}`,[c,o]);if(!r.rows[0])throw new NotFoundException();return r.rows[0];}
 @Get()
 list(@Req()req:{actor:Actor},@Param('companyId')c:string,@Param('orderId')o:string,@Query()query:unknown){const q=parse(z.object({page:z.coerce.number().int().min(1).max(100000).default(1),limit:z.coerce.number().int().min(1).max(100).default(25)}).strict(),query);return this.run(req.actor,c,null,async db=>{await this.order(db,c,o);const count=await db.query('select count(*)::int as total from app.production_registrations where company_id=$1 and order_id=$2',[c,o]);const rows=await db.query('select r.*,exists(select 1 from app.production_registrations v where v.company_id=r.company_id and v.reverses_id=r.id) as reversed from app.production_registrations r where company_id=$1 and order_id=$2 order by created_at desc,id desc limit $3 offset $4',[c,o,q.limit,(q.page-1)*q.limit]);return {items:rows.rows,total:count.rows[0].total};});}
 @Get('summary')
 summary(@Req()req:{actor:Actor},@Param('companyId')c:string,@Param('orderId')o:string){return this.run(req.actor,c,null,async db=>{const order=await this.order(db,c,o);const row=(await db.query("select coalesce(sum(case when kind='record' then quantity else -quantity end),0)::text as good_quantity from app.production_registrations where company_id=$1 and order_id=$2",[c,o])).rows[0];const [whole,fraction='']=row.good_quantity.split('.');const good=BigInt(whole)*100000000n+BigInt(fraction.padEnd(8,'0')),planned=scaled(order.quantity);return {company_id:c,order_id:o,good_quantity:row.good_quantity,planned_quantity:order.quantity,progress_percent:((good*10000n/planned)/100n).toString()+'.'+((good*10000n/planned)%100n).toString().padStart(2,'0'),overproduced:good>planned,unit:order.snapshot.unit};});}
 @Get(':id')
 detail(@Req()req:{actor:Actor},@Param('companyId')c:string,@Param('orderId')o:string,@Param('id')id:string){parse(uuid,id);return this.run(req.actor,c,null,async db=>{await this.order(db,c,o);const row=(await db.query('select * from app.production_registrations where company_id=$1 and order_id=$2 and id=$3',[c,o,id])).rows[0];if(!row)throw new NotFoundException();return row;});}
 @Post()
 create(@Req()req:{actor:Actor},@Param('companyId')c:string,@Param('orderId')o:string,@Body()body:unknown){const x=parse(record,body);return this.run(req.actor,c,'production.record',async db=>{await this.order(db,c,o);const old=(await db.query("select *,quantity=$3::numeric and boxes is not distinct from $4::integer as same from app.production_registrations where company_id=$1 and idempotency_key=$2",[c,x.idempotency_key,x.quantity,x.boxes])).rows[0];if(old){if(old.order_id!==o||old.kind!=='record'||!old.same||old.comment!==x.comment)throw new ConflictException();return old;}return(await db.query("insert into app.production_registrations(company_id,order_id,idempotency_key,kind,quantity,boxes,comment) values($1,$2,$3,'record',$4,$5,$6) returning *",[c,o,x.idempotency_key,x.quantity,x.boxes,x.comment])).rows[0];});}
 @Post(':id/reverse')
 reverse(@Req()req:{actor:Actor},@Param('companyId')c:string,@Param('orderId')o:string,@Param('id')id:string,@Body()body:unknown){parse(uuid,id);const x=parse(z.object({idempotency_key:uuid,comment:z.string().trim().min(1).max(2000)}).strict(),body);return this.run(req.actor,c,'production.correct',async db=>{await this.order(db,c,o);const old=(await db.query('select * from app.production_registrations where company_id=$1 and idempotency_key=$2',[c,x.idempotency_key])).rows[0];if(old){if(old.order_id!==o||old.kind!=='reversal'||old.reverses_id!==id||old.comment!==x.comment)throw new ConflictException();return old;}if(!(await db.query("select id from app.production_registrations where company_id=$1 and order_id=$2 and id=$3 and kind='record'",[c,o,id])).rows[0])throw new NotFoundException();return(await db.query("insert into app.production_registrations(company_id,order_id,idempotency_key,kind,quantity,comment,reverses_id) values($1,$2,$3,'reversal',1,$4,$5) returning *",[c,o,x.idempotency_key,x.comment,id])).rows[0];});}
}
