import {BadRequestException,Body,ConflictException,Controller,ForbiddenException,Get,Inject,NotFoundException,Param,Patch,Post,Query,Req} from '@nestjs/common';
import {PoolClient} from 'pg';
import {z} from 'zod';
import {Actor,AuthRequired} from './auth';
import {DatabaseService} from './database';
import {calculate,scaled,RecipeRevision} from './recipe-calculation';
const uuid=z.string().uuid();
const quantity=z.string().regex(/^(?:0|[1-9]\d{0,11})(?:\.\d{1,8})?$/).refine(v=>{try{return scaled(v)>0n;}catch{return false;}});
const date=z.string().datetime({offset:true}).nullable();
const fields=z.object({code:z.string().trim().min(1).max(60),quantity,customer_id:uuid.nullable().default(null),machine_id:uuid.nullable().default(null),bom_revision_id:uuid.nullable().default(null),packing_revision_id:uuid.nullable().default(null),packing_overrides:z.array(z.object({component_id:uuid,quantity}).strict()).max(100).default([]),planned_start:date.default(null),deadline:date.default(null),priority:z.number().int().min(0).max(3).default(0),notes:z.string().max(4000).default('')}).strict();
function parse<T>(schema:z.ZodType<T>,v:unknown):T{const r=schema.safeParse(v);if(!r.success)throw new BadRequestException();return r.data;}
type Snapshot={bom?:RecipeRevision;packing?:RecipeRevision;unit?:{symbol:string};machine?:unknown};
export function orderNeeds(order:{quantity:string;snapshot:Snapshot}){
 const s=order.snapshot,warnings:string[]=[];
 if(!s.unit)warnings.push('Lagerenhed mangler.');if(!s.bom)warnings.push('Stykliste mangler; materialebehov kan ikke beregnes.');if(!s.packing)warnings.push('Pakkeopbygning mangler.');if(!s.machine)warnings.push('Maskine mangler.');
 return {warnings,requirements:s.bom||s.packing?calculate(order.quantity,s.bom??undefined,s.packing??undefined):null};
}
@AuthRequired()
@Controller('companies/:companyId/production-orders')
export class ProductionOrdersController {
 constructor(@Inject(DatabaseService)private readonly database:DatabaseService){}
 private async run<T>(actor:Actor,company:string,write:boolean,work:(db:PoolClient)=>Promise<T>):Promise<T>{parse(uuid,company);for(let attempt=0;;attempt++){try{return await this.database.asActor(actor,company,async db=>{const r=await db.query("select app.allowed('production.read') as read,app.allowed('production.manage') and app.allowed('masterdata.read') as manage");if(!r.rows[0]?.read||(write&&!r.rows[0]?.manage))throw new ForbiddenException();return work(db);});}catch(e){const failure=e as {code:string;constraint?:string};if(attempt<2&&(['40001','40P01'].includes(failure.code)||(failure.code==='23505'&&failure.constraint==='production_orders_company_id_idempotency_key_key')))continue;throw e;}}}
 private async find(db:PoolClient,c:string,id:string,lock=false){parse(uuid,id);const r=await db.query(`select * from app.production_orders where company_id=$1 and id=$2${lock?' for update':''}`,[c,id]);if(!r.rows[0])throw new NotFoundException();return r.rows[0];}
 private present(row:any){const {request,...safe}=row;return {...safe,...orderNeeds(row)};}
 @Get()
 list(@Req()req:{actor:Actor},@Param('companyId')c:string,@Query()query:unknown){const q=parse(z.object({q:z.string().max(120).default(''),status:z.enum(['draft','planned','ready']).optional(),machine_id:uuid.optional(),customer_id:uuid.optional(),from:z.string().datetime({offset:true}).optional(),to:z.string().datetime({offset:true}).optional(),page:z.coerce.number().int().min(1).max(100000).default(1),limit:z.coerce.number().int().min(1).max(100).default(25)}).strict(),query);return this.run(req.actor,c,false,async db=>{const params=[c,'%'+q.q+'%',q.status??null,q.machine_id??null,q.customer_id??null,q.from??null,q.to??null];const where="company_id=$1 and (code ilike $2 or snapshot->'product'->>'name' ilike $2) and ($3::text is null or status=$3) and ($4::uuid is null or machine_id=$4) and ($5::uuid is null or customer_id=$5) and ($6::timestamptz is null or planned_start >= $6) and ($7::timestamptz is null or planned_start <= $7)";const count=await db.query('select count(*)::int as total from app.production_orders where '+where,params);const list=await db.query('select id,company_id,code,status,quantity,priority,problem,planned_start,deadline,version,snapshot->\'product\' as product,snapshot->\'machine\' as machine,snapshot->\'customer\' as customer from app.production_orders where '+where+' order by priority desc,planned_start nulls last,created_at desc,id limit $8 offset $9',[...params,q.limit,(q.page-1)*q.limit]);return {items:list.rows,total:count.rows[0].total};});}
 @Get('defaults/:productId')
 defaults(@Req()req:{actor:Actor},@Param('companyId')c:string,@Param('productId')id:string){parse(uuid,id);return this.run(req.actor,c,true,async db=>{const p=(await db.query("select id,customer_id,standard_machine_id,production_notes from app.items where company_id=$1 and id=$2 and kind='product' and active",[c,id])).rows[0];if(!p)throw new NotFoundException();const recipes=(await db.query('select id,name,kind,is_default,current_revision_id from app.recipes where company_id=$1 and product_id=$2 and active and current_revision_id is not null order by kind,is_default desc,name,id',[c,id])).rows;return {product_id:id,customer_id:p.customer_id,machine_id:p.standard_machine_id,notes:p.production_notes,bom_revision_id:recipes.find(r=>r.kind==='bom'&&r.is_default)?.current_revision_id??null,packing_revision_id:recipes.find(r=>r.kind==='packing'&&r.is_default)?.current_revision_id??null,recipes};});}
 @Get(':id')
 detail(@Req()req:{actor:Actor},@Param('companyId')c:string,@Param('id')id:string){return this.run(req.actor,c,false,async db=>this.present(await this.find(db,c,id)));}
 @Get(':id/history')
 history(@Req()req:{actor:Actor},@Param('companyId')c:string,@Param('id')id:string){return this.run(req.actor,c,false,async db=>{await this.find(db,c,id);return(await db.query('select * from app.production_order_audit where company_id=$1 and order_id=$2 order by occurred_at desc,id desc limit 100',[c,id])).rows;});}
 @Post()
 create(@Req()req:{actor:Actor},@Param('companyId')c:string,@Body()body:unknown){const x=parse(fields.extend({product_id:uuid,idempotency_key:uuid}).strict(),body);return this.run(req.actor,c,true,async db=>{const existing=(await db.query('select *,request=$3::jsonb as same from app.production_orders where company_id=$1 and idempotency_key=$2',[c,x.idempotency_key,JSON.stringify(x)])).rows[0];if(existing){if(!existing.same)throw new ConflictException();return this.present(existing);}const r=(await db.query('insert into app.production_orders(company_id,code,product_id,customer_id,machine_id,quantity,bom_revision_id,packing_revision_id,planned_start,deadline,priority,notes,idempotency_key,request,packing_overrides) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) returning *',[c,x.code,x.product_id,x.customer_id,x.machine_id,x.quantity,x.bom_revision_id,x.packing_revision_id,x.planned_start,x.deadline,x.priority,x.notes,x.idempotency_key,JSON.stringify(x),JSON.stringify(x.packing_overrides)])).rows[0];return this.present(r);});}
 @Patch(':id')
 edit(@Req()req:{actor:Actor},@Param('companyId')c:string,@Param('id')id:string,@Body()body:unknown){const x=parse(z.object({version:z.number().int().positive(),data:fields}).strict(),body);return this.run(req.actor,c,true,async db=>{const old=await this.find(db,c,id,true);if(old.version!==x.version||old.status!=='draft')throw new ConflictException();const d=x.data;const row=(await db.query('update app.production_orders set code=$3,customer_id=$4,machine_id=$5,quantity=$6,bom_revision_id=$7,packing_revision_id=$8,planned_start=$9,deadline=$10,priority=$11,notes=$12,packing_overrides=$13,version=version+1 where company_id=$1 and id=$2 returning *',[c,id,d.code,d.customer_id,d.machine_id,d.quantity,d.bom_revision_id,d.packing_revision_id,d.planned_start,d.deadline,d.priority,d.notes,JSON.stringify(d.packing_overrides)])).rows[0];return this.present(row);});}
 @Post(':id/status')
 status(@Req()req:{actor:Actor},@Param('companyId')c:string,@Param('id')id:string,@Body()body:unknown){const x=parse(z.object({version:z.number().int().positive(),status:z.enum(['draft','planned','ready'])}).strict(),body);return this.run(req.actor,c,true,async db=>{const old=await this.find(db,c,id,true);if(old.version!==x.version)throw new ConflictException();return this.present((await db.query('update app.production_orders set status=$3,version=version+1 where company_id=$1 and id=$2 returning *',[c,id,x.status])).rows[0]);});}
 @Post(':id/problem')
 problem(@Req()req:{actor:Actor},@Param('companyId')c:string,@Param('id')id:string,@Body()body:unknown){const x=parse(z.object({version:z.number().int().positive(),problem:z.string().trim().max(1000)}).strict(),body);return this.run(req.actor,c,true,async db=>{const old=await this.find(db,c,id,true);if(old.version!==x.version)throw new ConflictException();return this.present((await db.query('update app.production_orders set problem=$3,version=version+1 where company_id=$1 and id=$2 returning *',[c,id,x.problem])).rows[0]);});}
}
