import {BadRequestException,Body,ConflictException,Controller,ForbiddenException,Get,Inject,NotFoundException,Param,Post,Query,Req} from '@nestjs/common';
import {PoolClient} from 'pg';
import {z} from 'zod';
import {Actor,AuthRequired} from './auth';
import {DatabaseService} from './database';
const uuid=z.string().uuid();
const amount=z.string().regex(/^(0|[1-9][0-9]{0,11})(\.[0-9]{1,8})?$/);
function parse<T>(s:z.ZodType<T>,v:unknown):T{const r=s.safeParse(v);if(!r.success)throw new BadRequestException();return r.data;}
@AuthRequired()
@Controller('companies/:companyId/production-orders/:orderId/close')
export class ProductionCloseController{
 constructor(@Inject(DatabaseService)private readonly database:DatabaseService){}
 private async run<T>(actor:Actor,c:string,permission:string|null,work:(db:PoolClient)=>Promise<T>):Promise<T>{parse(uuid,c);for(let attempt=0;;attempt++)try{return await this.database.asActor(actor,c,async db=>{const p=(await db.query("select app.allowed('production.read') and app.allowed('inventory.read') as read,app.allowed($1) as action,app.allowed('inventory.transfer') as transfer,app.allowed('production.manage') and app.allowed('masterdata.read') as manage",[permission??'production.read'])).rows[0];if(!p?.read||!p.action||permission==='production.return'&&!p.transfer||permission==='production.close'&&!p.manage)throw new ForbiddenException();return work(db);});}catch(e:any){if(attempt<2&&(['40001','40P01'].includes(e?.code)||e?.code==='23505'&&['inventory_entries_company_id_idempotency_key_key','production_closures_company_id_idempotency_key_key'].includes(e?.constraint)))continue;throw e;}}
 private async order(db:PoolClient,c:string,o:string){parse(uuid,o);if(!(await db.query('select id from app.production_orders where company_id=$1 and id=$2',[c,o])).rows[0])throw new NotFoundException();}
 @Get('review')
 review(@Req()r:{actor:Actor},@Param('companyId')c:string,@Param('orderId')o:string){return this.run(r.actor,c,null,async db=>{await this.order(db,c,o);return(await db.query('select app.production_close_review($1,$2) as review',[c,o])).rows[0].review;});}
 @Get('returns')
 returns(@Req()r:{actor:Actor},@Param('companyId')c:string,@Param('orderId')o:string,@Query()raw:unknown){const q=parse(z.object({page:z.coerce.number().int().min(1).max(100000).default(1)}).strict(),raw);return this.run(r.actor,c,null,async db=>{await this.order(db,c,o);const where='company_id=$1 and production_order_id=$2 and production_return_of is not null';return {items:(await db.query('select * from app.inventory_entries where '+where+' order by posted_at desc,id desc limit 25 offset $3',[c,o,(q.page-1)*25])).rows,total:(await db.query('select count(*)::int total from app.inventory_entries where '+where,[c,o])).rows[0].total};});}
 @Get('result')
 result(@Req()r:{actor:Actor},@Param('companyId')c:string,@Param('orderId')o:string){return this.run(r.actor,c,null,async db=>{await this.order(db,c,o);const row=(await db.query('select * from app.production_closures where company_id=$1 and order_id=$2',[c,o])).rows[0];if(!row)throw new NotFoundException();return row;});}
 @Post('returns')
 returnMaterial(@Req()r:{actor:Actor},@Param('companyId')c:string,@Param('orderId')o:string,@Body()raw:unknown){const b=parse(z.object({idempotency_key:uuid,issue_id:uuid,to_location_id:uuid,quantity:amount.refine(x=>!/^0(\.0+)?$/.test(x)),comment:z.string().trim().min(3).max(1000)}).strict(),raw);return this.run(r.actor,c,'production.return',async db=>{await this.order(db,c,o);const issue=(await db.query("select l.* from app.inventory_entries e join app.inventory_lines l on l.company_id=e.company_id and l.entry_id=e.id and l.quantity>0 where e.company_id=$1 and e.production_order_id=$2 and e.id=$3 and e.kind='transfer' and e.production_return_of is null",[c,o,b.issue_id])).rows[0];if(!issue)throw new NotFoundException();if(issue.location_id===b.to_location_id)throw new BadRequestException();const lines=JSON.stringify([{item_id:issue.item_id,owner_id:issue.owner_id,location_id:issue.location_id,quantity:'-'+b.quantity},{item_id:issue.item_id,owner_id:issue.owner_id,location_id:b.to_location_id,quantity:b.quantity}]);const old=(await db.query('select *,request=$3::jsonb as same from app.inventory_entries where company_id=$1 and idempotency_key=$2',[c,b.idempotency_key,lines])).rows[0];if(old){if(old.kind!=='transfer'||old.production_order_id!==o||old.production_return_of!==b.issue_id||old.reason!==b.comment||!old.same)throw new ConflictException();return old;}return(await db.query("insert into app.inventory_entries(company_id,idempotency_key,kind,reason,request,production_order_id,production_return_of) values($1,$2,'transfer',$3,$4,$5,$6) returning *",[c,b.idempotency_key,b.comment,lines,o,b.issue_id])).rows[0];});}
 @Post()
 complete(@Req()r:{actor:Actor},@Param('companyId')c:string,@Param('orderId')o:string,@Body()raw:unknown){const b=parse(z.object({idempotency_key:uuid,review_token:z.string().regex(/^[a-f0-9]{32}$/),rejected_quantity:amount,comment:z.string().trim().min(3).max(2000),confirm_materials:z.literal(true)}).strict(),raw);return this.run(r.actor,c,'production.close',async db=>{await this.order(db,c,o);const old=(await db.query('select *,rejected_quantity=$3::numeric as same from app.production_closures where company_id=$1 and idempotency_key=$2',[c,b.idempotency_key,b.rejected_quantity])).rows[0];if(old){if(old.order_id!==o||old.review_token!==b.review_token||!old.same||old.comment!==b.comment)throw new ConflictException();return old;}return(await db.query('insert into app.production_closures(company_id,order_id,idempotency_key,review_token,rejected_quantity,comment) values($1,$2,$3,$4,$5,$6) returning *',[c,o,b.idempotency_key,b.review_token,b.rejected_quantity,b.comment])).rows[0];});}
}
